brunner56Rivenfrontend:
  brunner56Rivenfrontend:
    containerSecurityContext:
      readOnlyRootFilesystem: false
      seccompProfile:
        type: RuntimeDefault
    image:
      repository: ghcr.io/elfhosted/riven-frontend
      tag: v0.20.0@sha256:c4d792868a8113a2f57f504fe371cbcd8c52172d734c812c366bff352672998e
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "0"
        memory: 20Mi
  podSecurityContext:
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 568
    runAsUser: 568
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
kubernetesClusterDomain: cluster.local
