addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints: null
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-14T17:40:45Z"
  generateName: gluetun-premiumize-gr-
  labels:
    app: gluetun-premiumize-gr
    component: vpn-gateway
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: gluetun-premiumize-gr
  name: gluetun-premiumize-gr-t4tmh
  namespace: vpn-gateway
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: gluetun-premiumize-gr
ports: null
