addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints: null
kind: EndpointSlice
metadata:
  generateName: gluetun-premiumize-de-
  labels:
    app: gluetun-premiumize-de
    component: vpn-gateway
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: gluetun-premiumize-de
  name: gluetun-premiumize-de-t9bmq
  namespace: vpn-gateway
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: gluetun-premiumize-de
ports: null
