apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elfhosted-combined.fullname" . }}-recyclarr-config
  labels:
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  {{- include "elfhosted-combined.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
data:
  recyclarr.yaml: {{ .Values.recyclarrConfig.recyclarrYaml | quote }}
