apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elfhosted-combined.fullname" . }}-config
  labels:
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  {{- include "elfhosted-combined.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
data:
  cli_debrid_update.sh: {{ .Values.config.cliDebridUpdateSh | toYaml | indent 1 }}
  config.yml: {{ .Values.config.configYml | toYaml | indent 1 }}
  plex_update.sh: {{ .Values.config.plexUpdateSh | toYaml | indent 1 }}
  setup.sh: {{ .Values.config.setupSh | toYaml | indent 1 }}
