#!/usr/bin/env python3
"""Render Headscale config.yaml from implicit bootstrap context."""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path


def env(name: str, default: str = "") -> str:
    return os.environ.get(name, default)


def truthy(name: str, default: str = "true") -> bool:
    return env(name, default).lower() in ("1", "true", "yes", "on")


def load_node_ips(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text())
        return {k: str(v) for k, v in data.items() if v}
    except (json.JSONDecodeError, OSError):
        return {}


def load_coredns_ips() -> list[str]:
    raw = env("COREDNS_IPS", "")
    if raw:
        return [x.strip() for x in raw.split(",") if x.strip()]
    path = Path(env("COREDNS_IPS_FILE", ""))
    if path.is_file():
        return [ln.strip() for ln in path.read_text().splitlines() if ln.strip() and not ln.startswith("#")]
    return []


def extra_records(domain: str, magic_base: str, node_ips: dict[str, str]) -> list[dict]:
    records: list[dict] = []
    for host, ip in sorted(node_ips.items()):
        if not ip or ip.startswith("127."):
            continue
        records.append({"name": f"{host}.{magic_base}", "type": "A", "value": ip})
    # Stable edge aliases on the tailnet (updated when tailscale IPs are known).
    for alias in ("traefik", "headscale"):
        records.append({"name": f"{alias}.{magic_base}", "type": "A", "value": env("EXTERNAL_IP", "127.0.0.1")})
    _ = domain
    return records


def split_dns(domain: str, coredns_ips: list[str]) -> dict[str, list[str]]:
    if not coredns_ips:
        return {}
    return {domain: coredns_ips, f"*.{domain}": coredns_ips}


def yaml_scalar(value: str) -> str:
    if value == "":
        return '""'
    if any(c in value for c in ":{}[],&*#?|-<>=!%@\\\""):
        return json.dumps(value)
    return value


def emit_split(split: dict[str, list[str]], indent: int = 10) -> list[str]:
    if not split:
        return [" " * indent + "split: {}"]
    pad = " " * indent
    lines = [pad + "split:"]
    for domain, servers in split.items():
        lines.append(f"{pad}  {yaml_scalar(domain)}:")
        for s in servers:
            lines.append(f"{pad}    - {s}")
    return lines


def emit_extra_records_path() -> str:
    return "/var/lib/headscale/extra-records.json"


def main() -> int:
    domain = env("DOMAIN")
    magic_base = env("HEADSCALE_MAGIC_BASE_DOMAIN", f"myscale.{domain}")
    config_path = Path(env("CONFIG_PATH", "./volumes"))
    node_ips = load_node_ips(config_path / "placement" / "node-ips.json")
    coredns = load_coredns_ips()
    split = split_dns(domain, coredns)

    policy_path = env("HEADSCALE_POLICY_PATH", "/etc/headscale/acl.hujson")
    lines = [
        "---",
        "# Generated by arbitrary-scripts/bootstrap/render-headscale-config.py",
        f"server_url: {yaml_scalar(env('HEADSCALE_SERVER_URL', f'https://headscale.{domain}'))}",
        f"listen_addr: 0.0.0.0:{env('HEADSCALE_HTTP_PORT', '8081')}",
        f"metrics_listen_addr: 127.0.0.1:{env('HEADSCALE_METRICS_PORT', '8080')}",
        "trusted_proxies:",
        "  - 10.76.0.0/16",
        "  - 172.16.0.0/12",
        "  - 127.0.0.1/32",
        "noise:",
        "  private_key_path: /var/lib/headscale/noise_private.key",
        "prefixes:",
        "  v4: 100.64.0.0/10",
        "  v6: fd7a:115c:a1e0::/48",
        f"  allocation: {env('HEADSCALE_PREFIX_ALLOCATION', 'sequential')}",
        "derp:",
        "  server:",
        "    enabled: false",
        "    region_id: 999",
        '    region_code: "headscale"',
        '    region_name: "Headscale Embedded DERP"',
        "    verify_clients: true",
        f'    stun_listen_addr: "0.0.0.0:{env("HEADSCALE_STUN_PORT", "3478")}"',
        "    private_key_path: /var/lib/headscale/derp_server_private.key",
        "    automatically_add_embedded_derp_region: true",
        "    ipv4: 100.64.0.2",
        "    ipv6: fd7a:115c:a1e0::2",
        "  urls:",
        "    - https://controlplane.tailscale.com/derpmap/default",
        "  paths: []",
        "  auto_update_enabled: true",
        "  update_frequency: 3h",
        "disable_check_updates: false",
        "node:",
        f"  expiry: {env('HEADSCALE_NODE_EXPIRY', '0')}",
        "  ephemeral:",
        "    inactivity_timeout: 30m",
        "  routes:",
        "    ha:",
        "      probe_interval: 10s",
        "      probe_timeout: 5s",
        "database:",
        "  type: sqlite",
        f"  debug: {str(truthy('HEADSCALE_DEBUG', 'false')).lower()}",
        "  gorm:",
        f"    prepare_stmt: {str(truthy('HEADSCALE_PREPARE_STMT', 'true')).lower()}",
        f"    parameterized_queries: {str(truthy('HEADSCALE_PARAMETERIZED_QUERIES', 'true')).lower()}",
        f"    skip_err_record_not_found: {str(truthy('HEADSCALE_SKIP_ERR_RECORD_NOT_FOUND', 'true')).lower()}",
        f"    slow_threshold: {env('HEADSCALE_SLOW_THRESHOLD', '1000')}",
        "  sqlite:",
        "    path: /var/lib/headscale/db.sqlite",
        f"    write_ahead_log: {str(truthy('HEADSCALE_WRITE_AHEAD_LOG', 'true')).lower()}",
        f"    wal_autocheckpoint: {env('HEADSCALE_WAL_AUTOCHECKPOINT', '1000')}",
        "acme_url: https://acme-v02.api.letsencrypt.org/directory",
        "acme_email: \"\"",
        "tls_letsencrypt_hostname: \"\"",
        "tls_letsencrypt_cache_dir: /var/lib/headscale/cache",
        "tls_letsencrypt_challenge_type: HTTP-01",
        "tls_letsencrypt_listen: \":http\"",
        "tls_cert_path: \"\"",
        "tls_key_path: \"\"",
        "log:",
        f"  level: {env('HEADSCALE_LOG_LEVEL', 'info')}",
        f"  format: {env('HEADSCALE_LOG_FORMAT', 'text')}",
        "policy:",
        f"  mode: {env('HEADSCALE_POLICY_MODE', 'file')}",
        f"  path: {yaml_scalar(policy_path)}",
        "dns:",
        f"  magic_dns: {str(truthy('HEADSCALE_MAGIC_DNS', 'true')).lower()}",
        f"  base_domain: {yaml_scalar(magic_base)}",
        f"  override_local_dns: {str(truthy('HEADSCALE_OVERRIDE_LOCAL_DNS', 'true')).lower()}",
        "  nameservers:",
        "    global:",
        "      - 1.1.1.1",
        "      - 1.0.0.1",
        "      - 2606:4700:4700::1111",
        "      - 2606:4700:4700::1001",
        *emit_split(split),
        "  search_domains: []",
        f"  extra_records_path: {emit_extra_records_path()}",
        "unix_socket: /var/run/headscale/headscale.sock",
        'unix_socket_permission: "0770"',
        "logtail:",
        f"  enabled: {str(truthy('HEADSCALE_LOGTAIL_ENABLED', 'false')).lower()}",
        "taildrop:",
        f"  enabled: {str(truthy('HEADSCALE_TAILDROP_ENABLED', 'true')).lower()}",
        "auto_update:",
        f"  enabled: {str(truthy('HEADSCALE_AUTO_UPDATE', 'false')).lower()}",
        "",
    ]

    out = Path(sys.argv[1]) if len(sys.argv) > 1 else config_path / "headscale" / "config" / "config.yaml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))

    extra_path = config_path / "headscale" / "lib" / "extra-records.json"
    extra_path.parent.mkdir(parents=True, exist_ok=True)
    extra_path.write_text(json.dumps(extra_records(domain, magic_base, node_ips), indent=2) + "\n")

    acl_path = config_path / "headscale" / "config" / "acl.hujson"
    if not acl_path.exists():
        acl_path.write_text(
            "\n".join(
                [
                    "// Generated permissive bootstrap ACL — tighten for production.",
                    "{",
                    '  "acls": [',
                    '    {"action": "accept", "src": ["*"], "dst": ["*:*"]}',
                    "  ]",
                    "}",
                    "",
                ]
            )
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
