apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: bolabaden
  labels:
    app.kubernetes.io/instance: brunner56
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elfterm
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: bolabaden
  name: elfterm
  namespace: bolabaden
spec:
  clusterIP: 10.43.115.77
  clusterIPs:
  - 10.43.115.77
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3001
  selector:
    app.kubernetes.io/instance: brunner56
    app.kubernetes.io/name: filebrowser
