apiVersion: v1
data:
  tinyproxy.conf: |
    Port 8888
    Listen 0.0.0.0
    # Allow all connections
    Allow 0.0.0.0/0
    Timeout 600
    DisableViaHeader yes
    ReversePath "/" "http://localhost:32400/"
    # ReverseBaseURL "https://brunner56-plex.elfhosted.com"
    # ReverseMagic Yes
    ReverseOnly Yes
    # Anonymous "Host"
    # Anonymous "Authorization"
    # Anonymous "Cookie"
    # Anonymous "X-Forwarded-Proto"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: bolabaden
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: bolabaden
  name: plex-tinyproxy-conf
  namespace: bolabaden
