apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: bolabaden
  labels:
    app.kubernetes.io/instance: brunner56
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rcloneui
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: bolabaden
  name: rcloneui
  namespace: bolabaden
spec:
  clusterIP: 10.43.133.194
  clusterIPs:
  - 10.43.133.194
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: rcloneui
    port: 5572
  - name: webdav-local
    port: 5575
  selector:
    app.kubernetes.io/instance: brunner56
    app.kubernetes.io/name: rcloneui
