apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart-volsync-rd-backup-dest-pvc.fullname" . }}-volsync-rd-backup-dest
  labels:
    app.kubernetes.io/created-by: volsync
  {{- include "chart-volsync-rd-backup-dest-pvc.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.volsyncRdBackupDest.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.volsyncRdBackupDest.storageClass | quote }}
