[rdhttp]
type = http
url = https://my.real-debrid.com//
no_head = false
no_slash = false

[rdwebdav]
type = webdav
url = https://dav.real-debrid.com/
vendor = other
user = brunner56
pass = 

[rdhttp2]
type = http
url = https://my.real-debrid.com//
no_head = false
no_slash = false

[rdwebdav2]
type = webdav
url = https://dav.real-debrid.com/
vendor = other
user = 
pass = 

[zurg]
type = webdav
url = http://zurg:9999/dav
vendor = other
pacer_min_sleep = 0

[zurghttp]
type = http
url = http://zurg:9999/http/
no_head = false
no_slash = false
