x-common-env: &common-env
  PGID: ${PGID:-988}
  PUID: ${PUID:-1001}
  TZ: ${TZ:-America/Chicago}

x-resource-limits: &resource-limits
  cpu_shares: 1024 # CPU share weight (relative, 2-262144). Higher = more CPU *if competing*.
  #  mem_limit: 512m        # Max RAM usage (e.g., 64m, 1g). Exceeding = container kill.
  #  mem_reservation: 325m  # Soft RAM limit (e.g., 32m, 512m).  Best effort, not guaranteed.
  #  mem_swappiness: 30      # Swap usage (0-100). 0 = off. Higher = more swap, may slow down container.
  #memswap_limit: 1024m    # Max RAM + Swap.  Usually same as mem_limit.
  labels:
    autoheal: "true"

x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
  labels:
    autoheal: "true"
    swarm.autoscaler: "true"

x-swarm-resource-limits: &swarm-resource-limits
  resources:
    limits:
      cpus: "0.10"
      memory: 1024M
#    reservations:
#     cpus: '0.05'
#    memory:  256M

x-swarm-worker-priority: &swarm-worker-priority
  placement:
    preferences:
      - spread: node.labels.worker_priority

x-swarm-manager-only: &swarm-manager-only
  placement:
    constraints:
      - node.role == manager

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - ${OLLAMA_PORT:-11434}:11434
    volumes:
      - ${ROOT_DIR:-.}/configs/ollama/code:/code
      - ${ROOT_DIR:-.}/configs/ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE:-24h}
      - OLLAMA_HOST=${OLLAMA_HOST:-0.0.0.0}
    networks:
      - infrastructure_network
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      resources:
        reservations:
  #          devices:
  #            - driver: nvidia
  #              count: all
  #              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    hostname: open-webui
    extra_hosts:
      - host.docker.internal:172.17.0.1
    networks:
      - infrastructure_network
    volumes:
      - ${ROOT_DIR:-.}/configs/open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT:-8073}:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://ollama:${OLLAMA_PORT:-11434} #comma separated ollama hosts
      - ENV=${ENV:-dev}
      - WEBUI_AUTH=${WEBUI_AUTH:-False}
      - WEBUI_NAME=${WEBUI_NAME:-valiantlynx AI}
      - WEBUI_URL=http://open-webui.${DOMAIN}:${OPEN_WEBUI_PORT:-8073}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:?WEBUI_SECRET_KEY is not set}
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
    restart: unless-stopped
