x-common-env: &common-env
  TZ: ${TZ:-America/Chicago}
  PUID: ${PUID:-1002}
  PGID: ${PGID:-988}
  UMASK: ${UMASK:-002}

x-common-uidgid: &common-uidgid
  user: ${PUID:-1002}:${PGID:-988}

x-resource-limits: &resource-limits
  labels:
    autoheal: "true"

x-common-logging: &common-logging
  logging:
    driver: "local"
    options:
      max-file: "5"
      max-size: "10m"
services:
  plex_authentication:
    depends_on:
      plex:
        condition: service_healthy
    image: ghcr.io/westsurname/scripts/plex_authentication:latest
    container_name: plex_authentication_service
    volumes:
      - ${CONFIG_PATH:-./configs}/plex/plex_authentication/tokens.json:/app/shared/tokens.json
      - ${CONFIG_PATH:-./configs}/plex/plex_authentication/sockets:/app/sockets
    env_file:
      - ${CONFIG_PATH:-./configs}/plex/west/.env
    environment:
      <<: *common-env
    restart: always
  plex_request:
    depends_on:
      plex:
        condition: service_healthy
    image: ghcr.io/westsurname/scripts/plex_request:latest
    container_name: plex_request_service
    volumes:
      - ${CONFIG_PATH:-./configs}/plex/plex_request/tokens.json:/app/shared/tokens.json
      - ${CONFIG_PATH:-./configs}/plex/plex_request/sockets:/app/sockets
    env_file:
      - ${CONFIG_PATH:-./configs}/plex/west/.env
    environment:
      - BLACKHOLE_RD_MOUNT_REFRESH_SECONDS=30
      - BLACKHOLE_WAIT_FOR_TORRENT_TIMEOUT=10
#    profiles:
#      - all
#      - plex_request
    restart: always
  plex_watchlist_service:
    depends_on:
      plex:
        condition: service_healthy
      plex_authentication:
        condition: service_started
    image: ghcr.io/westsurname/scripts/watchlist:latest
    container_name: plex_watchlist_service
    volumes:
      - ${CONFIG_PATH:-./configs}/plex/plex_watchlist/tokens.json:/app/shared/tokens.json
    env_file:
      - ${CONFIG_PATH:-./configs}/plex/west/.env
    environment:
      <<: *common-env
#    profiles:
#      - all
#      - plex_watchlist
    restart: always
  realdebrid-account-monitor:
    build:
      context: ${SRC_PATH:-./src}/realdebrid-account-monitor
#    image: realdebrid-account-monitor
    container_name: realdebrid-account-monitor
    environment:
      <<: *common-env
      # A list of your real debrid api keys. e.g. ["key1", "key2"]
      # You can get your api key from https://real-debrid.com/apitoken
      TOKENS: '["TE6M7M2GGBN6H6XT2OZTUQIX42LEPJ4EIZIHTN73HAW2TJUZAFHA", "FA5NDX4HOAQROKATB6WD7JTZLBZPWYLQSQE6UNBZ7XTUPAKG3YPQ"]'
      # How often to check the accounts for traffic. This is a cron schedule.
      # e.g. every hour: 0 * * * *
      CRON_SCHEDULE: '0 * * * *'
    volumes:
      - ${DATA_DIR:-./data}/realdebrid-account-monitor:/app/data
#    profiles:
#      - all
#      - realdebrid-account-monitor
    restart: always

  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest    
    container_name: zurg
    hostname: zurg
    networks:
      publicnet:
        ipv4_address: ${ZURG_IPV4_ADDRESS:-10.76.128.48}
    ports:
      - 9999:9999
    volumes:
      - ${CONFIG_PATH:-./configs}/zurg/scripts/plex_update.sh:/app/plex_update.sh
      - ${CONFIG_PATH:-./configs}/zurg/app/config.yml:/app/config.yml
      - /mnt/remote/realdebrid/zurg/data:/app/data
      - /mnt/remote/realdebrid/zurg/logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:9999/dav/version.txt || exit 1"]
      interval: ${ZURG_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${ZURG_HEALTHCHECK_TIMEOUT:-10s}
      retries: ${ZURG_HEALTHCHECK_RETRIES:-3}
    labels: 
      traefik.enable: "true"
#      traefik.http.routers.zurg.middlewares: tinyauth@docker
      traefik.http.routers.zurg.rule: Host(`zurg.${DOMAIN}`) || Host(`zurg.${DUCKDNS_DOMAIN}`) || Host(`zurg.${TS_SUBDOMAIN}.duckdns.org`) || Host(`zurg.localhost`)
      traefik.http.services.zurg.loadbalancer.server.port: 9999
#    profiles:
#      - all
#      - zurg
#      - debrid_media_server
    restart: always
  rclone-zurg:
    # 🔹🔹 Rclone (with Zurg)🔹🔹
    # This configuration stores all torrents to /mnt/remote/realdebrid/__all__ so
    # that blackhole can see the torrents when downloading and creating the symlinks.
    depends_on:
      zurg:
        condition: service_healthy
        restart: true
    image: rclone/rclone:latest
    container_name: rclone-zurg
    hostname: ${RCLONE_ZURG_HOSTNAME:-rclone-zurg}
    networks:
      publicnet:
        ipv4_address: ${RCLONE_ZURG_IPV4_ADDRESS:-10.76.128.47}
    environment:
      <<: *common-env
    volumes:
      - ${CONFIG_PATH:-./configs}/rclone/config/rclone:/config/rclone
      - /mnt/remote/realdebrid/zurg/data:/data:rshared
      - /mnt/remote/realdebrid/zurg/cache:/mnt/cache
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    command: >
      mount zurg: /data
        --allow-non-empty
        --allow-other
        --uid=${PUID:-1002}
        --gid=${PGID:-988}
        --umask=${UMASK:-002}
        --attr-timeout 10y
        --buffer-size 64M
        --dir-cache-time 120s
        --poll-interval 60s
        --vfs-cache-max-age 2M
        --vfs-cache-max-size 30G
        --vfs-cache-min-free-space 1G
        --vfs-cache-mode full
        --vfs-cache-poll-interval 30s
        --vfs-disk-space-total-size 32G
        --vfs-fast-fingerprint
        --vfs-read-ahead 64M
        --vfs-read-chunk-size 1M
        --vfs-read-chunk-size-limit 32M
        --vfs-read-wait 40ms
        --vfs-refresh
        --transfers 16
        --checkers 16
        --multi-thread-streams 8
#    command: >
#      mount zurg:/ /data
#        --allow-other
#        --allow-non-empty
#        --uid=${PUID:-1002}
#        --gid=${PGID:-988}
#        --umask=${UMASK:-002}
#        --dir-cache-time=10s
#        --buffer-size=64M
#        --poll-interval=15s
#        --use-mmap
#        --vfs-read-ahead=128M
#        --vfs-read-chunk-size=64M
#        --vfs-read-chunk-size-limit=2048M
#        --vfs-cache-max-age=48h
#        --vfs-cache-mode=full
#        --vfs-cache-poll-interval=30s
#        --vfs-cache-max-size=10G
#        --cache-dir=/mnt/cache
#        --exclude "*.accdb" --exclude "*.cdb" --exclude "*.db" --exclude "*.dbf"
#        --exclude "*.dta" --exclude "*.fdb" --exclude "*.frm" --exclude "*.gdb"
#        --exclude "*.h2.db" --exclude "*.ibd" --exclude "*.kexi" --exclude "*.ldf"
#        --exclude "*.mdb" --exclude "*.mdf" --exclude "*.mv.db" --exclude "*.myd"
#        --exclude "*.myi" --exclude "*.ndf" --exclude "*.nsf" --exclude "*.odb"
#        --exclude "*.ora" --exclude "*.pdx" --exclude "*.rdb" --exclude "*.sdb"
#        --exclude "*.sdf" --exclude "*.sqlite" --exclude "*.sqlite3"
#        --exclude "*.sqlitedb"
#    profiles:
#      - all
#      - zurg
#      - debrid_media_server
    restart: always
  rclone-realdebrid:
    # 🔹🔹 Rclone (with Zurg)🔹🔹
    # This configuration stores all torrents to /mnt/remote/realdebrid/__all__ so
    # that blackhole can see the torrents when downloading and creating the symlinks.
    depends_on:
      zurg:
        condition: service_healthy
        restart: true
    image: rclone/rclone:latest
    container_name: rclone-realdebrid
    hostname: ${RCLONE_REALDEBRID_HOSTNAME:-rclone-realdebrid}
    networks:
      publicnet:
        ipv4_address: ${RCLONE_REALDEBRID_IPV4_ADDRESS:-10.76.128.41}
    environment:
      <<: *common-env
    volumes:
      - ${CONFIG_PATH:-./configs}/rclone/config/rclone:/config/rclone
      - /mnt/remote/realdebrid/data:/data:rshared
      - /mnt/remote/realdebrid/cache:/mnt/cache
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    command: >
      mount rd-webdav: /data
        --allow-non-empty
        --allow-other
        --uid=${PUID:-1002}
        --gid=${PGID:-988}
        --umask=${UMASK:-002}
        --attr-timeout 10y
        --buffer-size 64M
        --dir-cache-time 120s
        --poll-interval 60s
        --vfs-cache-max-age 2M
        --vfs-cache-max-size 30G
        --vfs-cache-min-free-space 1G
        --vfs-cache-mode full
        --vfs-cache-poll-interval 30s
        --vfs-disk-space-total-size 32G
        --vfs-fast-fingerprint
        --vfs-read-ahead 64M
        --vfs-read-chunk-size 1M
        --vfs-read-chunk-size-limit 32M
        --vfs-read-wait 40ms
        --vfs-refresh
        --transfers 16
        --checkers 16
        --multi-thread-streams 8
#    command: >
#      mount zurg:/ /data
#        --allow-other
#        --allow-non-empty
#        --uid=${PUID:-1002}
#        --gid=${PGID:-988}
#        --umask=${UMASK:-002}
#        --dir-cache-time=10s
#        --buffer-size=64M
#        --poll-interval=15s
#        --use-mmap
#        --vfs-read-ahead=128M
#        --vfs-read-chunk-size=64M
#        --vfs-read-chunk-size-limit=2048M
#        --vfs-cache-max-age=48h
#        --vfs-cache-mode=full
#        --vfs-cache-poll-interval=30s
#        --vfs-cache-max-size=10G
#        --cache-dir=/mnt/cache
#        --exclude "*.accdb" --exclude "*.cdb" --exclude "*.db" --exclude "*.dbf"
#        --exclude "*.dta" --exclude "*.fdb" --exclude "*.frm" --exclude "*.gdb"
#        --exclude "*.h2.db" --exclude "*.ibd" --exclude "*.kexi" --exclude "*.ldf"
#        --exclude "*.mdb" --exclude "*.mdf" --exclude "*.mv.db" --exclude "*.myd"
#        --exclude "*.myi" --exclude "*.ndf" --exclude "*.nsf" --exclude "*.odb"
#        --exclude "*.ora" --exclude "*.pdx" --exclude "*.rdb" --exclude "*.sdb"
#        --exclude "*.sdf" --exclude "*.sqlite" --exclude "*.sqlite3"
#        --exclude "*.sqlitedb"
#    profiles:
#      - all
#      - zurg
#      - debrid_media_server
    restart: always
  maintainerr:
    # 🔹🔹 Maintainerr 🔹🔹  https://docs.maintainerr.info/latest/Works/
    # Looks and smells like Overseerr, does the opposite. Maintenance tool for the Plex ecosystem
    image: ghcr.io/jorenn92/maintainerr
    container_name: maintainerr
    hostname: maintainerr
    networks:
      publicnet:
        ipv4_address: ${MAINTAINERR_IPV4_ADDRESS:-10.76.128.21}
    ports:
      - ${MAINTAINERR_API_PORT:-3002}:${MAINTAINERR_API_PORT:-3002}
      - ${MAINTAINERR_UI_PORT:-6246}:${MAINTAINERR_UI_PORT:-6246}
    volumes:
      - ${ROOT_DIR:-.}/configs/maintainerr/data:/opt/data
    <<: [*common-uidgid, *common-logging, *resource-limits]
    environment:
      <<: *common-env
      API_PORT: "${MAINTAINERR_API_PORT:-3002}"
      DEBUG: "${MAINTAINERR_DEBUG:-true}"
      NODE_ENV: "${MAINTAINERR_NODE_ENV:-production}"
      UI_HOSTNAME: "${MAINTAINERR_UI_HOSTNAME:-0.0.0.0}" # "0.0.0.0" for IPv4, "::" for IPv6
      UI_PORT: "${MAINTAINERR_UI_PORT:-6246}" # Default 6246.
      VERSION_TAG: "${MAINTAINERR_VERSION_TAG:-develop}"
      UV_USE_IO_URING: "${MAINTAINERR_UV_USE_IO_URING:-0}" # Temporary workaround for https://github.com/libuv/libuv/pull/4141
    labels:
      traefik.enable: "true"
      traefik.http.routers.maintainerr.middlewares: tinyauth@docker
      traefik.http.routers.maintainerr.rule: Host(`maintainerr.${DOMAIN}`) || Host(`maintainerr.${DUCKDNS_DOMAIN}`) || Host(`maintainerr.${TS_SUBDOMAIN}.duckdns.org`) || Host(`maintainerr.localhost`)
      traefik.http.services.maintainerr.loadbalancer.server.port: 3002
      homepage.group: Media Server Management
      homepage.name: Maintainerr
      homepage.icon: maintainerr.png
      homepage.href: https://maintainerr.${DOMAIN}
      homepage.description: A comprehensive tool for monitoring and managing your server, providing insights and tools to keep everything running smoothly.
    restart: unless-stopped

  riven:
    depends_on:
      riven-core:
        condition: service_started
    image: spoked/riven-frontend:latest
    container_name: riven
    hostname: ${RIVEN_HOSTNAME:-riven}
    networks:
      publicnet:
        ipv4_address: ${RIVEN_IPV4_ADDRESS:-10.76.0.59}
    tty: true
    volumes:
      - ${CONFIG_PATH:-./configs}/plex/riven/config:/riven/config
      - /mnt:/mnt
    environment:
      <<: *common-env
      ORIGIN: https://riven.${DOMAIN}
      BACKEND_URL: http://${RIVEN_CORE_HOSTNAME:-riven-core}:8080
      DIALECT: postgres
      DATABASE_URL: postgres://postgres:postgres@${RIVEN_DB_HOSTNAME:-riven-db}:5432/riven
    labels:
      deunhealth.restart.on.unhealthy: "true"
      traefik.enable: "true"
      traefik.http.routers.riven.middlewares: tinyauth@docker
      traefik.http.routers.riven.rule: Host(`riven.${DOMAIN}`) || Host(`riven.${DUCKDNS_DOMAIN}`) || Host(`riven.${TS_SUBDOMAIN}.duckdns.org`) || Host(`riven.localhost`)
      traefik.http.services.riven.loadbalancer.server.port: 3000
      homepage.group: Media
      homepage.name: Riven
      homepage.icon: riven.png
      homepage.href: https://riven.${DOMAIN}/
      homepage.description: Debrid service for Plex.
    healthcheck:  # docker exec riven-frontend ls -la /bin /usr/bin | grep -E 'curl|wget|nc|telnet|http|python|ncat|nmap'
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000 || exit 1"]
      interval: ${RIVEN_FRONTEND_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${RIVEN_FRONTEND_HEALTHCHECK_TIMEOUT:-10s}
      retries: ${RIVEN_FRONTEND_HEALTHCHECK_RETRIES:-3}
    restart: always
  riven-core:
    depends_on:
      riven-db:
        condition: service_healthy
    image: spoked/riven:latest
    container_name: riven-core
    hostname: ${RIVEN_CORE_HOSTNAME:-riven-core}
    networks:
      publicnet:
        ipv4_address: ${RIVEN_CORE_IPV4_ADDRESS:-10.76.0.55}
    tty: true
    volumes:
      - ${CONFIG_PATH:-./configs}/plex/riven/data:/riven/data
      - ${DATA_PATH:-./data}/media:/riven/src/data/media
      - /mnt:/mnt
    env_file:
      - ${CONFIG_PATH:-./configs}/plex/riven/config/.env
    environment:
      <<: *common-env
      RIVEN_DATABASE_HOST: ${RIVEN_DATABASE_HOST:-postgresql+psycopg2://${RIVEN_DB_USER:-postgres}:${RIVEN_DB_PASSWORD:-postgres}@${RIVEN_DB_HOSTNAME:-riven-db}/riven}
    labels:
      deunhealth.restart.on.unhealthy: "true"
      traefik.enable: "true"
#      traefik.http.routers.riven-core.middlewares: tinyauth@docker
      traefik.http.routers.riven-core.rule: Host(`riven-core.${DOMAIN}`) || Host(`riven-core.${DUCKDNS_DOMAIN}`) || Host(`riven-core.${TS_SUBDOMAIN}.duckdns.org`) || Host(`riven-core.localhost`)
      traefik.http.services.riven-core.loadbalancer.server.port: 8080
    healthcheck:  # docker exec riven ls -la /bin /usr/bin | grep -E 'curl|wget|nc|telnet|http|python|ncat|nmap'
      test: ["CMD-SHELL", "curl -s http://127.0.0.1:8080 >/dev/null || exit 1"]
      interval: ${RIVEN_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${RIVEN_HEALTHCHECK_TIMEOUT:-10s}
      retries: ${RIVEN_HEALTHCHECK_RETRIES:-10}
    restart: unless-stopped
  riven-db:
    image: postgres:17.4-alpine
    container_name: riven-db
    hostname: ${RIVEN_DB_HOSTNAME:-riven-db}
    networks:
      publicnet:
        ipv4_address: ${RIVEN_DB_IPV4_ADDRESS:-10.76.0.54}
    volumes:
      - ${CONFIG_PATH:-./configs}/plex/riven/pgdata:${RIVEN_PGDATA:-/var/lib/postgresql/data/pgdata}
    environment:
      <<: *common-env
      PGDATA: ${RIVEN_PGDATA:-/var/lib/postgresql/data/pgdata}
      POSTGRES_USER: ${RIVEN_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${RIVEN_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${RIVEN_DB_NAME:-riven}
    labels:
      deunhealth.restart.on.unhealthy: "true"
      traefik.enable: "true"
#      traefik.http.routers.riven-db.middlewares: tinyauth@docker
      traefik.http.routers.riven-db.rule: Host(`riven-db.${DOMAIN}`) || Host(`riven-db.${DUCKDNS_DOMAIN}`) || Host(`riven-db.${TS_SUBDOMAIN}.duckdns.org`) || Host(`riven-db.localhost`)
      traefik.http.services.riven-db.loadbalancer.server.port: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: ${RIVEN_DB_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${RIVEN_DB_HEALTHCHECK_TIMEOUT:-10s}
      retries: ${RIVEN_DB_HEALTHCHECK_RETRIES:-5}
    restart: always

  plex:
    # 🔹🔹 Plex Media Server 🔹🔹
    depends_on:
      - rclone-zurg
    image: plexinc/pms-docker
    container_name: plex
    hostname: plex
    networks:
      publicnet:
        ipv4_address: ${PLEX_IPV4_ADDRESS:-10.76.128.40}
    ports:
      - "${PLEX_DLNA_PORT:-1900}:1900/udp"
      - "${PLEX_PORT:-32400}:32400/tcp"
      - "${PLEX_PORT2:-32410}:32410/udp"
      - "${PLEX_PORT3:-8324}:8324/tcp"
      - "${PLEX_PORT4:-32410}:32410/udp"
      - "${PLEX_PORT5:-32412}:32412/udp"
      - "${PLEX_PORT6:-32413}:32413/udp"
      - "${PLEX_PORT7:-32414}:32414/udp"
      - "${PLEX_PORT8:-32469}:32469/tcp"
      - "${PLEX_PORT9:-8324}:8324/tcp"
    # Uncomment below line if you have an embedded intel GPU
    #devices:
    #  - /dev/dri:/dev/dri
    volumes:
      - /dev/shm:/dev/shm
      - "${CONFIG_PATH:-./configs}/plex:/config"
      - "${CONFIG_PATH:-./configs}/plex/config:/config"
      - "${CONFIG_PATH:-./configs}/plex/config/osx-config:/config/Library/Application Support/Plex Media Server"
      - "${CONFIG_PATH:-./configs}/plex/transcodes:/transcode"
      - "/mnt/remote/realdebrid/zurg:/mnt/zurg"
    environment:
      <<: *common-env
      PLEX_CLAIM: ${PLEX_CLAIM}
    labels:
      deunhealth.restart.on.unhealthy: "true"
      traefik.enable: "${PLEX_TRAEFIK_ENABLE:-true}"
      traefik.http.routers.plex.rule: Host(`plex.${DOMAIN}`) || Host(`plex.${DUCKDNS_DOMAIN}`) || Host(`plex.${TS_SUBDOMAIN}.duckdns.org`) || Host(`plex.localhost`)
      traefik.http.services.plex.loadbalancer.server.port: 32400
      homepage.group: Media Streaming
      homepage.name: Plex Media Server
      homepage.icon: plex.png
      homepage.href: https://plex.${DOMAIN}/
      homepage.description: Stream your movies, TV shows, music, and photos to any device, providing a centralized media hub for all your content.
      homepage.weight: 4
      homepage.widget.type: plex
      homepage.widget.url: https://plex.${DOMAIN}
      homepage.widget.key: ${PLEX_TOKEN}  # see instructions here: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:32400/identity
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 1m
#    profiles:
#      - all
#      - plex
#      - debrid_media_server
    restart: unless-stopped
  tautulli:
    image: ghcr.io/tautulli/tautulli:latest
    container_name: tautulli
    hostname: ${TAUTULLI_HOSTNAME:-tautulli}
    networks:
      publicnet:
        ipv4_address: ${TAUTULLI_IPV4_ADDRESS:-10.76.0.53}
    volumes:
      - ${CONFIG_PATH:-./configs}/tautulli:/config
    environment:
      <<: *common-env
    labels:
      deunhealth.restart.on.unhealthy: "true"
      traefik.enable: "true"
      traefik.http.routers.tautulli.middlewares: tinyauth@docker
      traefik.http.routers.tautulli.rule: Host(`tautulli.${DOMAIN}`) || Host(`tautulli.${DUCKDNS_DOMAIN}`) || Host(`tautulli.${TS_SUBDOMAIN}.duckdns.org`) || Host(`tautulli.localhost`)
      traefik.http.services.tautulli.loadbalancer.server.port: 8181
      homepage.group: Media Maintenance
      homepage.name: Tautulli
      homepage.icon: tautulli.png
      homepage.href: https://tautulli.${DOMAIN}/
      homepage.description: Tautulli is a web interface for Plex Media Server.
      homepage.weight: 6
      homepage.widget.type: tautulli
      homepage.widget.url: https://tautulli.${DOMAIN}
      homepage.widget.key: ${TAUTULLI_API_KEY}
#    profiles:
#      - all
#      - tautulli
#      - debrid_media_server
    restart: always


networks:
  publicnet:  # https://docs.docker.com/engine/network/drivers/bridge/#differences-between-user-defined-bridges-and-the-default-bridge
    external: true  # docker network create --driver=bridge --attachable publicnet --subnet=${PUBLICNET_SUBNET:-10.76.0.0/16} --gateway=${PUBLICNET_GATEWAY:-10.76.0.1} --ip-range=${PUBLICNET_IP_RANGE:-10.76.0.0/16}
    attachable: true
    name: publicnet
    ipam:
      config:
        - subnet: ${PUBLICNET_SUBNET:-10.76.0.0/16}
          gateway: ${PUBLICNET_GATEWAY:-10.76.0.1}
          ip_range: ${PUBLICNET_IP_RANGE:-10.76.0.0/16}
