x-common-env: &common-env
  PGID: ${PGID:-988} # 'docker' Group ID
  PUID: ${PUID:-1001} # A non-root user ID
  TZ: ${TZ:-America/Chicago} # Your Timezone

x-resource-limits: &resource-limits
  cpu_shares: 1024 # CPU share weight (relative, 2-262144). Higher = more CPU *if competing*.
  #  mem_limit: 512m        # Max RAM usage (e.g., 64m, 1g). Exceeding = container kill.
  #  mem_reservation: 325m  # Soft RAM limit (e.g., 32m, 512m).  Best effort, not guaranteed.
  #  mem_swappiness: 30      # Swap usage (0-100). 0 = off. Higher = more swap, may slow down container.
  #memswap_limit: 1024m    # Max RAM + Swap.  Usually same as mem_limit.
  labels:
    autoheal: "true"

x-swarm-resource-limits: &swarm-resource-limits
  resources:
    limits:
      cpus: "0.10"
      memory: 1024M
#    reservations:
#     cpus: '0.05'
#    memory:  256M

x-common-deploy: &common-deploy
  placement:
    preferences:
      - spread: node.labels.worker_priority
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
  labels:
    autoheal: "true"
    swarm.autoscaler: "true"
#  resources:
#    limits:
#      cpus: '0.10'
#      memory: 128M
#    reservations:
#      cpus: '0.10'
#      memory: 64M

x-changedetection-labels: &changedetection-labels
  traefik.enable: "true"
  traefik.http.services.changedetection.loadbalancer.server.port: 5000

x-notifiarr-labels: &notifiarr-labels
  traefik.enable: "true"
  traefik.http.services.notifiarr.loadbalancer.server.port: 5454

x-ntfy-labels: &ntfy-labels
  traefik.enable: "true"
  traefik.http.services.ntfy.loadbalancer.server.port: 80

services:
  changedetection:
    # 🔹🔹 Changedetection 🔹🔹  https://github.com/dgtlmoon/changedetection.io
    # Detect website content changes and perform
    # meaningful actions - trigger notifications via
    #  Discord, Email, Slack, Telegram, API calls and many more.
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - traefik_public
    volumes:
      - ${ROOT_DIR:-.}/configs/changedetection/datastore:/datastore
    environment:
      <<: *common-env
    labels:
      <<: *changedetection-labels
      homepage.group: Utilities
      homepage.name: Change Detection
      homepage.icon: changedetection.png
      homepage.href: https://changedetection.${DOMAIN}/
      homepage.description: Monitor websites for changes and receive notifications, ensuring you're always up-to-date with the latest information.
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        <<: *changedetection-labels
    restart: unless-stopped

  notifiarr:
    # 🔹🔹 Notifiarr 🔹🔹
    # Client for Notifiarr.com
    image: golift/notifiarr
    container_name: notifiarr
    security_opt:
      - no-new-privileges:true
    privileged: true
    ports:
      - ${NOTIFIARR_PORT:-5454}:5454
    volumes:
      - ${ROOT_DIR:-.}/configs/notifiarr/notifiarr.conf:/config/notifiarr.conf
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    environment:
      DN_AUTO_UPDATE: ${NOTIFIARR_AUTO_UPDATE:-"off"}
    labels:
      <<: *notifiarr-labels
      homepage.group: Notifications
      homepage.name: Notifiarr
      homepage.icon: notifiarr.png
      homepage.href: https://notifiarr.${DOMAIN}
      homepage.description: Centralized notification system for various services, keeping you informed in real-time.
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        <<: *notifiarr-labels
    restart: unless-stopped

  ntfy:
    # 🔹🔹 Ntfy 🔹🔹
    image: binwiederhier/ntfy
    container_name: ntfy
    hostname: ntfy
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - traefik_public
    ports:
      - ${NTFY_PORT:-8586}:80
    command:
      - serve
    volumes:
      - ${ROOT_DIR:-.}/configs/ntfy/cache:/var/cache/ntfy
      - ${ROOT_DIR:-.}/configs/ntfy:/etc/ntfy
      - ${ROOT_DIR:-.}/configs/ntfy/cache.db:/var/cache/ntfy/cache.db
    environment:
      <<: *common-env
    labels:
      <<: *ntfy-labels
      homepage.group: Notifications
      homepage.name: Ntfy
      homepage.icon: ntfy.png
      homepage.href: https://ntfy.${DOMAIN}
    healthcheck: # optional: remember to adapt the host:port to your environment
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://ntfy:${NTFY_PORT:-8586}/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        <<: *ntfy-labels
    restart: unless-stopped
