apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"CronJob","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"cronjob","app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"notifiarr-sync"},"name":"notifiarr-sync","namespace":"default"},"spec":{"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"args":["--sync"],"command":["/app/notifiarr"],"image":"ghcr.io/elfhosted/notifiarr:latest","name":"notifiarr-sync","resources":{"limits":{"cpu":"200m","memory":"512Mi"},"requests":{"cpu":"50m","memory":"128Mi"}}}],"restartPolicy":"OnFailure"}}}},"schedule":"0 */6 * * *"}}
  labels:
    app.kubernetes.io/component: cronjob
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: notifiarr-sync
  name: notifiarr-sync
  namespace: default
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
    spec:
      template:
        metadata:
        spec:
          containers:
          - args:
            - --sync
            command:
            - /app/notifiarr
            image: ghcr.io/elfhosted/notifiarr:latest
            imagePullPolicy: Always
            name: notifiarr-sync
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 50m
                memory: 128Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 */6 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
  lastScheduleTime: "2025-06-14T18:00:00Z"
