kind: Service
apiVersion: v1
metadata:
  name: brunner56-riven
  namespace: my-media-stack
  labels:
    app.kubernetes.io/instance: brunner56
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: riven
    app.kubernetes.io/service: brunner56-riven
    helm.sh/chart: riven-0.2.1
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
spec:
  ports:
  - name: http
    protocol: TCP
    port: 3001
    targetPort: http
  selector:
    app.kubernetes.io/instance: brunner56
    app.kubernetes.io/name: riven
  clusterIP: 10.43.47.150
  clusterIPs:
  - 10.43.47.150
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
