kind: Pod
apiVersion: v1
metadata:
  name: brunner56-traefikforwardauth-7db49dfc96-9vwjd
  generateName: brunner56-traefikforwardauth-7db49dfc96-
  namespace: my-media-stack
  uid: 3462366c-2772-4a9e-8536-5caf507cede2
  resourceVersion: '2389349962'
  creationTimestamp: '2025-05-29T16:29:05Z'
  labels:
    app.kubernetes.io/instance: brunner56
    app.kubernetes.io/name: traefikforwardauth
    pod-template-hash: 7db49dfc96
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: brunner56-traefikforwardauth-7db49dfc96
      uid: 621d2ed5-cdd3-4adb-ab23-7c42fc697c98
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: k3s
      operation: Update
      apiVersion: v1
      time: '2025-05-29T16:29:05Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/name: {}
            f:pod-template-hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"621d2ed5-cdd3-4adb-ab23-7c42fc697c98"}: {}
        f:spec:
          f:affinity:
            .: {}
            f:podAffinity:
              .: {}
              f:requiredDuringSchedulingIgnoredDuringExecution: {}
          f:automountServiceAccountToken: {}
          f:containers:
            k:{"name":"brunner56-traefikforwardauth"}:
              .: {}
              f:env:
                .: {}
                k:{"name":"SECRET"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:secretKeyRef: {}
                k:{"name":"TZ"}:
                  .: {}
                  f:name: {}
                  f:value: {}
              f:envFrom: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:livenessProbe:
                .: {}
                f:failureThreshold: {}
                f:periodSeconds: {}
                f:successThreshold: {}
                f:tcpSocket:
                  .: {}
                  f:port: {}
                f:timeoutSeconds: {}
              f:name: {}
              f:ports:
                .: {}
                k:{"containerPort":4181,"protocol":"TCP"}:
                  .: {}
                  f:containerPort: {}
                  f:name: {}
                  f:protocol: {}
              f:readinessProbe:
                .: {}
                f:failureThreshold: {}
                f:periodSeconds: {}
                f:successThreshold: {}
                f:tcpSocket:
                  .: {}
                  f:port: {}
                f:timeoutSeconds: {}
              f:resources:
                .: {}
                f:limits:
                  .: {}
                  f:cpu: {}
                  f:memory: {}
                f:requests:
                  .: {}
                  f:cpu: {}
                  f:memory: {}
              f:securityContext:
                .: {}
                f:readOnlyRootFilesystem: {}
                f:seccompProfile:
                  .: {}
                  f:type: {}
              f:startupProbe:
                .: {}
                f:failureThreshold: {}
                f:periodSeconds: {}
                f:successThreshold: {}
                f:tcpSocket:
                  .: {}
                  f:port: {}
                f:timeoutSeconds: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:priorityClassName: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext:
            .: {}
            f:seccompProfile:
              .: {}
              f:type: {}
          f:serviceAccount: {}
          f:serviceAccountName: {}
          f:terminationGracePeriodSeconds: {}
    - manager: k3s
      operation: Update
      apiVersion: v1
      time: '2025-05-29T16:29:10Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodReadyToStartContainers"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:hostIPs: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.2.112.147"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      subresource: status
spec:
  containers:
    - name: brunner56-traefikforwardauth
      image: >-
        ghcr.io/elfhosted/traefik-forward-auth:3.1.0@sha256:19cd990fae90c544100676bc049f944becc8c454639e57d20f6f48e27de90776
      ports:
        - name: http
          containerPort: 4181
          protocol: TCP
      envFrom:
        - configMapRef:
            name: traefik-forward-auth-config
      env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: brunner56-traefikforwardauth
              key: secret
        - name: TZ
          value: UTC
      resources:
        limits:
          cpu: '1'
          memory: 32Mi
        requests:
          cpu: '0'
          memory: 6Mi
      livenessProbe:
        tcpSocket:
          port: 4181
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        tcpSocket:
          port: 4181
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      startupProbe:
        tcpSocket:
          port: 4181
        timeoutSeconds: 1
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 30
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
      securityContext:
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  automountServiceAccountToken: false
  nodeName: hansel18
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.elfhosted.com/role
                operator: In
                values:
                  - nodefinder
          topologyKey: kubernetes.io/hostname
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priorityClassName: tenant-normal
  priority: 4000
  enableServiceLinks: false
  preemptionPolicy: PreemptLowerPriority
status:
  phase: Running
  conditions:
    - type: PodReadyToStartContainers
      status: 'True'
      lastProbeTime: '2025-05-29T17:12:59Z'
      lastTransitionTime: '2025-05-29T16:29:07Z'
    - type: Initialized
      status: 'True'
      lastProbeTime: '2025-05-29T17:12:59Z'
      lastTransitionTime: '2025-05-29T16:29:05Z'
    - type: Ready
      status: 'True'
      lastProbeTime: '2025-05-29T17:12:59Z'
      lastTransitionTime: '2025-05-29T16:29:10Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: '2025-05-29T17:12:59Z'
      lastTransitionTime: '2025-05-29T16:29:10Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: '2025-05-29T17:12:59Z'
      lastTransitionTime: '2025-05-29T16:29:05Z'
  hostIP: 10.0.42.38
  hostIPs:
    - ip: 10.0.42.38
  podIP: 10.2.112.147
  podIPs:
    - ip: 10.2.112.147
  startTime: '2025-05-29T16:29:05Z'
  containerStatuses:
    - name: brunner56-traefikforwardauth
      state:
        running:
          startedAt: '2025-05-29T16:29:06Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: sha256:d6d7a84e623b7879d91322128899ed1a2ef5a8180b97fd745315c826bc76f24c
      imageID: >-
        ghcr.io/elfhosted/traefik-forward-auth@sha256:19cd990fae90c544100676bc049f944becc8c454639e57d20f6f48e27de90776
      containerID: >-
        containerd://0f6d1fe819fbbbbd0d544ffa9c4627115e453509e728de92967399217c46ee81
      started: true
  qosClass: Burstable
