kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: realdebrid-zurg
  namespace: my-media-stack
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
    velero.io/exclude-from-backup: 'true'
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
spec:
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels:
      name: rclone-brunner56-realdebrid-zurg
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
