apiVersion: storage.k8s.io/v1
kind: CSINode
metadata:
  annotations:
    storage.alpha.kubernetes.io/migrated-plugins: kubernetes.io/aws-ebs,kubernetes.io/azure-disk,kubernetes.io/azure-file,kubernetes.io/cinder,kubernetes.io/gce-pd,kubernetes.io/portworx-volume,kubernetes.io/vsphere-volume
  name: cloudserver.bolabaden.lebla512ssd.org
  ownerReferences:
  - apiVersion: v1
    kind: Node
    name: cloudserver.bolabaden.lebla512ssd.org
spec:
  drivers: null
