apiVersion: v1
kind: Service
metadata:
    name: comet
    namespace: my-media-stack
spec:
    selector: {}
    ports:
        - name: comet-2020
          port: 2020
          targetPort: comet-2020
