apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobechat
  namespace: my-media-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lobechat
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lobechat
    spec:
      containers:
        - name: lobechat
          image: lobehub/lobe-chat:latest
          ports:
            - name: lobechat-3210
              containerPort: 3210
          env:
            - name: ACCESS_CODE
              value: "brunner56"
            - name: PGID
              value: "988"
            - name: PUID
              value: "1002"
            - name: TZ
              value: "America/Chicago"
            - name: UMASK
              value: "002"
          volumeMounts:
            - name: host-config
              mountPath: /configs/lobechat/host_config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: host-config
          hostPath:
            path: /home/ubuntu/my-media-stack/configs/lobechat/host_config
            type: DirectoryOrCreate
