{{- if .Values.podGatewayConfig.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pod-gateway-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vpn-gateway.labels" . | nindent 4 }}
data:
  settings.sh: |
    #!/bin/sh
    export VXLAN_ID="{{ .Values.podGatewayConfig.settings.VXLAN_ID }}"
    export VXLAN_IP_NETWORK="{{ .Values.podGatewayConfig.settings.VXLAN_IP_NETWORK }}"
    export VXLAN_PORT="{{ .Values.podGatewayConfig.settings.VXLAN_PORT }}"
    export VPN_INTERFACE_MTU="{{ .Values.podGatewayConfig.settings.VPN_INTERFACE_MTU }}"
    export ACTIVE_VPN_GATEWAY="{{ .Values.podGatewayConfig.settings.ACTIVE_VPN_GATEWAY }}"
    export VXLAN_GATEWAY_FIRST_DYNAMIC_IP="{{ .Values.podGatewayConfig.settings.VXLAN_GATEWAY_FIRST_DYNAMIC_IP }}"
    GATEWAY_NAME="${ACTIVE_VPN_GATEWAY:-gluetun-premiumize-us}"
{{- end }}
