apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/out
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: comet
  name: comet
spec:
  ports:
    - name: "2020"
      port: 2020
      targetPort: 2020
  selector:
    io.kompose.service: comet 