apiVersion: v1
kind: Service
metadata:
  annotations:
    deunhealth.restart.on.unhealthy: "true"
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/out
    kompose.version: 1.36.0 (ae2a39403)
    traefik.enable: "true"
    traefik.http.routers.flaresolverr.middlewares: nginx-auth@file
    traefik.http.routers.flaresolverr.rule: Host(`flaresolverr.bolabaden.org`) || Host( `flaresolverr.bolabaden.duckdns.org`) || Host(`flaresolverr.micklethefickle.duckdns.org`) || Host(`flaresolverr.micklethefickle.bolabaden.org`) || Host(`flaresolverr.micklethefickle.bolabaden.duckdns.org`)
    traefik.http.services.flaresolverr.loadbalancer.server.port: "8191"
  labels:
    io.kompose.service: flaresolverr
  name: flaresolverr
spec:
  ports:
    - name: "8191"
      port: 8191
      targetPort: 8191
  selector:
    io.kompose.service: flaresolverr
