apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f compose/docker-compose.networks-inline.yml convert -o k8s/out
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: gluetun-premiumize-it
  name: gluetun-premiumize-it
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: gluetun-premiumize-it
