apiVersion: v1
kind: Service
metadata:
  annotations:
    deunhealth.restart.on.unhealthy: "true"
    homepage.description: A chatbot for your applications.
    homepage.group: AI
    homepage.href: https://lobechat.bolabaden.org/
    homepage.icon: lobechat.png
    homepage.name: Lobe Chat
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/out
    kompose.version: 1.36.0 (ae2a39403)
    traefik.enable: "true"
    traefik.http.routers.lobechat.middlewares: nginx-auth@file
    traefik.http.routers.lobechat.rule: Host(`lobechat.bolabaden.org`) || Host(`lobechat.bolabaden.duckdns.org`) || Host(`lobechat.micklethefickle.duckdns.org`) || Host(`lobechat.micklethefickle.bolabaden.org`) || Host(`lobechat.micklethefickle.bolabaden.duckdns.org`)
    traefik.http.services.lobechat.loadbalancer.server.port: "3210"
  labels:
    io.kompose.service: lobechat
  name: lobechat
spec:
  ports:
    - name: "3210"
      port: 3210
      targetPort: 3210
  selector:
    io.kompose.service: lobechat
