apiVersion: v1
kind: Service
metadata:
  annotations:
    deunhealth.restart.on.unhealthy: "true"
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/out
    kompose.version: 1.36.0 (ae2a39403)
    traefik.enable: "true"
    traefik.http.routers.mongodb.middlewares: nginx-auth@file
    traefik.http.routers.mongodb.rule: Host(`mongodb.bolabaden.org`) || Host(`mongodb.bolabaden.duckdns.org`) || Host(`mongodb.micklethefickle.duckdns.org`)
    traefik.http.services.mongodb.loadbalancer.server.port: "27017"
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongodb
