apiVersion: v1
kind: Service
metadata:
  annotations:
    deunhealth.restart.on.unhealthy: "true"
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/out
    kompose.version: 1.36.0 (ae2a39403)
    traefik.enable: "true"
    traefik.http.services.nginx-auth.loadbalancer.server.port: "80"
  labels:
    io.kompose.service: nginx-auth
  name: nginx-auth
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: nginx-auth
