apiVersion: v1
kind: Service
metadata:
  annotations:
    deunhealth.restart.on.unhealthy: "true"
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/out
    kompose.version: 1.36.0 (ae2a39403)
    traefik.enable: "true"
    traefik.http.routers.redis.middlewares: nginx-auth@file
    traefik.http.routers.redis.rule: Host(`redis.bolabaden.org`) || Host(`redis.bolabaden.duckdns.org`) || Host(`redis.micklethefickle.duckdns.org`)
    traefik.http.services.redis.loadbalancer.server.port: "6379"
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis
