apiVersion: v1
kind: Service
metadata:
  annotations:
    deunhealth.restart.on.unhealthy: "true"
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/out
    kompose.version: 1.36.0 (ae2a39403)
    traefik.enable: "true"
    traefik.http.routers.stremthru-redis.middlewares: nginx-auth@file
    traefik.http.routers.stremthru-redis.rule: Host(`stremthru-redis.bolabaden.org`) || Host(`stremthru-redis.bolabaden.duckdns.org`) || Host(`stremthru-redis.micklethefickle.duckdns.org`) || Host(`stremthru-redis.micklethefickle.bolabaden.org`) || Host(`stremthru-redis.micklethefickle.bolabaden.duckdns.org`)
    traefik.http.services.stremthru-redis.loadbalancer.server.port: "6379"
  labels:
    io.kompose.service: stremthru-redis
  name: stremthru-redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: stremthru-redis
