apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/out
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: tailscale-warp
  name: tailscale-warp
spec:
  ports:
    - name: "41641"
      port: 41641
      targetPort: 41641
    - name: "8885"
      port: 8885
      targetPort: 8885
    - name: "1055"
      port: 1055
      targetPort: 1055
  selector:
    io.kompose.service: tailscale-warp 