apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: tailscale-warp-tmp
  name: tailscale-warp-tmp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi 