apiVersion: v1
kind: Service
metadata:
  annotations:
    deunhealth.restart.on.unhealthy: "true"
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/out
    kompose.version: 1.36.0 (ae2a39403)
    traefik.enable: "true"
    traefik.http.routers.traefik.middlewares: nginx-auth@file
    traefik.http.routers.traefik.rule: Host(`traefik.bolabaden.org`) || Host(`traefik.bolabaden.duckdns.org`) || Host(`traefik.micklethefickle.duckdns.org`) || Host(`traefik.micklethefickle.bolabaden.org`) || Host(`traefik.micklethefickle.bolabaden.duckdns.org`)
    traefik.http.services.traefik.loadbalancer.server.port: "8080"
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: traefik
