apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/out
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: warp-fetch-proxy
  name: warp-fetch-proxy
spec:
  ports:
    - name: "3128"
      port: 3128
      targetPort: 3128
  selector:
    io.kompose.service: warp-fetch-proxy 