apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f compose/docker-compose.networks-inline.yml convert -o k8s/out
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: warp
  name: warp
spec:
  ports:
    - name: "1080"
      port: 1080
      targetPort: 1080
    - name: "443"
      port: 443
      protocol: UDP
      targetPort: 443
    - name: 1080-tcp
      port: 1080
      targetPort: 1080
  selector:
    io.kompose.service: warp
