apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/out
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: watchtower
  name: watchtower
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: watchtower
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o k8s/out
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: watchtower
    spec:
      containers:
        - env:
            - name: TZ
              value: America/Chicago
            - name: PUID
              value: "1001"
            - name: PGID
              value: "988"
            - name: UMASK
              value: "002"
            - name: WATCHTOWER_CLEANUP
              value: "true"
            - name: WATCHTOWER_SCHEDULE
              value: 0 0 6 * * *
            - name: WATCHTOWER_NOTIFICATION_URL
              value: ""
            - name: WATCHTOWER_NOTIFICATION_REPORT
              value: "true"
            - name: WATCHTOWER_NOTIFICATION_TEMPLATE
              value: |
                {{- if .Report -}}
                  {{- with .Report -}}
                    {{- if ( or .Updated .Failed ) -}}
                {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
                      {{- range .Updated}}
                - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
                      {{- end -}}
                      {{- range .Skipped}}
                - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
                      {{- end -}}
                      {{- range .Failed}}
                - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
                      {{- end -}}
                    {{- end -}}
                  {{- end -}}
                {{- else -}}
                  {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
                {{- end -}}
          image: containrrr/watchtower:latest
          name: watchtower
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
      restartPolicy: Always
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
