apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.elfhosted.com/name":"sonarr","app.kubernetes.io/instance":"myprecious"},"name":"sonarr","namespace":"default"}}
  labels:
    app.elfhosted.com/name: sonarr
    app.kubernetes.io/instance: myprecious
  name: sonarr
  namespace: default
