apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    local.path.provisioner/selected-node: beatapostapita
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-8584dcfa-f620-4be7-af5b-8a9a4d9f8934
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: traefik
    namespace: kube-system
  local:
    path: /var/lib/rancher/k3s/storage/pvc-8584dcfa-f620-4be7-af5b-8a9a4d9f8934_kube-system_traefik
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - beatapostapita
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
  lastPhaseTransitionTime: "2025-06-14T17:41:08Z"
  phase: Bound
