kubernetesClusterDomain: cluster.local
wizarrStepsJellyfin:
  01DownloadMd: "---\ntitle: \"Join & download Jellyfin\"\nrequire: true\n---\nYou're
    in! \U0001F389\nGreat news! You've been granted access to brunner56's **ElfHosted
    Jellyfin Server**! \U0001F973"
  02AboutMd: "---\ntitle: \"What is Jellyfin?\"\n---\n## ℹ️ What's Jellyfin?\nJellyfin
    lets people share their film and TV libraries with friends. \"\n      \"You're
    here because brunner56’s invited you to theirs! \U0001F4FA\n## \U0001F37F How
    do I watch stuff?\nSearch your phone, tablet, computer or smart-TV's app store
    for \"Jellyfin\", or [download on this device](https://jellyfin.org/downloads){target=_blank
    .btn}.\nSign in, search, push play. That’s it!"
  03RequestsMd: "---\ntitle:  \"Automatic requests\"\nrequires: [overseerr_url]\n---\n#\"Request
    mooar content \U0001F64B‍♀️\nCan't find what you want to watch? Make a request
    — robots will grab the film or episode automatically and add it to the library.\n[Make
    a request]({{ overseerr_url }}){:target=_blank .btn}"
  04DiscordMd: |-
    ---
    title:  "Discord community"
    requires: [discord_id]
    ---
    <iframe src="https://discord.com/widget?id={{discord_id }}&theme=dark"
            width="350" height="500"
            allowtransparency="true" frameborder="0"
            sandbox="allow-popups allow-same-origin allow-scripts"></iframe>
  05TipsMd: "---\ntitle: \"Tips for the best experience\"\n---\n## \U0001F39E Get
    the best quality\nPlex sometimes defaults to low quality or shows its own adverts
    first. \"\n      \"Here’s how to fix that:\n1. **Set streaming quality to original**
    – Settings → Playback\n2. **Enable hardware decoding** if your device supports
    it for smoother 4K.\n3. **Prefer Ethernet over Wi-Fi** on smart-TVs.\n*Happy viewing!*
    \U0001F37F"
  06ElfhostedMd: "---\ntitle: \"Get ElfHosted!\"\n---\n## \U0001F39E Want your **own**
    media library?\nReady to take it to the next level?\nGet your **own** Media Server
    with a [ElfHosted bundle](https://store.elfhosted.com/product-category/streaming-bundles/){target=_blank
    .btn}, $1 7-day trials available!\nRock on! \U0001F918"
