apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart-volsync-rs-backup-cache-pvc.fullname" . }}-volsync-rs-backup-cache
  labels:
    app.kubernetes.io/created-by: volsync
  {{- include "chart-volsync-rs-backup-cache-pvc.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.volsyncRsBackupCache.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.volsyncRsBackupCache.storageClass | quote }}
