apiVersion: v1
kind: Pod
metadata:
  generateName: health-check-services-29165695-
  labels:
    batch.kubernetes.io/controller-uid: e033f615-2cc5-4efa-aef7-85b4fe79cf2f
    batch.kubernetes.io/job-name: health-check-services-29165695
    controller-uid: e033f615-2cc5-4efa-aef7-85b4fe79cf2f
    job-name: health-check-services-29165695
  name: health-check-services-29165695-rcnbh
  namespace: default
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: health-check-services-29165695
spec:
  containers:
  - args:
    - -c
    - "\n      services=\"plex:32400 radarr:7878 sonarr:8989 prowlarr:9696\"\n      for
      service in $services; do\n        host=$(echo $service | cut -d: -f1)\n        port=$(echo
      $service | cut -d: -f2)\n        if curl -f -s http://$host:$port/ping > /dev/null;
      then\n          echo \"$service is healthy\"\n        else\n          echo \"$service
      is unhealthy\"\n        fi\n      done\n    "
    command:
    - /bin/sh
    image: curlimages/curl:latest
    imagePullPolicy: Always
    name: health-check-services
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: regcred
  nodeName: beatapostapita
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:55:16Z"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:55:02Z"
    reason: PodCompleted
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:55:15Z"
    reason: PodCompleted
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:55:15Z"
    reason: PodCompleted
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:55:00Z"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://b61a4935311e8a0419fea56e82ba903cf09834168318943568dfaf4cb9edf38f
    image: docker.io/curlimages/curl:latest
    imageID: docker.io/curlimages/curl@sha256:d43bdb28bae0be0998f3be83199bfb2b81e0a30b034b6d7586ce7e05de34c3fd
    lastState: {}
    name: health-check-services
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://b61a4935311e8a0419fea56e82ba903cf09834168318943568dfaf4cb9edf38f
        exitCode: 0
        finishedAt: "2025-06-14T22:55:14Z"
        reason: Completed
        startedAt: "2025-06-14T22:55:03Z"
  hostIP: 10.0.0.81
  hostIPs:
  - ip: 10.0.0.81
  phase: Succeeded
  podIP: 10.42.0.96
  podIPs:
  - ip: 10.42.0.96
  qosClass: Burstable
  startTime: "2025-06-14T22:55:02Z"
