apiVersion: v1
kind: Pod
metadata:
  generateName: overseerr-5866b7bfcc-
  labels:
    app.elfhosted.com/name: overseerr
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: overseerr
    pod-template-hash: 5866b7bfcc
  name: overseerr-5866b7bfcc-64ckh
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: overseerr-5866b7bfcc
spec:
  containers:
  - image: sctx/overseerr:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 5055
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 10
    name: overseerr
    ports:
    - containerPort: 5055
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 5055
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /app/config
      name: config
      subPath: overseerr
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: beatapostapita
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: config
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:44:22Z"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:44:20Z"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:04:19Z"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:04:19Z"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:44:20Z"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://22414918756caa053175ec688215fca4ae9aaaaffbf11552829a98d24ee1a589
    image: docker.io/sctx/overseerr:latest
    imageID: docker.io/sctx/overseerr@sha256:4f38f58d68555004d3f487a4c5cbe2823e6a0942d946a25a2d9391d8492240a4
    lastState: {}
    name: overseerr
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-06-14T17:44:22Z"
    volumeMounts:
    - mountPath: /app/config
      name: config
  hostIP: 10.0.0.81
  hostIPs:
  - ip: 10.0.0.81
  phase: Running
  podIP: 10.42.0.41
  podIPs:
  - ip: 10.42.0.41
  qosClass: Burstable
  startTime: "2025-06-14T17:44:20Z"
