apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2025-06-12T01:11:04Z"
  generateName: radarr-4k-75565cfcc7-
  labels:
    app.elfhosted.com/name: radarr-4k
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: radarr-4k
    pod-template-hash: 75565cfcc7
  name: radarr-4k-75565cfcc7-zmtsd
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: radarr-4k-75565cfcc7
spec:
  containers:
  - image: linuxserver/radarr:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 7878
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 10
    name: radarr-4k
    ports:
    - containerPort: 7878
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 7878
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: config
      subPath: radarr4k
    - mountPath: /storage/symlinks
      name: symlinks
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: beatapostapita
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: config
  - name: symlinks
    persistentVolumeClaim:
      claimName: symlinks
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:22:02Z"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T15:09:43Z"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:04:24Z"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:04:24Z"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T15:09:43Z"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://a70e0759f2e0dab4f8b0396b1b98e12358406f17972bbdb918b9c87c8e9618ae
    image: docker.io/linuxserver/radarr:latest
    imageID: docker.io/linuxserver/radarr@sha256:36e43720c130ec2d3ed80726d2134af3c6644729f4750abc830fdda7fa71d1e1
    lastState: {}
    name: radarr-4k
    ready: true
    restartCount: 2
    started: true
    state:
      running:
        startedAt: "2025-06-14T17:22:01Z"
    volumeMounts:
    - mountPath: /config
      name: config
    - mountPath: /storage/symlinks
      name: symlinks
  hostIP: 10.0.0.81
  hostIPs:
  - ip: 10.0.0.81
  phase: Running
  podIP: 10.42.0.2
  podIPs:
  - ip: 10.42.0.2
  qosClass: Burstable
  startTime: "2025-06-14T15:09:43Z"
