apiVersion: v1
kind: Pod
metadata:
  generateName: zurg-7cf85665db-
  labels:
    app.elfhosted.com/name: zurg
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: zurg
    pod-template-hash: 7cf85665db
  name: zurg-7cf85665db-d86gz
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: zurg-7cf85665db
spec:
  containers:
  - image: debridmediamanager/zurg-testing:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 9999
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 10
    name: zurg
    ports:
    - containerPort: 9999
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 9999
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /app/config.yml
      name: config
      subPath: config.yml
    - mountPath: /data
      name: realdebrid-zurg
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: beatapostapita
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: zurg-config
    name: config
  - name: realdebrid-zurg
    persistentVolumeClaim:
      claimName: realdebrid-zurg
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:44:23Z"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:44:21Z"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:44:21Z"
    message: 'containers with unready status: [zurg]'
    reason: ContainersNotReady
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:44:21Z"
    message: 'containers with unready status: [zurg]'
    reason: ContainersNotReady
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:44:21Z"
    type: PodScheduled
  containerStatuses:
  - image: debridmediamanager/zurg-testing:latest
    imageID: ""
    lastState: {}
    name: zurg
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: 'Back-off pulling image "debridmediamanager/zurg-testing:latest":
          ErrImagePull: rpc error: code = NotFound desc = failed to pull and unpack
          image "docker.io/debridmediamanager/zurg-testing:latest": failed to resolve
          reference "docker.io/debridmediamanager/zurg-testing:latest": docker.io/debridmediamanager/zurg-testing:latest:
          not found'
        reason: ImagePullBackOff
    volumeMounts:
    - mountPath: /app/config.yml
      name: config
    - mountPath: /data
      name: realdebrid-zurg
  hostIP: 10.0.0.81
  hostIPs:
  - ip: 10.0.0.81
  phase: Pending
  podIP: 10.42.0.43
  podIPs:
  - ip: 10.42.0.43
  qosClass: Burstable
  startTime: "2025-06-14T17:44:21Z"
