[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs

[AutoRun]
enabled=false
program=

[BitTorrent]
ExcludedFileNamesEnabled=true
MergeTrackersEnabled=true
Session\AddExtensionToIncompleteFiles=false
Session\AddTorrentStopped=false
Session\AddTorrentToTopOfQueue=true
Session\AddTrackersFromURLEnabled=true
Session\AdditionalTrackersURL=https://raw.githubusercontent.com/ngosang/trackerslist/refs/heads/master/trackers_best.txt
Session\AnonymousModeEnabled=true
Session\BlockPeersOnPrivilegedPorts=true
Session\ChokingAlgorithm=FixedSlots
Session\DefaultSavePath=/downloads/
Session\DisableAutoTMMByDefault=false
Session\DisableAutoTMMTriggers\CategorySavePathChanged=false
Session\DisableAutoTMMTriggers\DefaultSavePathChanged=false
Session\DiskQueueSize=10485760
Session\Encryption=1
Session\ExcludedFileNames=*_8k_*, *blacked*, *_6k_*, *chechik*, *ps4*, *.funscript, *.nfo, *smartphone*, *1k*, RARBG.com.txt, RARBG.txt, RARBG_DO_NOT_MIRROR.exe
Session\FilePoolSize=1
Session\FinishedTorrentExportDirectory=/blackhole
Session\GlobalDLSpeedLimit=0
Session\GlobalMaxInactiveSeedingMinutes=1440
Session\GlobalMaxRatio=1
Session\GlobalMaxSeedingMinutes=1440
Session\I2P\Address=172.28.4.2
Session\I2P\Enabled=true
Session\I2P\InboundLength=3
Session\I2P\MixedMode=true
Session\IgnoreSlowTorrentsForQueueing=true
Session\MaxActiveDownloads=5
Session\MaxActiveTorrents=5000
Session\MaxConnections=500
Session\MaxConnectionsPerTorrent=-1
Session\MaxUploads=8
Session\MaxUploadsPerTorrent=4
Session\PerformanceWarning=true
Session\PieceExtentAffinity=false
Session\Port=6881
Session\Preallocation=true
Session\ProxyPeerConnections=true
Session\QueueingSystemEnabled=true
Session\SSL\Port=25181
Session\SeedChokingAlgorithm=AntiLeech
Session\ShareLimitAction=Stop
Session\SlowTorrentsDownloadRate=100
Session\SlowTorrentsInactivityTimer=5
Session\SlowTorrentsUploadRate=100
Session\SubcategoriesEnabled=true
Session\SuggestMode=true
Session\Tags=Don't Kill
Session\TempPath=/downloads/incomplete/
Session\TempPathEnabled=true
Session\TorrentExportDirectory=/blackhole
Session\UseCategoryPathsInManualMode=true
Session\UseUnwantedFolder=true
Session\uTPMixedMode=Proportional

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
PortForwardingEnabled=true
Proxy\AuthEnabled=false
Proxy\HostnameLookupEnabled=true
Proxy\IP=warp
Proxy\Password=proxypassword
Proxy\Port=@Variant(\0\0\0\x85\x4\x38)
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true
Proxy\Type=SOCKS5
Proxy\Username=proxyuser

[Preferences]
Advanced\IgnoreSSLErrors=false
Advanced\RecheckOnCompletion=false
Advanced\confirmTorrentRecheck=false
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
General\Locale=en
General\StatusbarExternalIPDisplayed=true
MailNotification\req_auth=true
WebUI\Address=*
WebUI\AuthSubnetWhitelist=152.117.108.32/32
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(feNPr1ueNOHPjJ/mpH0MTA==:nHgXdXQ4N/r/Yd23a/7c8Mcb9H8dh+RdgWKf+ijhoKUkhLmrt803BafR6Rqssgyeky9dpz3jqAWxoXrPJvr5pg==)"
WebUI\Port=8084
WebUI\ServerDomains=*
WebUI\UseUPnP=true
WebUI\Username=brunner56

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\EnableProcessing=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
Session\EnableProcessing=true
