apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart-logs-pvc.fullname" . }}-logs
  labels:
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  {{- include "chart-logs-pvc.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.logs.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.logs.storageClass | quote }}
