apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    local.path.provisioner/selected-node: beatapostapita
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-f6c1b927-f764-46aa-9e3c-91da43c9d235
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: symlinks
    namespace: default
  local:
    path: /var/lib/rancher/k3s/storage/pvc-f6c1b927-f764-46aa-9e3c-91da43c9d235_default_symlinks
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - beatapostapita
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
  lastPhaseTransitionTime: "2025-06-12T00:54:49Z"
  phase: Bound
