apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    local.path.provisioner/selected-node: beatapostapita
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-cceed13f-b8c6-42b3-8637-46e6869a0221
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-data-redis-0
    namespace: default
  local:
    path: /var/lib/rancher/k3s/storage/pvc-cceed13f-b8c6-42b3-8637-46e6869a0221_default_redis-data-redis-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - beatapostapita
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
  lastPhaseTransitionTime: "2025-06-14T15:02:59Z"
  phase: Bound
