apiVersion: v1
kind: Service
metadata:
  name: {{ include "gatus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatus.labels" . | nindent 4 }}
    app.kubernetes.io/service: {{ include "gatus.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "gatus.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 