apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"generation":1,"name":"warp","namespace":"bolabaden"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"warp"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"warp"}},"spec":{"containers":[{"env":[{"name":"TUNNEL_TOKEN","value":"eyJhIjoiZTRlYjNkYmViMTJiZWFhY2MxNzcwNDEyMzE3OTA0NTQiLCJ0IjoiM2ExODhhOTMtYzQwNC00Zjg5LTg4NzItOThlMDkxNjNiYzAzIiwicyI6Ill6SmpNVFl5WmpNdE9EYzROUzAwWlRrMUxUazFORFl0TWpnd1lXWXhZVEpsT1dNMiJ9"},{"name":"WARP_LICENSE_KEY","value":"eyJhIjoiZTRlYjNkYmViMTJiZWFhY2MxNzcwNDEyMzE3OTA0NTQiLCJ0IjoiM2ExODhhOTMtYzQwNC00Zjg5LTg4NzItOThlMDkxNjNiYzAzIiwicyI6Ill6SmpNVFl5WmpNdE9EYzROUzAwWlRrMUxUazFORFl0TWpnd1lXWXhZVEpsT1dNMiJ9"},{"name":"WARP_SLEEP","value":"2"}],"image":"caomingjun/warp:latest","imagePullPolicy":"IfNotPresent","name":"warp","ports":[{"containerPort":8888,"name":"warp-8888","protocol":"TCP"},{"containerPort":4000,"name":"warp-4000","protocol":"TCP"},{"containerPort":3232,"name":"warp-3232","protocol":"TCP"},{"containerPort":443,"name":"warp-443","protocol":"TCP"},{"containerPort":1080,"name":"warp-1080","protocol":"TCP"},{"containerPort":3005,"name":"warp-3005","protocol":"TCP"},{"containerPort":8000,"name":"warp-8000","protocol":"TCP"},{"containerPort":8181,"name":"warp-8181","protocol":"TCP"},{"containerPort":8469,"name":"warp-8469","protocol":"TCP"},{"containerPort":3185,"name":"warp-3185","protocol":"TCP"}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"securityContext":{"capabilities":{"add":["MKNOD","AUDIT_WRITE","NET_ADMIN"]}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/lib/cloudflare-warp","name":"var-lib-cloudflare-warp"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"sysctls":[{"name":"net.ipv4.conf.all.src_valid_mark","value":"1"},{"name":"net.ipv6.conf.all.disable_ipv6","value":"1"}]},"terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/home/ubuntu/my-media-stack/data","type":""},"name":"var-lib-cloudflare-warp"}]}}}}
  name: warp
  namespace: bolabaden
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: warp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: warp
    spec:
      containers:
      - env:
        - name: TUNNEL_TOKEN
          value: eyJhIjoiZTRlYjNkYmViMTJiZWFhY2MxNzcwNDEyMzE3OTA0NTQiLCJ0IjoiM2ExODhhOTMtYzQwNC00Zjg5LTg4NzItOThlMDkxNjNiYzAzIiwicyI6Ill6SmpNVFl5WmpNdE9EYzROUzAwWlRrMUxUazFORFl0TWpnd1lXWXhZVEpsT1dNMiJ9
        - name: WARP_LICENSE_KEY
          value: eyJhIjoiZTRlYjNkYmViMTJiZWFhY2MxNzcwNDEyMzE3OTA0NTQiLCJ0IjoiM2ExODhhOTMtYzQwNC00Zjg5LTg4NzItOThlMDkxNjNiYzAzIiwicyI6Ill6SmpNVFl5WmpNdE9EYzROUzAwWlRrMUxUazFORFl0TWpnd1lXWXhZVEpsT1dNMiJ9
        - name: WARP_SLEEP
          value: "2"
        image: caomingjun/warp:latest
        imagePullPolicy: IfNotPresent
        name: warp
        ports:
        - containerPort: 8888
          name: warp-8888
          protocol: TCP
        - containerPort: 4000
          name: warp-4000
          protocol: TCP
        - containerPort: 3232
          name: warp-3232
          protocol: TCP
        - containerPort: 443
          name: warp-443
          protocol: TCP
        - containerPort: 1080
          name: warp-1080
          protocol: TCP
        - containerPort: 3005
          name: warp-3005
          protocol: TCP
        - containerPort: 8000
          name: warp-8000
          protocol: TCP
        - containerPort: 8181
          name: warp-8181
          protocol: TCP
        - containerPort: 8469
          name: warp-8469
          protocol: TCP
        - containerPort: 3185
          name: warp-3185
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          capabilities:
            add:
            - MKNOD
            - AUDIT_WRITE
            - NET_ADMIN
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/cloudflare-warp
          name: var-lib-cloudflare-warp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        sysctls:
        - name: net.ipv4.conf.all.src_valid_mark
          value: "1"
        - name: net.ipv6.conf.all.disable_ipv6
          value: "1"
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /home/ubuntu/my-media-stack/data
          type: ""
        name: var-lib-cloudflare-warp
  conditions:
  - lastTransitionTime: "2025-06-14T19:17:49Z"
    lastUpdateTime: "2025-06-14T19:17:49Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    type: Available
  - lastTransitionTime: "2025-06-14T22:52:04Z"
    lastUpdateTime: "2025-06-14T22:52:04Z"
    message: ReplicaSet "warp-56c8b6cbf4" has timed out progressing.
    reason: ProgressDeadlineExceeded
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
