apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elfhosted-neat-final.fullname" . }}-brunner56-riven
  labels:
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  {{- include "elfhosted-neat-final.labels" . | nindent 4 }}
  annotations:
    configmap.reloader.stakater.com/reload: elfbot-all,elfbot-riven,riven-env,riven-setup
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
spec:
  replicas: {{ .Values.brunner56Riven.replicas }}
  revisionHistoryLimit: {{ .Values.brunner56Riven.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.brunner56Riven.strategy.type | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: brunner56
      app.kubernetes.io/name: riven
    {{- include "elfhosted-neat-final.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.elfhosted.com/name: riven
        app.kubernetes.io/instance: brunner56
        app.kubernetes.io/name: riven
      {{- include "elfhosted-neat-final.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.elfhosted.com/role
                operator: In
                values:
                - nodefinder
            topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: false
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: {{ include "elfhosted-neat-final.fullname" . }}-riven-env
        - configMapRef:
            name: elfbot-riven
            optional: true
        image: {{ .Values.brunner56Riven.brunner56Riven.image.repository }}:{{ .Values.brunner56Riven.brunner56Riven.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.brunner56Riven.brunner56Riven.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3001
          timeoutSeconds: 1
        name: brunner56-riven
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3001
          timeoutSeconds: 1
        resources: {{- toYaml .Values.brunner56Riven.brunner56Riven.resources | nindent
          10 }}
        securityContext: {{- toYaml .Values.brunner56Riven.brunner56Riven.containerSecurityContext
          | nindent 10 }}
        startupProbe:
          failureThreshold: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 3001
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /backup
          name: backup
        - mountPath: /riven/data
          name: config
          subPath: riven
        - mountPath: /dev-shm
          name: dev-shm
        - mountPath: /elfbot
          name: elfbot
        - mountPath: /riven/data/logs
          name: logs
          subPath: riven
        - mountPath: /storage/rclone
          name: rclone
        - mountPath: /storage/realdebrid-zurg
          name: rclonemountrealdebridzurg
        - mountPath: /setup
          name: setup
        - mountPath: /storage/symlinks
          name: symlinks
        - mountPath: /tmp
          name: tmp
      - args: {{- toYaml .Values.brunner56Riven.database.args | nindent 8 }}
        env:
        - name: POSTGRES_PASSWORD
          value: {{ quote .Values.brunner56Riven.database.env.postgresPassword }}
        - name: POSTGRES_DB
          value: {{ quote .Values.brunner56Riven.database.env.postgresDb }}
        - name: POSTGRES_USER
          value: {{ quote .Values.brunner56Riven.database.env.postgresUser }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.brunner56Riven.database.image.repository }}:{{ .Values.brunner56Riven.database.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.brunner56Riven.database.imagePullPolicy }}
        name: database
        resources: {{- toYaml .Values.brunner56Riven.database.resources | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: config
          subPath: riven/postgresql/database
        - mountPath: /dev/shm
          name: dev-shm
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      initContainers:
      - command:
        - /bin/bash
        - -c
        - "set -e\n\n# Allows us to use app.elfhosted.com/name, but fall back to app.kubernetes.io/name
          if the former doesn't exist\nif [[ -z \"$ELF_APP_NAME\" ]]; then\n  ELF_APP_NAME=$K8S_APP_NAME\nfi\n\n#
          look for commands - we match specific names in order of least-destructive\nTIMESTAMP_NOW=$(date
          +%s)\nif [[ -f /etc/elfbot/pause ]]; then\n  TIMESTAMP_COMMAND=$(cat /etc/elfbot/pause)\n
          \ TIMESTAMP_DIFF=$((TIMESTAMP_NOW-TIMESTAMP_COMMAND))\n  if [[ $TIMESTAMP_DIFF
          -lt 600 ]]; then\n    COMMAND=pause\n  fi\nfi\n\n# If no command is set, then
          move onto the next possibility\nif [[ -f /etc/elfbot/backup && -z \"$COMMAND\"
          ]]; then\n  TIMESTAMP_COMMAND=$(cat /etc/elfbot/backup)\n  TIMESTAMP_DIFF=$((TIMESTAMP_NOW-TIMESTAMP_COMMAND))\n
          \ if [[ $TIMESTAMP_DIFF -lt 600 ]]; then\n    COMMAND=backup\n  fi\nfi\n\n# If
          no command is set, then move onto the next possibility\nif [[ -f /etc/elfbot/reset
          && -z \"$COMMAND\" ]]; then\n  TIMESTAMP_COMMAND=$(cat /etc/elfbot/reset)\n  TIMESTAMP_DIFF=$((TIMESTAMP_NOW-TIMESTAMP_COMMAND))\n
          \ if [[ $TIMESTAMP_DIFF -lt 600 ]]; then\n    COMMAND=reset\n  fi\nfi\n\ncase
          $COMMAND in\n\n  \"pause\")\n    echo \"Recent pause command found, sleeping 5m..\"\n
          \   sleep 300\n    ;;\n\n  \"reset\")\n\n    # Safety check - if /config/homer
          exists, we've not mounted /config properly and are about to wipe out EVERYTHING\n
          \   if [ -e \"/config/homer\" ]; then\n        echo \"The path /config/homer exists.
          Exiting.\"\n        exit 1\n    fi      \n    echo \"Recent reset command found,
          resetting\"\n    rm -rf /config/*\n    ;;\n\n  \"backup\")\n    echo \"Recent
          backup command found, backing up to /storage/backup/${ELF_APP_NAME}-${TIMESTAMP}\"\n
          \   TIMESTAMP=$(printf '%(%Y-%m-%d--%H-%M)T\\n' -1)\n    cp -rfp /config /storage/backup/$ELF_APP_NAME-$TIMESTAMP\n
          \   ;;\n\nesac\n\nif [[ ! -f /config/i-am-bootstrapped ]]\nthen\n  echo \"Bootstrapping
          from goldilocks config...\"\n  s5cmd sync s3://elfhosted-config/goldilocks/$ELF_APP_NAME/*
          /config/\n  touch /config/i-am-bootstrapped\nfi\n"
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access-key-id
              name: b2-elfhosted-config-ro
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: b2-elfhosted-config-ro
        - name: S3_ENDPOINT_URL
          value: {{ quote .Values.brunner56Riven.bootstrap.env.s3EndpointUrl }}
        - name: K8S_APP_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/name']
        - name: ELF_APP_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.elfhosted.com/name']
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.brunner56Riven.bootstrap.image.repository }}:{{ .Values.brunner56Riven.bootstrap.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.brunner56Riven.bootstrap.imagePullPolicy }}
        name: bootstrap
        resources: {{- toYaml .Values.brunner56Riven.bootstrap.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.brunner56Riven.bootstrap.containerSecurityContext
          | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/elfbot
          name: elfbot
        - mountPath: /storage/backup
          name: backup
        - mountPath: /config
          name: config
          subPath: riven
        - mountPath: /tmp
          name: tmp
      - command:
        - /bin/bash
        - -c
        - |
          # run the setup script from the configmap, so that we can make templated changes
          bash /setup/setup.sh
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.brunner56Riven.setup.image.repository }}:{{ .Values.brunner56Riven.setup.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.brunner56Riven.setup.imagePullPolicy }}
        name: setup
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /storage/symlinks
          name: symlinks
        - mountPath: /config
          name: config
          subPath: riven
        - mountPath: /setup/
          name: setup
      - command:
        - /bin/bash
        - -c
        - |
          set -x
          set -e
      
          mkdir -p /config/postgresql/database
          mkdir -p /config/postgresql/backups
          chown elfie:elfie /config -R
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.brunner56Riven.setupPostgres.image.repository }}:{{ .Values.brunner56Riven.setupPostgres.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.brunner56Riven.setupPostgres.imagePullPolicy }}
        name: setup-postgres
        resources: {}
        securityContext: {{- toYaml .Values.brunner56Riven.setupPostgres.containerSecurityContext
          | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
          subPath: riven
      priorityClassName: tenant-normal
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {{- toYaml .Values.brunner56Riven.podSecurityContext | nindent 8
        }}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - name: backup
        persistentVolumeClaim:
          claimName: {{ include "elfhosted-neat-final.fullname" . }}-backup
      - name: config
        persistentVolumeClaim:
          claimName: {{ include "elfhosted-neat-final.fullname" . }}-config
      - name: dev-shm
      - configMap:
          defaultMode: 420
          name: elfbot-riven
          optional: true
        name: elfbot
      - name: logs
        persistentVolumeClaim:
          claimName: {{ include "elfhosted-neat-final.fullname" . }}-logs
      - name: rclone
        persistentVolumeClaim:
          claimName: {{ include "elfhosted-neat-final.fullname" . }}-rclone
      - name: rclonemountrealdebridzurg
        persistentVolumeClaim:
          claimName: {{ include "elfhosted-neat-final.fullname" . }}-realdebrid-zurg
      - configMap:
          defaultMode: 420
          name: {{ include "elfhosted-neat-final.fullname" . }}-riven-setup
        name: setup
      - name: symlinks
        persistentVolumeClaim:
          claimName: {{ include "elfhosted-neat-final.fullname" . }}-symlinks
      - name: tmp
