apiVersion: v1
kind: Service
metadata:
  name: {{ include "elfhosted-neat-final.fullname" . }}-elfterm
  labels:
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  {{- include "elfhosted-neat-final.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
spec:
  type: {{ .Values.elfterm.type }}
  selector:
    app.kubernetes.io/instance: brunner56
    app.kubernetes.io/name: filebrowser
    {{- include "elfhosted-neat-final.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.elfterm.ports | toYaml | nindent 2 }}
