apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"proxy-injector"},"name":"proxy-injector","namespace":"vpn-gateway"},"spec":{"clusterIP":"10.43.99.96","clusterIPs":["10.43.99.96"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"webhook","port":443,"protocol":"TCP","targetPort":8443}],"selector":{"app":"proxy-injector"},"sessionAffinity":"None","type":"ClusterIP"}}
  labels:
    app: proxy-injector
  name: proxy-injector
  namespace: vpn-gateway
spec:
  clusterIP: 10.43.99.96
  clusterIPs:
  - 10.43.99.96
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: proxy-injector
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
