apiVersion: v1
kind: Secret
metadata:
  name: traefik-secrets
  namespace: my-media-stack
type: Opaque
data:
  # Base64 encoded values - replace with your actual base64 encoded secrets
  CLOUDFLARE_API_KEY: MzRhNGQ5OTQzOTc1Yjg5ZGQyNDMwODcwY2UxNDZmMjZhYTViZg==
  CLOUDFLARE_EMAIL: Ym9kZW4uY3JvdWNoQGdtYWlsLmNvbQ==
  CLOUDFLARE_DNS_API_TOKEN: ZnA2dGpaV2I2NnAxckN5WkJNOWswaHhyRTBuMFk3WGN0U1RXUDUySQ==
  CLOUDFLARE_ZONE_API_TOKEN: ZnA2dGpaV2I2NnAxckN5WkJNOWswaHhyRTBuMFk3WGN0U1RXUDUySQ==
  DUCKDNS_TOKEN: MmMxODc2OWEtMjg4OS00NjQ4LWE3MGMtMmZlNDRkZDEwZjIw
  LETS_ENCRYPT_EMAIL: Ym9kZW4uY3JvdWNoQGdtYWlsLmNvbQ== 