apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ResourceQuota","metadata":{"annotations":{},"name":"vpn-gateway-quota","namespace":"vpn-gateway"},"spec":{"hard":{"limits.cpu":"1600m","limits.memory":"3Gi","pods":"10","requests.cpu":"800m","requests.memory":"1.5Gi"}}}
  name: vpn-gateway-quota
  namespace: vpn-gateway
spec:
  hard:
    limits.cpu: 1600m
    limits.memory: 3Gi
    pods: "10"
    requests.cpu: 800m
    requests.memory: 1536Mi
  hard:
    limits.cpu: 1600m
    limits.memory: 3Gi
    pods: "10"
    requests.cpu: 800m
    requests.memory: 1536Mi
  used:
    limits.cpu: 1300m
    limits.memory: 1920Mi
    pods: "6"
    requests.cpu: 550m
    requests.memory: 704Mi
