apiVersion: v1
data:
  s3cfg: |
    [default]
    bucket_location = us-west-002
    host_base = s3.us-west-002.backblazeb2.com
    host_bucket = %(bucket)s.s3.us-west-002.backblazeb2.com
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"s3cfg":"[default]\nbucket_location = us-west-002\nhost_base = s3.us-west-002.backblazeb2.com\nhost_bucket = %(bucket)s.s3.us-west-002.backblazeb2.com\n"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"brunner56","meta.helm.sh/release-namespace":"bolabaden"},"labels":{"app.kubernetes.io/managed-by":"Helm","helm.toolkit.fluxcd.io/name":"brunner56","helm.toolkit.fluxcd.io/namespace":"bolabaden"},"name":"b2-s3cmd-restore-config","namespace":"bolabaden"}}
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: bolabaden
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: bolabaden
  name: b2-s3cmd-restore-config
  namespace: bolabaden
