apiVersion: v1
data:
  nat.conf: "# Fully dynamic - no static assignments needed \n"
  settings.sh: |
    #!/bin/bash
    VXLAN_ID="42"
    VXLAN_IP_NETWORK="172.16.0"
    VXLAN_GATEWAY_FIRST_DYNAMIC_IP=10
    VPN_INTERFACE=CloudflareWARP
    VPN_BLOCK_OTHER_TRAFFIC=false
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"nat.conf":"# Fully dynamic - no static assignments needed \n","settings.sh":"#!/bin/bash\nVXLAN_ID=\"42\"\nVXLAN_IP_NETWORK=\"172.16.0\"\nVXLAN_GATEWAY_FIRST_DYNAMIC_IP=10\nVPN_INTERFACE=CloudflareWARP\nVPN_BLOCK_OTHER_TRAFFIC=false\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"pod-gateway-config","namespace":"bolabaden"}}
  name: pod-gateway-config
  namespace: bolabaden
