apiVersion: v1
data:
  rclone-remote-storage: |
    [storage]
    type = alias
    remote = /storage
  settings.js: |
    export const guiVersion = "0.4.0";
    export const rcloneSettings = {
        host: "https://brunner56-rclonefm.elfhosted.com",
        // null if --rc-no-auth, otherwise what is set in --rc-user
        user: null,
        // null if --rc-no-auth, otherwise what is set in --rc-pass
        pass: null,
        // null if there is no login_token in URL query parameters,
        // otherwise is set from there and takes over user/pass
        loginToken: null
    };
    export const asyncOperations = [
        "/sync/copy",
        "/sync/move",
        "/operations/purge",
        "/operations/copyfile",
        "/operations/movefile",
        "/operations/deletefile"
    ];
    export const remotes = {
        "storage": {
            "startingFolder": "/storage",
            "canQueryDisk": true,
            "pathToQueryDisk": ""
        }
    };
    export const userSettings = {
        timerRefreshEnabled: true,
        timerRefreshView: 2,
        timerRefreshViewInterval: undefined,
        timerProcessQueue: 5,
        timerProcessQueueInterval: undefined
    };
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"rclone-remote-storage":"[storage]\ntype = alias\nremote = /storage\n","settings.js":"export const guiVersion = \"0.4.0\";\nexport const rcloneSettings = {\n    host: \"https://brunner56-rclonefm.elfhosted.com\",\n    // null if --rc-no-auth, otherwise what is set in --rc-user\n    user: null,\n    // null if --rc-no-auth, otherwise what is set in --rc-pass\n    pass: null,\n    // null if there is no login_token in URL query parameters,\n    // otherwise is set from there and takes over user/pass\n    loginToken: null\n};\nexport const asyncOperations = [\n    \"/sync/copy\",\n    \"/sync/move\",\n    \"/operations/purge\",\n    \"/operations/copyfile\",\n    \"/operations/movefile\",\n    \"/operations/deletefile\"\n];\nexport const remotes = {\n    \"storage\": {\n        \"startingFolder\": \"/storage\",\n        \"canQueryDisk\": true,\n        \"pathToQueryDisk\": \"\"\n    }\n};\nexport const userSettings = {\n    timerRefreshEnabled: true,\n    timerRefreshView: 2,\n    timerRefreshViewInterval: undefined,\n    timerProcessQueue: 5,\n    timerProcessQueueInterval: undefined\n};\n"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"brunner56","meta.helm.sh/release-namespace":"my-media-stack"},"labels":{"app.kubernetes.io/managed-by":"Helm","helm.toolkit.fluxcd.io/name":"brunner56","helm.toolkit.fluxcd.io/namespace":"my-media-stack"},"name":"rclonefm-config","namespace":"bolabaden"}}
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  name: rclonefm-config
  namespace: bolabaden
