apiVersion: v1
data:
  setup.sh: |
    #!/bin/bash

    # make symlink directories if they don't exist, to make onboarding simpler
    mkdir -p /storage/symlinks/movies
    mkdir -p /storage/symlinks/shows

    # Enforce API key
    contents="$(jq '.api_key="1nMZNC0Cg6UP7sblvFirUi9Sad4ga84u"' /config/settings.json)" && \
      echo -E "${contents}" > /config/settings.json
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"setup.sh":"#!/bin/bash\n\n# make symlink directories if they don't exist, to make onboarding simpler\nmkdir -p /storage/symlinks/movies\nmkdir -p /storage/symlinks/shows\n\n# Enforce API key\ncontents=\"$(jq '.api_key=\"1nMZNC0Cg6UP7sblvFirUi9Sad4ga84u\"' /config/settings.json)\" \u0026\u0026 \\\n  echo -E \"${contents}\" \u003e /config/settings.json\n"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"brunner56","meta.helm.sh/release-namespace":"my-media-stack"},"labels":{"app.kubernetes.io/managed-by":"Helm","helm.toolkit.fluxcd.io/name":"brunner56","helm.toolkit.fluxcd.io/namespace":"my-media-stack"},"name":"riven-setup","namespace":"bolabaden"}}
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  name: riven-setup
  namespace: bolabaden
