apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    local.path.provisioner/selected-node: baden.vpshostingservice.co
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-3e192e16-b32f-4866-a9a9-010e4cb4e541
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: influxdb-data-influxdb-0
    namespace: default
  local:
    path: /var/lib/rancher/k3s/storage/pvc-3e192e16-b32f-4866-a9a9-010e4cb4e541_default_influxdb-data-influxdb-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - baden.vpshostingservice.co
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  volumeMode: Filesystem
  lastPhaseTransitionTime: "2025-06-14T15:03:04Z"
  phase: Bound
