package failover

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// TraefikWriterPriority beats typical Docker-provider rule-length priorities.
const TraefikWriterPriority = 1000

// TraefikWriterConfig configures failover-fallbacks.yaml generation.
type TraefikWriterConfig struct {
	Domain     string
	LocalNode  string
	PeerHosts  []string
	OutputPath string
}

// DefaultTraefikWriterConfig returns sensible defaults.
func DefaultTraefikWriterConfig(domain, localNode, outputPath string, peers []string) TraefikWriterConfig {
	return TraefikWriterConfig{
		Domain:     domain,
		LocalNode:  localNode,
		PeerHosts:  peers,
		OutputPath: outputPath,
	}
}

// WriteFailoverYAML emits Traefik dynamic config from the registry.
//
// Both global Host(`svc.$DOMAIN`) and node-direct Host(`svc.<node>.$DOMAIN`)
// for local + every peer point at the same peer-aware loadBalancer. Local
// http://svc:port is omitted when the service is not running/unhealthy on this
// node. Peer HTTPS backends are emitted only for peers where the registry
// shows running/unhealthy (avoids recursion to empty Traefiks).
//
// This agent owns failover-fallbacks.yaml; do not run osvc_ingress_sync
// concurrently on the same node.
func WriteFailoverYAML(reg *Registry, cfg TraefikWriterConfig) error {
	if cfg.Domain == "" {
		return fmt.Errorf("domain is required")
	}
	if cfg.OutputPath == "" {
		return fmt.Errorf("output path is required")
	}

	entries := reg.List()
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Name < entries[j].Name
	})

	nodes := knownNodes(cfg.LocalNode, cfg.PeerHosts)

	var b strings.Builder
	b.WriteString("# Generated by failover-agent — sole owner of this file\n")
	b.WriteString("# Do not run scripts/osvc_ingress_sync.py against the same path concurrently\n")
	b.WriteString(fmt.Sprintf("# generated_at: %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString("# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3-file-provider.json\n")
	b.WriteString("http:\n")
	b.WriteString("  serversTransports:\n")
	b.WriteString("    failover-peers:\n")
	b.WriteString("      insecureSkipVerify: true\n")
	b.WriteString("  routers:\n")

	for _, e := range entries {
		if e.Port <= 0 {
			continue
		}
		name := sanitizeName(e.Name)

		b.WriteString(fmt.Sprintf("    %s-with-failover:\n", name))
		b.WriteString(fmt.Sprintf("      service: %s-with-failover@file\n", name))
		b.WriteString(fmt.Sprintf("      rule: Host(`%s.%s`)\n", name, cfg.Domain))
		b.WriteString("      entryPoints:\n")
		b.WriteString("        - websecure\n")
		b.WriteString(fmt.Sprintf("      priority: %d\n", TraefikWriterPriority))
		writeMiddlewares(&b, e.Middlewares)

		for _, node := range nodes {
			b.WriteString(fmt.Sprintf("    %s-direct-%s:\n", name, sanitizeName(node)))
			b.WriteString(fmt.Sprintf("      service: %s-with-failover@file\n", name))
			b.WriteString(fmt.Sprintf("      rule: Host(`%s.%s.%s`)\n", name, node, cfg.Domain))
			b.WriteString("      entryPoints:\n")
			b.WriteString("        - websecure\n")
			b.WriteString(fmt.Sprintf("      priority: %d\n", TraefikWriterPriority))
			writeMiddlewares(&b, e.Middlewares)
		}
	}

	b.WriteString("  services:\n")
	for _, e := range entries {
		if e.Port <= 0 {
			continue
		}
		name := sanitizeName(e.Name)
		healthPath := e.HealthPath
		if healthPath == "" {
			healthPath = "/"
		}
		healthInterval := e.HealthInterval
		if healthInterval == "" {
			healthInterval = "15s"
		}
		healthTimeout := e.HealthTimeout
		if healthTimeout == "" {
			healthTimeout = "5s"
		}

		activePeers := ActivePeerBackends(e, cfg.LocalNode, cfg.PeerHosts)

		b.WriteString(fmt.Sprintf("    %s-with-failover:\n", name))
		b.WriteString("      loadBalancer:\n")
		b.WriteString("        serversTransport: failover-peers\n")
		b.WriteString("        servers:\n")
		if LocalBackendActive(e, cfg.LocalNode) {
			b.WriteString(fmt.Sprintf("          - url: http://%s:%d\n", name, e.Port))
		}
		for _, peer := range activePeers {
			b.WriteString(fmt.Sprintf("          - url: https://%s.%s.%s\n", name, peer, cfg.Domain))
		}
		if !LocalBackendActive(e, cfg.LocalNode) && len(activePeers) == 0 {
			b.WriteString(fmt.Sprintf("          - url: http://%s:%d\n", name, e.Port))
		}
		b.WriteString("        healthCheck:\n")
		b.WriteString(fmt.Sprintf("          path: %q\n", healthPath))
		b.WriteString(fmt.Sprintf("          interval: %s\n", healthInterval))
		b.WriteString(fmt.Sprintf("          timeout: %s\n", healthTimeout))
	}

	if err := os.MkdirAll(filepath.Dir(cfg.OutputPath), 0o755); err != nil {
		return err
	}
	tmp := cfg.OutputPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, cfg.OutputPath)
}

// LocalBackendActive reports whether this node should emit a local http:// backend.
func LocalBackendActive(e *ServiceEntry, localNode string) bool {
	if e == nil {
		return false
	}
	if localNode != "" && e.Nodes != nil {
		if np, ok := e.Nodes[localNode]; ok && np != nil {
			return np.Status == StatusRunning || np.Status == StatusUnhealthy
		}
		return false
	}
	return e.Status == StatusRunning || e.Status == StatusUnhealthy
}

// ActivePeerBackends returns peer hostnames that should receive HTTPS backend URLs.
func ActivePeerBackends(e *ServiceEntry, localNode string, peerHosts []string) []string {
	if e == nil {
		return nil
	}
	var out []string
	seen := map[string]bool{}
	for _, peer := range peerHosts {
		peer = strings.TrimSpace(peer)
		if peer == "" || peer == localNode || seen[peer] {
			continue
		}
		if !peerBackendActive(e, peer) {
			continue
		}
		seen[peer] = true
		out = append(out, peer)
	}
	return out
}

func peerBackendActive(e *ServiceEntry, peer string) bool {
	if e.Nodes == nil {
		return false
	}
	np, ok := e.Nodes[peer]
	if !ok || np == nil {
		return false
	}
	return np.Status == StatusRunning || np.Status == StatusUnhealthy
}

func knownNodes(local string, peers []string) []string {
	seen := map[string]bool{}
	var out []string
	add := func(n string) {
		n = strings.TrimSpace(n)
		if n == "" || seen[n] {
			return
		}
		seen[n] = true
		out = append(out, n)
	}
	add(local)
	for _, p := range peers {
		add(p)
	}
	sort.Strings(out)
	return out
}

func filterPeers(peers []string, local string) []string {
	var out []string
	for _, p := range peers {
		p = strings.TrimSpace(p)
		if p == "" || p == local {
			continue
		}
		out = append(out, p)
	}
	return out
}

func writeMiddlewares(b *strings.Builder, mws []string) {
	if len(mws) == 0 {
		return
	}
	b.WriteString("      middlewares:\n")
	for _, mw := range mws {
		b.WriteString(fmt.Sprintf("        - %s\n", mw))
	}
}

func sanitizeName(name string) string {
	name = strings.TrimPrefix(name, "/")
	if idx := strings.LastIndex(name, "/"); idx >= 0 {
		name = name[idx+1:]
	}
	return name
}
