{{- if .Values.persistence.config.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
  {{- with .Values.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.config.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
  {{- if or .Values.global.storageClass .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass | default .Values.global.storageClass }}
  {{- end }}
  volumeMode: Filesystem
{{- end }}

{{- if .Values.persistence.backup.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-backup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
  {{- with .Values.persistence.backup.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.backup.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backup.size | quote }}
  {{- if or .Values.global.storageClass .Values.persistence.backup.storageClass }}
  storageClassName: {{ .Values.persistence.backup.storageClass | default .Values.global.storageClass }}
  {{- end }}
  volumeMode: Filesystem
{{- end }}

{{- if .Values.persistence.logs.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-logs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
  {{- with .Values.persistence.logs.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.logs.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size | quote }}
  {{- if or .Values.global.storageClass .Values.persistence.logs.storageClass }}
  storageClassName: {{ .Values.persistence.logs.storageClass | default .Values.global.storageClass }}
  {{- end }}
  volumeMode: Filesystem
{{- end }}

{{- if .Values.persistence.rclone.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-rclone
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
  {{- with .Values.persistence.rclone.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.rclone.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.rclone.size | quote }}
  {{- if or .Values.global.storageClass .Values.persistence.rclone.storageClass }}
  storageClassName: {{ .Values.persistence.rclone.storageClass | default .Values.global.storageClass }}
  {{- end }}
  volumeMode: Filesystem
{{- end }}

{{- if .Values.persistence.symlinks.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-symlinks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
  {{- with .Values.persistence.symlinks.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.symlinks.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.symlinks.size | quote }}
  {{- if or .Values.global.storageClass .Values.persistence.symlinks.storageClass }}
  storageClassName: {{ .Values.persistence.symlinks.storageClass | default .Values.global.storageClass }}
  {{- end }}
  volumeMode: Filesystem
{{- end }}

{{- if .Values.persistence.realdebridZurg.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-realdebrid-zurg
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
  {{- with .Values.persistence.realdebridZurg.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.realdebridZurg.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.realdebridZurg.size | quote }}
  {{- if or .Values.global.storageClass .Values.persistence.realdebridZurg.storageClass }}
  storageClassName: {{ .Values.persistence.realdebridZurg.storageClass | default .Values.global.storageClass }}
  {{- end }}
  volumeMode: Filesystem
{{- end }}