apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elfhosted-combined.fullname" . }}-plex-config
  labels:
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  {{- include "elfhosted-combined.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
data:
  ADVERTISE_IP: {{ .Values.plexConfig.advertiseIp | quote }}
  PLEX_PREFERENCE_2: {{ .Values.plexConfig.plexPreference2 | quote }}
  PLEX_PREFERENCE_3: {{ .Values.plexConfig.plexPreference3 | quote }}
  PLEX_PREFERENCE_4: {{ .Values.plexConfig.plexPreference4 | quote }}
  PLEX_PREFERENCE_7: {{ .Values.plexConfig.plexPreference7 | quote }}
  PLEX_PREFERENCE_8: {{ .Values.plexConfig.plexPreference8 | quote }}
  PLEX_PREFERENCE_9: {{ .Values.plexConfig.plexPreference9 | quote }}
  PLEX_PREFERENCE_10: {{ .Values.plexConfig.plexPreference10 | quote }}
  PLEX_PREFERENCE_11: {{ .Values.plexConfig.plexPreference11 | quote }}
  PLEX_PREFERENCE_12: {{ .Values.plexConfig.plexPreference12 | quote }}
  PLEX_PREFERENCE_13: {{ .Values.plexConfig.plexPreference13 | quote }}
  PLEX_PREFERENCE_14: {{ .Values.plexConfig.plexPreference14 | quote }}
  PLEX_PREFERENCE_15: {{ .Values.plexConfig.plexPreference15 | quote }}
  PLEX_PREFERENCE_16: {{ .Values.plexConfig.plexPreference16 | quote }}
  PLEX_PREFERENCE_17: {{ .Values.plexConfig.plexPreference17 | quote }}
  PLEX_PREFERENCE_18: {{ .Values.plexConfig.plexPreference18 | quote }}
  PLEX_PREFERENCE_19: {{ .Values.plexConfig.plexPreference19 | quote }}
  PLEX_PREFERENCE_20: {{ .Values.plexConfig.plexPreference20 | quote }}
  PLEX_PREFERENCE_21: {{ .Values.plexConfig.plexPreference21 | quote }}
  PLEX_PREFERENCE_22: {{ .Values.plexConfig.plexPreference22 | quote }}
  PLEX_PREFERENCE_23: {{ .Values.plexConfig.plexPreference23 | quote }}
  PLEX_PREFERENCE_24: {{ .Values.plexConfig.plexPreference24 | quote }}
  PLEX_PREFERENCE_25: {{ .Values.plexConfig.plexPreference25 | quote }}
  WAIT_FOR_MOUNT_PATHS: {{ .Values.plexConfig.waitForMountPaths | quote }}
  WAIT_FOR_URLS: {{ .Values.plexConfig.waitForUrls | quote }}
  WAIT_FOR_VPN: {{ .Values.plexConfig.waitForVpn | quote }}
