apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-14T17:22:11Z"
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Metrics-server
    objectset.rio.cattle.io/hash: a5d3bc601c871e123fa32b27f549b6ea770bcf4a
  name: metrics-server
  namespace: kube-system
subsets:
- addresses:
  - ip: 10.42.0.11
    nodeName: beatapostapita
    targetRef:
      kind: Pod
      name: metrics-server-6f4c6675d5-g6br4
      namespace: kube-system
  ports:
  - name: https
    port: 10250
    protocol: TCP
