apiVersion: v1
kind: Pod
metadata:
  generateName: local-path-provisioner-774c6665dc-
  labels:
    app: local-path-provisioner
    pod-template-hash: 774c6665dc
  name: local-path-provisioner-774c6665dc-rlfng
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: local-path-provisioner-774c6665dc
spec:
  containers:
  - command:
    - local-path-provisioner
    - start
    - --config
    - /etc/config/config.json
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: rancher/local-path-provisioner:v0.0.31
    imagePullPolicy: IfNotPresent
    name: local-path-provisioner
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/config/
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xncpd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: beatapostapita
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: local-path-provisioner-service-account
  serviceAccountName: local-path-provisioner-service-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: local-path-config
    name: config-volume
  - name: kube-api-access-xncpd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:20:43Z"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-06-11T06:36:46Z"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:21:08Z"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:21:08Z"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-11T06:36:46Z"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://7fc265a9360bf180f79aa28a32706c23f985d0c7db464b4c7ce8108dee507341
    image: docker.io/rancher/local-path-provisioner:v0.0.31
    imageID: docker.io/rancher/local-path-provisioner@sha256:80496fdeb307541007621959aa13aed41d31db9cd2dc4167c19833e0bfa3878c
    lastState:
      terminated:
        containerID: containerd://ef2af74f6149ea07eaecd38adbd0199794a41055d1b21fe6a809924be8cf2fa5
        exitCode: 1
        finishedAt: "2025-06-14T17:20:44Z"
        reason: Error
        startedAt: "2025-06-14T17:20:43Z"
    name: local-path-provisioner
    ready: true
    restartCount: 5
    started: true
    state:
      running:
        startedAt: "2025-06-14T17:21:07Z"
    volumeMounts:
    - mountPath: /etc/config/
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-xncpd
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.0.0.81
  hostIPs:
  - ip: 10.0.0.81
  phase: Running
  podIP: 10.42.0.238
  podIPs:
  - ip: 10.42.0.238
  qosClass: BestEffort
  startTime: "2025-06-11T06:36:46Z"
