apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elfhosted-neat-final.fullname" . }}-mattermost-backup
  labels:
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  {{- include "elfhosted-neat-final.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
data:
  daily: {{ .Values.mattermostBackup.daily | toYaml | indent 1 }}
