apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elfhosted-neat-final.fullname" . }}-wizarr-steps-jellyfin
  labels:
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  {{- include "elfhosted-neat-final.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
data:
  01_download.md: {{ .Values.wizarrStepsJellyfin.01DownloadMd | toYaml | indent 1
    }}
  02_about.md: {{ .Values.wizarrStepsJellyfin.02AboutMd | toYaml | indent 1 }}
  03_requests.md: {{ .Values.wizarrStepsJellyfin.03RequestsMd | toYaml | indent 1
    }}
  04_discord.md: {{ .Values.wizarrStepsJellyfin.04DiscordMd | toYaml | indent 1 }}
  05_tips.md: {{ .Values.wizarrStepsJellyfin.05TipsMd | toYaml | indent 1 }}
  06_elfhosted.md: {{ .Values.wizarrStepsJellyfin.06ElfhostedMd | toYaml | indent
    1 }}
