apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart-volsync-rs-symlinks-cache-pvc.fullname" . }}-volsync-rs-symlinks-cache
  labels:
    app.kubernetes.io/created-by: volsync
  {{- include "chart-volsync-rs-symlinks-cache-pvc.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.volsyncRsSymlinksCache.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.volsyncRsSymlinksCache.storageClass | quote }}
