apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-wizarr-env-configmap.fullname" . }}-wizarr-env
  labels:
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  {{- include "chart-wizarr-env-configmap.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
data:
  APP_URL: {{ .Values.wizarrEnv.appUrl | quote }}
  DISABLE_BUILTIN_AUTH: {{ .Values.wizarrEnv.disableBuiltinAuth | quote }}
