apiVersion: v1
kind: Pod
metadata:
  generateName: homepage-6f79d4cf9c-
  labels:
    app: homepage
    pod-template-hash: 6f79d4cf9c
  name: homepage-6f79d4cf9c-f9qrj
  namespace: bolabaden
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: homepage-6f79d4cf9c
spec:
  containers:
  - env:
    - name: HOMEPAGE_ALLOWED_HOSTS
      value: '*'
    - name: HOMEPAGE_VAR_HEADER_STYLE
    - name: HOMEPAGE_VAR_SEARCH_PROVIDER
      value: google
    - name: HOMEPAGE_VAR_TITLE
      value: my-media-stack
    - name: HOMEPAGE_VAR_WEATHER_CITY
      value: Chicago
    - name: HOMEPAGE_VAR_WEATHER_LAT
      value: "41.8781"
    - name: HOMEPAGE_VAR_WEATHER_LONG
      value: "-87.6298"
    - name: HOMEPAGE_VAR_WEATHER_UNIT
      value: fahrenheit
    - name: TZ
      value: America/Chicago
    image: ghcr.io/gethomepage/homepage
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - wget -qO- http://127.0.0.1:3000 > /dev/null 2>&1 || exit 1
      failureThreshold: 3
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 15
    name: homepage
    ports:
    - containerPort: 3000
      name: homepage-3000
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: var-run-docker-sock
    - mountPath: /app/config
      name: app-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hqp7b
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: beatapostapita
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: var-run-docker-sock
  - hostPath:
      path: /home/ubuntu/my-media-stack/configs/homepage
      type: ""
    name: app-config
  - name: kube-api-access-hqp7b
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:32:55Z"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:32:53Z"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:32:55Z"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:32:55Z"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:32:52Z"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://d32c5783d9595db64dc7d6163d0fdc2235e1fd1af6cd037fa9ae6525c1b1a41b
    image: ghcr.io/gethomepage/homepage:latest
    imageID: ghcr.io/gethomepage/homepage@sha256:4f923bf0e9391b3a8bc5527e539b022e92dcc8a3a13e6ab66122ea9ed030e196
    lastState: {}
    name: homepage
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-06-14T22:32:54Z"
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: var-run-docker-sock
    - mountPath: /app/config
      name: app-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-hqp7b
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.0.0.81
  hostIPs:
  - ip: 10.0.0.81
  phase: Running
  podIP: 10.42.0.74
  podIPs:
  - ip: 10.42.0.74
  qosClass: Burstable
  startTime: "2025-06-14T22:32:53Z"
