apiVersion: v1
kind: Pod
metadata:
  generateName: redis-5f8dd778fb-
  labels:
    app: redis
    pod-template-hash: 5f8dd778fb
  name: redis-5f8dd778fb-fsnj7
  namespace: bolabaden
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: redis-5f8dd778fb
spec:
  containers:
  - command:
    - redis-server
    - --appendonly
    - "yes"
    - --save
    - "60"
    - "1"
    image: redis:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - redis-cli ping > /dev/null 2>&1 || exit 1
      failureThreshold: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: redis
    ports:
    - containerPort: 6379
      name: redis-6379
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dnkt6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: beatapostapita
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /home/ubuntu/my-media-stack/configs/redis
      type: ""
    name: data
  - name: kube-api-access-dnkt6
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:42:08Z"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:42:04Z"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:42:08Z"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:42:08Z"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:42:03Z"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://fb4e5463f7b4f518a2df0c52a461edb15feb0cde0943fce59c6c373cdd48b978
    image: docker.io/library/redis:latest
    imageID: docker.io/library/redis@sha256:1b835e5a8d5db58e8b718850bf43a68ef5a576fc68301fd08a789b20b4eecb61
    lastState: {}
    name: redis
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-06-14T22:42:08Z"
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dnkt6
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.0.0.81
  hostIPs:
  - ip: 10.0.0.81
  phase: Running
  podIP: 10.42.0.93
  podIPs:
  - ip: 10.42.0.93
  qosClass: Burstable
  startTime: "2025-06-14T22:42:04Z"
