apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-14T17:40:44Z"
  labels:
    app: gluetun-premiumize-ca
    component: vpn-gateway
  name: gluetun-premiumize-ca
  namespace: vpn-gateway
