apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "1"
    deployment.kubernetes.io/revision: "1"
  labels:
    app: nginx-auth
    pod-template-hash: 9bd77d666
  name: nginx-auth-9bd77d666
  namespace: bolabaden
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: nginx-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-auth
      pod-template-hash: 9bd77d666
  template:
    metadata:
      labels:
        app: nginx-auth
        pod-template-hash: 9bd77d666
    spec:
      containers:
      - env:
        - name: PGID
          value: "988"
        - name: PUID
          value: "1002"
        - name: TZ
          value: America/Chicago
        - name: UMASK
          value: "002"
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: nginx-auth
        ports:
        - containerPort: 80
          name: nginx-auth-80
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          readOnly: true
          subPath: nginx.conf
        - mountPath: /etc/nginx/auth
          name: auth-config
          readOnly: true
        - mountPath: /var/cache/nginx
          name: cache
        - mountPath: /var/log/nginx
          name: logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /home/ubuntu/my-media-stack/configs/nginx-middlewares/nginx.conf
          type: File
        name: nginx-conf
      - hostPath:
          path: /home/ubuntu/my-media-stack/configs/nginx-middlewares/auth
          type: DirectoryOrCreate
        name: auth-config
      - hostPath:
          path: /home/ubuntu/my-media-stack/configs/nginx-middlewares/cache
          type: DirectoryOrCreate
        name: cache
      - hostPath:
          path: /home/ubuntu/my-media-stack/configs/nginx-middlewares/logs
          type: DirectoryOrCreate
        name: logs
  fullyLabeledReplicas: 1
  observedGeneration: 1
  replicas: 1
