apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "1"
    deployment.kubernetes.io/revision: "1"
  labels:
    app: tinyauth
    pod-template-hash: 844bf8849f
  name: tinyauth-844bf8849f
  namespace: bolabaden
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: tinyauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyauth
      pod-template-hash: 844bf8849f
  template:
    metadata:
      labels:
        app: tinyauth
        pod-template-hash: 844bf8849f
    spec:
      containers:
      - env:
        - name: APP_TITLE
          value: my-media-stack
        - name: APP_URL
          value: https://auth.my-media-stack.org
        - name: COOKIE_SECURE
          value: "true"
        - name: GITHUB_CLIENT_ID
          value: Ov23li1ijiBeH6cBV9bJ
        - name: GITHUB_CLIENT_SECRET
          value: 99adef0dd47be1f9fb76885b0ac6722fd9730d08
        - name: GOOGLE_CLIENT_ID
          value: 324816055390-dftm6jq2d3ifs37miivj3nj09piv0df9.apps.googleusercontent.com
        - name: GOOGLE_CLIENT_SECRET
          value: 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
        - name: LOGIN_MAX_RETRIES
          value: "5"
        - name: LOGIN_TIMEOUT
          value: "300"
        - name: OAUTH_AUTO_REDIRECT
          value: none
        - name: OAUTH_WHITELIST
        - name: SECRET
          value: b9a4ZxFNBbyR9KdTAf2kSciI5jUCQLzE
        - name: SESSION_EXPIRY
          value: "604800"
        - name: USERS
          value: brunner56:$2y$05$CEXtGy1XS4BlkTXEgSG64eSQlrGn.55Xm2HbiSgVSgO./WoVXXLAa,my-media-stack.duckdns@gmail.com:$2y$05$BbVWsqh2XkzaxvLGwd.0euD/PkkoaeFNDIhB0tTEBn4tAjGckKRzq
        image: ghcr.io/steveiliop56/tinyauth:v3
        imagePullPolicy: IfNotPresent
        name: tinyauth
        ports:
        - containerPort: 3000
          name: tinyauth-3000
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /home/ubuntu/my-media-stack/configs/tinyauth
          type: ""
        name: data
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
