apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "1"
    deployment.kubernetes.io/revision: "1"
  labels:
    app: watchtower
    pod-template-hash: 68bd74ff47
  name: watchtower-68bd74ff47
  namespace: bolabaden
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: watchtower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchtower
      pod-template-hash: 68bd74ff47
  template:
    metadata:
      labels:
        app: watchtower
        pod-template-hash: 68bd74ff47
    spec:
      containers:
      - env:
        - name: PGID
          value: "988"
        - name: PUID
          value: "1001"
        - name: TZ
          value: America/Chicago
        - name: UMASK
          value: "002"
        - name: WATCHTOWER_CLEANUP
          value: "true"
        - name: WATCHTOWER_NOTIFICATION_REPORT
          value: "true"
        - name: WATCHTOWER_NOTIFICATION_URL
        - name: WATCHTOWER_SCHEDULE
          value: 0 0 6 * * *
        image: containrrr/watchtower:latest
        imagePullPolicy: IfNotPresent
        name: watchtower
        ports:
        - containerPort: 8080
          name: watchtower-8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: var-run-docker-sock
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: var-run-docker-sock
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
