brunner56Starter:
  brunner56Starter:
    containerSecurityContext:
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
    image:
      repository: filebrowser/filebrowser
      tag: focal-20240530@sha256:458d1f3b54e9455b5cdad3c341d6853a6fdd75ac3f1120931ca3c09ac4b588de
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 250m
        memory: 1Mi
  cleanUpDns:
    containerSecurityContext:
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
    image:
      repository: filebrowser/filebrowser
      tag: focal-20240530@sha256:458d1f3b54e9455b5cdad3c341d6853a6fdd75ac3f1120931ca3c09ac4b588de
    imagePullPolicy: IfNotPresent
  podSecurityContext:
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 568
    runAsNonRoot: true
    runAsUser: 568
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  updateDns:
    containerSecurityContext:
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
    image:
      repository: filebrowser/filebrowser
      tag: focal-20240530@sha256:458d1f3b54e9455b5cdad3c341d6853a6fdd75ac3f1120931ca3c09ac4b588de
    imagePullPolicy: IfNotPresent
kubernetesClusterDomain: cluster.local
