

x-authelia-labels: &authelia-labels
  traefik.enable: "true"
  traefik.http.middlewares.authelia.forwardauth.address: "http://authelia:${AUTHELIA_PORT:-9091}/api/authz/forward-auth"  # yamllint disable-line rule:line-length
  traefik.http.middlewares.authelia.forwardauth.trustForwardHeader: "true"
  traefik.http.middlewares.authelia.forwardauth.authResponseHeaders: "Remote-User,Remote-Groups,Remote-Name,Remote-Email"  # yamllint disable-line rule:line-length
  traefik.http.services.authelia.loadbalancer.server.port: 9091

x-keycloak-labels: &keycloak-labels
  traefik.enable: "true"
  traefik.http.services.keycloak.loadbalancer.server.port: 8080

services:
  # Authelia (Lite) - Self-Hosted Single Sign-On and Two-Factor Authentication
  authelia:
    depends_on:
      redis:
        condition: service_healthy
    image: authelia/authelia
    container_name: authelia
    hostname: authelia
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    security_opt:
      - no-new-privileges:true
    networks:
      - auth-net
      - traefik_public
    ports:
      - ${AUTHELIA_PORT:-9091}:9091
    volumes:
      - ${ROOT_DIR:-.}/configs/authelia:/config
    environment:
      <<: *common-env
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/secrets/authelia_jwt_secret
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/authelia_session_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia_storage_encryption_key
      AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE: /run/secrets/authelia_storage_mysql_password
      AUTHELIA_SESSION_REDIS_PASSWORD_FILE: /run/secrets/authelia_session_redis_password
      AUTHELIA_DUO_API_SECRET_KEY_FILE: /run/secrets/authelia_duo_api_secret_key
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_encryption_key
      - authelia_storage_mysql_password
      - authelia_notifier_smtp_password
      - authelia_duo_api_secret_key
    labels:
      <<: *authelia-labels
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        <<: *authelia-labels
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak
    depends_on: 
      keycloak-db:
        condition: service_healthy
      traefik:
        condition: service_started
    container_name: keycloak
    hostname: keycloak
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    command: start-dev
    networks:
      - auth-net
      - traefik_public
    ports:
      - ${KEYCLOAK_PORT:-8075}:8080
    volumes:
      - ${ROOT_DIR:-.}/configs/keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
    environment:
      <<: *common-env
      KC_DB_URL: "jdbc:postgresql://keycloak-db:${KEYCLOAK_POSTGRES_PORT:-5431}/${KEYCLOAK_POSTGRES_DB:-keycloak}"
      KC_DB: ${KEYCLOAK_DB:-postgres}
      KC_HOSTNAME: "keycloak.${DOMAIN}"
      KC_LOG_LEVEL: ${KEYCLOAK_LOGLEVEL:-DEBUG}
      KC_PROXY: ${KEYCLOAK_PROXY:-edge}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      PROXY_ADDRESS_FORWARDING: ${KEYCLOAK_PROXY_ADDRESS_FORWARDING:-true}
    labels:
      <<: *keycloak-labels
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      placement:
        constraints: [node.role == manager]
      labels:
        <<: *keycloak-labels
    restart: unless-stopped

  keycloak-db:
    image: postgres:17.4
    container_name: keycloak-db
    hostname: keycloak-db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      <<: *common-env
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD:?KEYCLOAK_POSTGRES_PASSWORD is required}
      POSTGRES_ROOT_PASSWORD: ${KEYCLOAK_POSTGRES_ROOT_PASSWORD:?KEYCLOAK_POSTGRES_ROOT_PASSWORD is required}
    networks:
      - auth-net
    ports:
      - ${KEYCLOAK_POSTGRES_PORT:-5431}:5432
    volumes:
      - ${ROOT_DIR:-.}/configs/keycloak/db:/var/lib/postgresql/data
    labels:
      traefik.enable: "false"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
    restart: unless-stopped


# to build the secrets:
# docker secret create authelia_duo_api_secret_key <(openssl rand -base64 32) >> ${SECRETS_DIR:-./secrets}/authelia_duo_api_secret_key
# docker secret create authelia_jwt_secret <(openssl rand -base64 32) >> ${SECRETS_DIR:-./secrets}/authelia_jwt_secret
# docker secret create authelia_notifier_smtp_password <(openssl rand -base64 16) >> ${SECRETS_DIR:-./secrets}/authelia_notifier_smtp_password
# docker secret create authelia_session_secret <(openssl rand -base64 32) >> ${SECRETS_DIR:-./secrets}/authelia_session_secret
# docker secret create authelia_storage_encryption_key <(openssl rand -base64 32) >> ${SECRETS_DIR:-./secrets}/authelia_storage_encryption_key
# docker secret create authelia_storage_mysql_password <(openssl rand -base64 16) >> ${SECRETS_DIR:-./secrets}/authelia_storage_mysql_password
