apiVersion: v1
data:
  ADVERTISE_IP: https://brunner56-plex.elfhosted.com:443
  PLEX_PREFERENCE_2: FSEventLibraryPartialScanEnabled=1
  PLEX_PREFERENCE_3: FSEventLibraryUpdatesEnabled=1
  PLEX_PREFERENCE_4: TranscoderPhotoFileSizeLimitMiB=5
  PLEX_PREFERENCE_7: autoEmptyTrash=0
  PLEX_PREFERENCE_8: BackgroundTranscodeLowPriority=1
  PLEX_PREFERENCE_9: LongRunningJobThreads=1
  PLEX_PREFERENCE_10: TranscoderH264BackgroundPreset=ultrafast
  PLEX_PREFERENCE_11: RelayEnabled=0
  PLEX_PREFERENCE_12: TranscoderTempDirectory=/transcode
  PLEX_PREFERENCE_13: MinutesAllowedPaused=30
  PLEX_PREFERENCE_14: GenerateIntroMarkerBehavior=scheduled
  PLEX_PREFERENCE_15: ButlerStartHour=9
  PLEX_PREFERENCE_16: ButlerEndHour=10
  PLEX_PREFERENCE_17: ButlerTaskDeepMediaAnalysis=0
  PLEX_PREFERENCE_18: ButlerTaskUpgradeMediaAnalysis=0
  PLEX_PREFERENCE_19: MarkerSource=cloud
  PLEX_PREFERENCE_20: GenerateCreditsMarkerBehavior=never
  PLEX_PREFERENCE_21: GenerateChapterThumbBehavior=never
  PLEX_PREFERENCE_22: GenerateChapterThumbBehavior=never
  PLEX_PREFERENCE_23: GenerateIntroMarkerBehavior=never
  PLEX_PREFERENCE_24: GenerateBIFBehavior=never
  PLEX_PREFERENCE_25: GenerateAdMarkerBehavior=never
  WAIT_FOR_MOUNT_PATHS: /storage/realdebrid-zurg/__all__
  WAIT_FOR_URLS: http://zurg:9999/http/version.txt
  WAIT_FOR_VPN: "true"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ADVERTISE_IP":"https://brunner56-plex.elfhosted.com:443","PLEX_PREFERENCE_10":"TranscoderH264BackgroundPreset=ultrafast","PLEX_PREFERENCE_11":"RelayEnabled=0","PLEX_PREFERENCE_12":"TranscoderTempDirectory=/transcode","PLEX_PREFERENCE_13":"MinutesAllowedPaused=30","PLEX_PREFERENCE_14":"GenerateIntroMarkerBehavior=scheduled","PLEX_PREFERENCE_15":"ButlerStartHour=9","PLEX_PREFERENCE_16":"ButlerEndHour=10","PLEX_PREFERENCE_17":"ButlerTaskDeepMediaAnalysis=0","PLEX_PREFERENCE_18":"ButlerTaskUpgradeMediaAnalysis=0","PLEX_PREFERENCE_19":"MarkerSource=cloud","PLEX_PREFERENCE_2":"FSEventLibraryPartialScanEnabled=1","PLEX_PREFERENCE_20":"GenerateCreditsMarkerBehavior=never","PLEX_PREFERENCE_21":"GenerateChapterThumbBehavior=never","PLEX_PREFERENCE_22":"GenerateChapterThumbBehavior=never","PLEX_PREFERENCE_23":"GenerateIntroMarkerBehavior=never","PLEX_PREFERENCE_24":"GenerateBIFBehavior=never","PLEX_PREFERENCE_25":"GenerateAdMarkerBehavior=never","PLEX_PREFERENCE_3":"FSEventLibraryUpdatesEnabled=1","PLEX_PREFERENCE_4":"TranscoderPhotoFileSizeLimitMiB=5","PLEX_PREFERENCE_7":"autoEmptyTrash=0","PLEX_PREFERENCE_8":"BackgroundTranscodeLowPriority=1","PLEX_PREFERENCE_9":"LongRunningJobThreads=1","WAIT_FOR_MOUNT_PATHS":"/storage/realdebrid-zurg/__all__","WAIT_FOR_URLS":"http://zurg:9999/http/version.txt","WAIT_FOR_VPN":"true"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"brunner56","meta.helm.sh/release-namespace":"my-media-stack"},"labels":{"app.kubernetes.io/managed-by":"Helm","helm.toolkit.fluxcd.io/name":"brunner56","helm.toolkit.fluxcd.io/namespace":"my-media-stack"},"name":"plex-config","namespace":"bolabaden"}}
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  name: plex-config
  namespace: bolabaden
