kind: ConfigMap
apiVersion: v1
metadata:
  name: b2-s3cmd-restore-config
  namespace: my-media-stack
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
data:
  s3cfg: |
    [default]

    bucket_location = us-west-002

    host_base = s3.us-west-002.backblazeb2.com

    host_bucket = %(bucket)s.s3.us-west-002.backblazeb2.com
