kind: Service
apiVersion: v1
metadata:
  name: brunner56-gatus
  namespace: my-media-stack
  labels:
    app.kubernetes.io/instance: brunner56
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gatus
    app.kubernetes.io/service: brunner56-gatus
    helm.sh/chart: gatus-0.2.1
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/instance: brunner56
    app.kubernetes.io/name: gatus
  clusterIP: 10.43.109.185
  clusterIPs:
  - 10.43.109.185
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
