apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "2"
  labels:
    app.elfhosted.com/name: homer
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: homer
    pod-template-hash: 5895bd5897
  name: homer-5895bd5897
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: homer
spec:
  replicas: 0
  selector:
    matchLabels:
      app.elfhosted.com/name: homer
      pod-template-hash: 5895bd5897
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-06-12T01:11:04Z"
      labels:
        app.elfhosted.com/name: homer
        app.kubernetes.io/instance: myprecious
        app.kubernetes.io/name: homer
        pod-template-hash: 5895bd5897
    spec:
      containers:
      - image: ghcr.io/elfhosted/homer:v23.10.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: homer
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /www/assets
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: homer-config
        name: config
  observedGeneration: 2
  replicas: 0
