apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../namespaced/kube-system/addons.k3s.cattle.io/aggregated-metrics-reader.yaml
- ../../namespaced/kube-system/addons.k3s.cattle.io/auth-delegator.yaml
- ../../namespaced/kube-system/addons.k3s.cattle.io/auth-reader.yaml
- ../../namespaced/kube-system/addons.k3s.cattle.io/ccm.yaml
- ../../namespaced/kube-system/addons.k3s.cattle.io/coredns.yaml
- ../../namespaced/kube-system/addons.k3s.cattle.io/local-storage.yaml
- ../../namespaced/kube-system/addons.k3s.cattle.io/metrics-apiservice.yaml
- ../../namespaced/kube-system/addons.k3s.cattle.io/metrics-server-deployment.yaml
- ../../namespaced/kube-system/addons.k3s.cattle.io/metrics-server-service.yaml
- ../../namespaced/kube-system/addons.k3s.cattle.io/resource-reader.yaml
- ../../namespaced/kube-system/addons.k3s.cattle.io/rolebindings.yaml
- ../../namespaced/kube-system/addons.k3s.cattle.io/runtimes.yaml
- ../../namespaced/kube-system/addons.k3s.cattle.io/traefik.yaml
- ../../namespaced/kube-system/configmaps/chart-content-traefik-crd.yaml
- ../../namespaced/kube-system/configmaps/chart-content-traefik.yaml
- ../../namespaced/kube-system/configmaps/cluster-dns.yaml
- ../../namespaced/kube-system/configmaps/coredns.yaml
- ../../namespaced/kube-system/configmaps/extension-apiserver-authentication.yaml
- ../../namespaced/kube-system/configmaps/kube-apiserver-legacy-service-account-token-tracking.yaml
- ../../namespaced/kube-system/configmaps/kube-root-ca.crt.yaml
- ../../namespaced/kube-system/configmaps/local-path-config.yaml
- ../../namespaced/kube-system/controllerrevisions.apps/svclb-traefik-679a600c-689dd6f987.yaml
- ../../namespaced/kube-system/controllerrevisions.apps/svclb-traefik-679a600c-86b78b86f9.yaml
- ../../namespaced/kube-system/daemonsets.apps/svclb-traefik-679a600c.yaml
- ../../namespaced/kube-system/deployments.apps/coredns.yaml
- ../../namespaced/kube-system/deployments.apps/local-path-provisioner.yaml
- ../../namespaced/kube-system/deployments.apps/metrics-server.yaml
- ../../namespaced/kube-system/deployments.apps/traefik.yaml
- ../../namespaced/kube-system/endpoints/kube-dns.yaml
- ../../namespaced/kube-system/endpoints/metrics-server.yaml
- ../../namespaced/kube-system/endpoints/traefik.yaml
- ../../namespaced/kube-system/endpointslices.discovery.k8s.io/kube-dns-lcwr7.yaml
- ../../namespaced/kube-system/endpointslices.discovery.k8s.io/metrics-server-s5mw2.yaml
- ../../namespaced/kube-system/endpointslices.discovery.k8s.io/traefik-j29tt.yaml
- ../../namespaced/kube-system/helmchartconfigs.helm.cattle.io/pod-gateway.yaml
- ../../namespaced/kube-system/helmchartconfigs.helm.cattle.io/traefik.yaml
- ../../namespaced/kube-system/helmcharts.helm.cattle.io/traefik-crd.yaml
- ../../namespaced/kube-system/helmcharts.helm.cattle.io/traefik.yaml
- ../../namespaced/kube-system/jobs.batch/helm-install-traefik-crd.yaml
- ../../namespaced/kube-system/jobs.batch/helm-install-traefik.yaml
- ../../namespaced/kube-system/leases.coordination.k8s.io/apiserver-bxlyoszjqrqf663ec23r2ib5vm.yaml
- ../../namespaced/kube-system/leases.coordination.k8s.io/cert-manager-controller.yaml
- ../../namespaced/kube-system/persistentvolumeclaims/traefik.yaml
- ../../namespaced/kube-system/pods.metrics.k8s.io/coredns-697968c856-wbjmt.yaml
- ../../namespaced/kube-system/pods.metrics.k8s.io/local-path-provisioner-774c6665dc-rlfng.yaml
- ../../namespaced/kube-system/pods.metrics.k8s.io/metrics-server-6f4c6675d5-g6br4.yaml
- ../../namespaced/kube-system/pods.metrics.k8s.io/svclb-traefik-679a600c-gv7wq.yaml
- ../../namespaced/kube-system/pods.metrics.k8s.io/svclb-traefik-679a600c-v6nmr.yaml
- ../../namespaced/kube-system/pods.metrics.k8s.io/svclb-traefik-679a600c-xgbv6.yaml
- ../../namespaced/kube-system/pods.metrics.k8s.io/traefik-594f7cf9cc-p9m48.yaml
- ../../namespaced/kube-system/pods/coredns-697968c856-wbjmt.yaml
- ../../namespaced/kube-system/pods/local-path-provisioner-774c6665dc-rlfng.yaml
- ../../namespaced/kube-system/pods/metrics-server-6f4c6675d5-g6br4.yaml
- ../../namespaced/kube-system/pods/svclb-traefik-679a600c-gv7wq.yaml
- ../../namespaced/kube-system/pods/svclb-traefik-679a600c-v6nmr.yaml
- ../../namespaced/kube-system/pods/svclb-traefik-679a600c-xgbv6.yaml
- ../../namespaced/kube-system/pods/traefik-594f7cf9cc-p9m48.yaml
- ../../namespaced/kube-system/replicasets.apps/coredns-697968c856.yaml
- ../../namespaced/kube-system/replicasets.apps/local-path-provisioner-774c6665dc.yaml
- ../../namespaced/kube-system/replicasets.apps/metrics-server-6f4c6675d5.yaml
- ../../namespaced/kube-system/replicasets.apps/traefik-594f7cf9cc.yaml
- ../../namespaced/kube-system/replicasets.apps/traefik-c98fdf6fb.yaml
- ../../namespaced/kube-system/rolebindings.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection.yaml
- ../../namespaced/kube-system/rolebindings.rbac.authorization.k8s.io/cert-manager:leaderelection.yaml
- ../../namespaced/kube-system/rolebindings.rbac.authorization.k8s.io/k3s-cloud-controller-manager-authentication-reader.yaml
- ../../namespaced/kube-system/rolebindings.rbac.authorization.k8s.io/metrics-server-auth-reader.yaml
- ../../namespaced/kube-system/rolebindings.rbac.authorization.k8s.io/system::extension-apiserver-authentication-reader.yaml
- ../../namespaced/kube-system/rolebindings.rbac.authorization.k8s.io/system::leader-locking-kube-controller-manager.yaml
- ../../namespaced/kube-system/rolebindings.rbac.authorization.k8s.io/system::leader-locking-kube-scheduler.yaml
- ../../namespaced/kube-system/rolebindings.rbac.authorization.k8s.io/system:controller:bootstrap-signer.yaml
- ../../namespaced/kube-system/rolebindings.rbac.authorization.k8s.io/system:controller:cloud-provider.yaml
- ../../namespaced/kube-system/rolebindings.rbac.authorization.k8s.io/system:controller:token-cleaner.yaml
- ../../namespaced/kube-system/roles.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection.yaml
- ../../namespaced/kube-system/roles.rbac.authorization.k8s.io/cert-manager:leaderelection.yaml
- ../../namespaced/kube-system/roles.rbac.authorization.k8s.io/extension-apiserver-authentication-reader.yaml
- ../../namespaced/kube-system/roles.rbac.authorization.k8s.io/system::leader-locking-kube-controller-manager.yaml
- ../../namespaced/kube-system/roles.rbac.authorization.k8s.io/system::leader-locking-kube-scheduler.yaml
- ../../namespaced/kube-system/roles.rbac.authorization.k8s.io/system:controller:bootstrap-signer.yaml
- ../../namespaced/kube-system/roles.rbac.authorization.k8s.io/system:controller:cloud-provider.yaml
- ../../namespaced/kube-system/roles.rbac.authorization.k8s.io/system:controller:token-cleaner.yaml
- ../../namespaced/kube-system/secrets/baden.vpshostingservice.co.node-password.k3s.yaml
- ../../namespaced/kube-system/secrets/beatapostapita.node-password.k3s.yaml
- ../../namespaced/kube-system/secrets/chart-values-traefik-crd.yaml
- ../../namespaced/kube-system/secrets/chart-values-traefik.yaml
- ../../namespaced/kube-system/secrets/cloudserver.bolabaden.lebla512ssd.org.node-password.k3s.yaml
- ../../namespaced/kube-system/secrets/k3s-serving.yaml
- ../../namespaced/kube-system/secrets/sh.helm.release.v1.traefik-crd.v1.yaml
- ../../namespaced/kube-system/secrets/sh.helm.release.v1.traefik.v1.yaml
- ../../namespaced/kube-system/secrets/sh.helm.release.v1.traefik.v2.yaml
- ../../namespaced/kube-system/serviceaccounts/attachdetach-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/certificate-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/clusterrole-aggregation-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/coredns.yaml
- ../../namespaced/kube-system/serviceaccounts/cronjob-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/daemon-set-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/default.yaml
- ../../namespaced/kube-system/serviceaccounts/deployment-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/disruption-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/endpoint-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/endpointslice-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/endpointslicemirroring-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/ephemeral-volume-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/expand-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/generic-garbage-collector.yaml
- ../../namespaced/kube-system/serviceaccounts/helm-traefik-crd.yaml
- ../../namespaced/kube-system/serviceaccounts/helm-traefik.yaml
- ../../namespaced/kube-system/serviceaccounts/horizontal-pod-autoscaler.yaml
- ../../namespaced/kube-system/serviceaccounts/job-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/legacy-service-account-token-cleaner.yaml
- ../../namespaced/kube-system/serviceaccounts/local-path-provisioner-service-account.yaml
- ../../namespaced/kube-system/serviceaccounts/metrics-server.yaml
- ../../namespaced/kube-system/serviceaccounts/namespace-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/node-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/persistent-volume-binder.yaml
- ../../namespaced/kube-system/serviceaccounts/pod-garbage-collector.yaml
- ../../namespaced/kube-system/serviceaccounts/pv-protection-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/pvc-protection-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/replicaset-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/replication-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/resourcequota-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/root-ca-cert-publisher.yaml
- ../../namespaced/kube-system/serviceaccounts/service-account-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/statefulset-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/svclb.yaml
- ../../namespaced/kube-system/serviceaccounts/token-cleaner.yaml
- ../../namespaced/kube-system/serviceaccounts/traefik.yaml
- ../../namespaced/kube-system/serviceaccounts/ttl-after-finished-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/ttl-controller.yaml
- ../../namespaced/kube-system/serviceaccounts/validatingadmissionpolicy-status-controller.yaml
- ../../namespaced/kube-system/services/kube-dns.yaml
- ../../namespaced/kube-system/services/metrics-server.yaml
- ../../namespaced/kube-system/services/traefik.yaml
