apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-14T15:04:50Z"
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: homer
  name: homer
  namespace: default
subsets:
- addresses:
  - ip: 10.42.3.18
    nodeName: baden.vpshostingservice.co
    targetRef:
      kind: Pod
      name: homer-6d5977c66d-z7x28
      namespace: default
  ports:
  - name: http
    port: 8080
    protocol: TCP
