apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-14T22:00:50Z"
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: lidarr
  name: lidarr
  namespace: default
subsets:
- addresses:
  - ip: 10.42.0.5
    nodeName: beatapostapita
    targetRef:
      kind: Pod
      name: lidarr-77fc4cd668-5wvtl
      namespace: default
  ports:
  - name: http
    port: 8686
    protocol: TCP
