apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: plex
  name: plex
  namespace: default
subsets:
- addresses:
  - ip: 10.42.0.250
    nodeName: beatapostapita
    targetRef:
      kind: Pod
      name: plex-86c4594cd4-lvhf9
      namespace: default
  ports:
  - name: tinyproxy
    port: 8888
    protocol: TCP
  - name: speed
    port: 3002
    protocol: TCP
  - name: http
    port: 32400
    protocol: TCP
