apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: readarr
  name: readarr
  namespace: default
subsets:
- addresses:
  - ip: 10.42.0.247
    nodeName: beatapostapita
    targetRef:
      kind: Pod
      name: readarr-57f87cdf79-4hdqv
      namespace: default
  ports:
  - name: http
    port: 8787
    protocol: TCP
