apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-14T15:06:00Z"
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: riven-frontend
  name: riven-frontend
  namespace: default
subsets:
- addresses:
  - ip: 10.42.3.22
    nodeName: baden.vpshostingservice.co
    targetRef:
      kind: Pod
      name: riven-frontend-6b5dcd5f5f-gvzzn
      namespace: default
  ports:
  - name: http
    port: 3000
    protocol: TCP
