---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
  - Github:
    - abbr: GH
      href: https://github.com/bolabaden

- Portfolio:
  - bolabaden.org:
    - abbr: BO
      href: https://bolabaden.org/
  - LinkedIn:
    - abbr: LI
      href: https://www.linkedin.com/in/boden-crouch-555897193/

- Entertainment:
  - Homer:
    - abbr: HM
      href: https://homer.bolabaden.org/

- Social:
  - Reddit:
    - abbr: RE
      href: https://reddit.com/
