apiVersion: v1
kind: Pod
metadata:
  generateName: warp-pod-gateway-58c5b97d47-
  labels:
    app: warp-pod-gateway
    pod-template-hash: 58c5b97d47
  name: warp-pod-gateway-58c5b97d47-k5fpb
  namespace: bolabaden
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: warp-pod-gateway-58c5b97d47
spec:
  containers:
  - env:
    - name: WARP_SLEEP
      value: "2"
    - name: WARP_LICENSE_KEY
      value: eyJhIjoiZTRlYjNkYmViMTJiZWFhY2MxNzcwNDEyMzE3OTA0NTQiLCJ0IjoiM2ExODhhOTMtYzQwNC00Zjg5LTg4NzItOThlMDkxNjNiYzAzIiwicyI6Ill6SmpNVFl5WmpNdE9EYzROUzAwWlRrMUxUazFORFl0TWpnd1lXWXhZVEpsT1dNMiJ9
    - name: TUNNEL_TOKEN
      value: eyJhIjoiZTRlYjNkYmViMTJiZWFhY2MxNzcwNDEyMzE3OTA0NTQiLCJ0IjoiM2ExODhhOTMtYzQwNC00Zjg5LTg4NzItOThlMDkxNjNiYzAzIiwicyI6Ill6SmpNVFl5WmpNdE9EYzROUzAwWlRrMUxUazFORFl0TWpnd1lXWXhZVEpsT1dNMiJ9
    - name: WARP_ENABLE_NAT
      value: "1"
    image: caomingjun/warp:latest
    imagePullPolicy: Always
    name: warp
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/cloudflare-warp
      name: warp-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sqhqw
      readOnly: true
  - command:
    - /bin/gateway_sidecar.sh
    env:
    - name: VXLAN_ID
      value: "42"
    - name: VXLAN_IP_NETWORK
      value: 172.16.0
    - name: VXLAN_GATEWAY_FIRST_DYNAMIC_IP
      value: "10"
    - name: VPN_INTERFACE
      value: CloudflareWARP
    - name: VPN_BLOCK_OTHER_TRAFFIC
      value: "false"
    image: ghcr.io/angelnu/pod-gateway:v1.10.0
    imagePullPolicy: IfNotPresent
    name: gateway-sidecar
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 25m
        memory: 32Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: pod-gateway-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sqhqw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - /bin/gateway_init.sh
    env:
    - name: VXLAN_ID
      value: "42"
    - name: VXLAN_IP_NETWORK
      value: 172.16.0
    - name: VXLAN_GATEWAY_FIRST_DYNAMIC_IP
      value: "10"
    - name: VPN_INTERFACE
      value: CloudflareWARP
    - name: VPN_BLOCK_OTHER_TRAFFIC
      value: "false"
    image: ghcr.io/angelnu/pod-gateway:v1.10.0
    imagePullPolicy: IfNotPresent
    name: gateway-init
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: pod-gateway-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sqhqw
      readOnly: true
  nodeName: beatapostapita
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    sysctls:
    - name: net.ipv4.ip_forward
      value: "1"
    - name: net.ipv4.conf.all.src_valid_mark
      value: "1"
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /home/ubuntu/my-media-stack/configs/warp/gateway
      type: DirectoryOrCreate
    name: warp-data
  - configMap:
      defaultMode: 493
      name: pod-gateway-config
    name: pod-gateway-config
  - name: kube-api-access-sqhqw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  message: 'Pod was rejected: forbidden sysctl: "net.ipv4.conf.all.src_valid_mark"
    not allowlisted'
  phase: Failed
  qosClass: Burstable
  reason: SysctlForbidden
  startTime: "2025-06-14T22:46:13Z"
