x-common-env: &common-env
  TZ: ${TZ:-America/Chicago}
  PUID: ${PUID:-1001}
  PGID: ${PGID:-988}
  UMASK: ${UMASK:-002}

x-common-uidgid: &common-uidgid
  user: ${PUID:-1001}:${PGID:-988}

x-resource-limits: &resource-limits
  labels:
    autoheal: "true"

x-common-logging: &common-logging
  logging:
    driver: "local"
    options:
      max-file: "5"
      max-size: "10m"

x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
  labels:
    autoheal: "true"
    swarm.autoscaler: "true"

x-swarm-resource-limits: &swarm-resource-limits
  resources:
    limits:
      cpus: "0.10"
      memory: 512M

x-constraints-manager-only: &constraints-manager-only
  constraints:
    - node.role == manager

x-preferences-worker-priority: &preferences-worker-priority
  preferences:
    - spread: node.labels.worker_priority

x-gluetun-labels: &gluetun-labels
  dockupdater.disable: "true"
  traefik.enable: "true"
  # AIOStreams
  traefik.http.routers.aiostreams.service: aiostreams
  traefik.http.services.aiostreams.loadbalancer.server.port: 3000
  # Autobrr
  traefik.http.routers.autobrr.service: autobrr
  traefik.http.services.autobrr.loadbalancer.server.port: ${AUTOBRR__PORT:-7474}
  # Deluge
  traefik.http.routers.deluge.service: deluge
  traefik.http.services.deluge.loadbalancer.server.port: 8112
  # Flaresolverr
  traefik.http.routers.flaresolverr.service: flaresolverr
  traefik.http.services.flaresolverr.loadbalancer.server.port: 8191
  # Jackett
  traefik.http.routers.jackett.service: jackett
  traefik.http.services.jackett.loadbalancer.server.port: 9117
  # Prowlarr
  traefik.http.routers.prowlarr.service: prowlarr
  traefik.http.services.prowlarr.loadbalancer.server.port: 9696
  # SABnzbd
  traefik.http.routers.sabnzbd.service: sabnzbd
  traefik.http.services.sabnzbd.loadbalancer.server.port: 8080
  # Stremio
  traefik.http.routers.stremio.service: stremio
  traefik.http.services.stremio.loadbalancer.server.port: 8080
  # Transmission
  traefik.http.routers.transmission.service: transmission
  traefik.http.services.transmission.loadbalancer.server.port: 9091
  # Gluetun HTTP Control Panel
  traefik.http.services.gluetun.loadbalancer.server.port: ${GLUETUN_HTTP_CONTROL_SERVER_ADDRESS:-8000}

services:
  autobrr:
    # 🔹🔹 Autobrr 🔹🔹  # https://github.com/autobrr/autobrr
    # Modern, easy to use download automation for torrents and usenet.
    image: ghcr.io/autobrr/autobrr
    container_name: autobrr
    network_mode: service:gluetun-openvpn
    volumes:
      - ${CONFIG_PATH:-./configs}/autobrr/config:/config
      - ${CONFIG_PATH:-./configs}/autobrr/logs:/logs
      - ${DATA_PATH:-./data}:/data
    <<: [*common-logging, *resource-limits]
    environment:
      <<: *common-env
      AUTOBRR__BASE_URL: ${AUTOBRR__BASE_URL:-}
      AUTOBRR__CHECK_FOR_UPDATES: ${AUTOBRR__CHECK_FOR_UPDATES:-true}
      AUTOBRR__CUSTOM_DEFINITIONS: ${AUTOBRR__CUSTOM_DEFINITIONS:-}
      AUTOBRR__DATABASE_TYPE: ${AUTOBRR__DATABASE_TYPE:-sqlite}
      AUTOBRR__HOST: ${AUTOBRR__HOST:-0.0.0.0}
      AUTOBRR__LOG_LEVEL: ${AUTOBRR__LOG_LEVEL:-info}
      AUTOBRR__LOG_MAX_BACKUPS: ${AUTOBRR__LOG_MAX_BACKUPS:-8}
      AUTOBRR__LOG_MAX_SIZE: ${AUTOBRR__LOG_MAX_SIZE:-2}
      AUTOBRR__LOG_PATH: ${AUTOBRR__LOG_PATH:-logs/autobrr.log}
      AUTOBRR__METRICS_BASIC_AUTH_USERS: ${AUTOBRR__METRICS_BASIC_AUTH_USERS:-}
      AUTOBRR__METRICS_ENABLED: ${AUTOBRR__METRICS_ENABLED:-false}
      AUTOBRR__METRICS_HOST: ${AUTOBRR__METRICS_HOST:-0.0.0.0}
      AUTOBRR__METRICS_PORT: ${AUTOBRR__METRICS_PORT:-9092}
      AUTOBRR__OIDC_CLIENT_ID: ${AUTOBRR__OIDC_CLIENT_ID:-}
      AUTOBRR__OIDC_CLIENT_SECRET: ${AUTOBRR__OIDC_CLIENT_SECRET:-}
      AUTOBRR__OIDC_DISABLE_BUILT_IN_LOGIN: ${AUTOBRR__OIDC_DISABLE_BUILT_IN_LOGIN:-false}
      AUTOBRR__OIDC_ENABLED: ${AUTOBRR__OIDC_ENABLED:-false}
      AUTOBRR__OIDC_ISSUER: ${AUTOBRR__OIDC_ISSUER:-}
      AUTOBRR__OIDC_REDIRECT_URL: ${AUTOBRR__OIDC_REDIRECT_URL:-}
      AUTOBRR__PORT: ${AUTOBRR__PORT:-7474}
      AUTOBRR__POSTGRES_DATABASE: ${AUTOBRR__POSTGRES_DATABASE:-autobrr}
      AUTOBRR__POSTGRES_EXTRA_PARAMS: ${AUTOBRR__POSTGRES_EXTRA_PARAMS:-}
      AUTOBRR__POSTGRES_HOST: ${AUTOBRR__POSTGRES_HOST:-postgres}
      AUTOBRR__POSTGRES_PASS: ${AUTOBRR__POSTGRES_PASS:-autobrr}
      AUTOBRR__POSTGRES_PORT: ${AUTOBRR__POSTGRES_PORT:-5430}
      AUTOBRR__POSTGRES_SSLMODE: ${AUTOBRR__POSTGRES_SSLMODE:-disable}
      AUTOBRR__POSTGRES_USER: ${AUTOBRR__POSTGRES_USER:-autobrr}
      AUTOBRR__SESSION_SECRET: ${AUTOBRR__SESSION_SECRET:-}
    labels:
      homepage.group: Source Aggregator
      homepage.name: Autobrr
      homepage.icon: autobrr.png
      homepage.href: https://autobrr.${DOMAIN}
      homepage.description: Redefines download automation for torrents and Usenet
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    restart: unless-stopped

  bazarr:
    # 🔹🔹 Bazarr 🔹🔹
    image: linuxserver/bazarr
    container_name: bazarr
    hostname: bazarr
    networks:
      - infranet
    ports:
      - ${BAZARR_PORT:-6767}:6767
    volumes:
      - ${CONFIG_PATH:-./configs}/bazarr/config:/config
      - ${DATA_PATH:-./data}/media/anime:/media/anime
      - ${DATA_PATH:-./data}/media/movies:/media/movies
      - ${DATA_PATH:-./data}/media/tv:/media/tv
      - ${DATA_PATH:-./data}/downloads/bazarr:/downloads
      - ${DATA_PATH:-./data}/downloads/complete:/downloads/complete
      - ${DATA_PATH:-./data}/downloads/incomplete:/downloads/incomplete
    environment:
      <<: *common-env
    labels:
      traefik.enable: "true"
      traefik.http.services.bazarr.loadbalancer.server.port: 6767
      homepage.group: Media Management
      homepage.name: Bazarr
      homepage.icon: bazarr.png
      homepage.href: https://bazarr.${DOMAIN}/
      homepage.description: Companion application to Sonarr and Radarr for automatic subtitle downloading and management in multiple languages.
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
      labels:
        traefik.enable: "true"
        traefik.http.services.bazarr.loadbalancer.server.port: 6767
    healthcheck:
      test: curl -fs http://127.0.0.1:6767
      interval: ${BAZARR_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${BAZARR_HEALTHCHECK_TIMEOUT:-15s}
      retries: ${BAZARR_HEALTHCHECK_RETRIES:-4}
      start_period: ${BAZARR_HEALTHCHECK_START_PERIOD:-60s}
    restart: unless-stopped

  checkrr:
    # 🔹🔹 Checkrr 🔹🔹  https://github.com/aetaric/checkrr
    # Scan your library files for corrupt media and replace the files via sonarr and radarr
    image: aetaric/checkrr:3.4.0
    container_name: checkrr
    hostname: checkrr
    networks:
      - infranet
    ports:
      - ${CHECKRR_PORT:-8585}:8585
    volumes:
      #      - ${CONFIG_PATH:-./configs}/certs:/certs
      - ${CONFIG_PATH:-./configs}/checkrr/config/checkrr.db:/checkrr.db
      - ${CONFIG_PATH:-./configs}/checkrr/config/checkrr.yaml:/checkrr.yaml
      - ${CONFIG_PATH:-./configs}/checkrr/logs:/logs
      - ${DATA_PATH:-./data}/media:/media
    environment:
      <<: *common-env
      GIN_MODE: release
    labels:
      traefik.enable: "true"
      traefik.http.services.checkrr.loadbalancer.server.port: 8585
      homepage.group: System Monitoring
      homepage.name: Checkrr
      homepage.icon: checkrr.png
      homepage.href: https://checkrr.${DOMAIN}/
      homepage.description: A comprehensive system monitoring tool that checks the health and status of your various services and applications.
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
      labels:
        traefik.enable: "true"
        traefik.docker.network: infranet
        traefik.http.services.checkrr.loadbalancer.server.port: 8585
    restart: unless-stopped

  cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    container_name: cloudflare-companion
    volumes:
      - ${CONFIG_PATH:-./configs}/cloudflare-companion/logs:/logs
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
    environment:
      <<: *common-env
      # Timezone for the container - defaults to America/Chicago if not set
      TIMEZONE: ${TZ:-America/Chicago}

      # Logging Configuration
      # LOG_TYPE: Determines where logs are output - CONSOLE, FILE, or BOTH
      LOG_TYPE: ${CLOUDFLARE_COMPANION_LOG_TYPE:-BOTH}
      # LOG_LEVEL: Set the verbosity of logging - INFO, VERBOSE, or DEBUG
      LOG_LEVEL: ${CLOUDFLARE_COMPANION_LOG_LEVEL:-INFO}

      # Traefik Version - Determines how container labels are interpreted
      # Version 2 or 3 are typically used, with 3 being the latest
      TRAEFIK_VERSION: ${TRAEFIK_VERSION:-3}

      # Cloudflare Authentication
      # CF_EMAIL: Email address associated with Cloudflare account
      # Leave blank if using scoped API token
      CF_EMAIL: ${CF_EMAIL}
      # CF_TOKEN: Cloudflare API token with DNS edit permissions
      CF_TOKEN: ${CLOUDFLARE_API_TOKEN}

      # Record Type for DNS updates - typically CNAME, A, or AAAA
      RC_TYPE: ${RC_TYPE:-CNAME}

      # Domain Configuration
      # DOMAIN1: Primary domain to update DNS records for
      DOMAIN1: ${DOMAIN}
      # DOMAIN1_ZONE_ID: Cloudflare Zone ID for the primary domain
      DOMAIN1_ZONE_ID: ${CF_ZONE_ID}
      #DOMAIN2, DOMAIN2_ZONE_ID: Secondary domain and zone ID
      #DOMAIN3, DOMAIN3_ZONE_ID: Tertiary domain and zone ID
      #DOMAIN4...
      # TARGET_DOMAIN: The destination domain/IP where records will point
      TARGET_DOMAIN: ${DUCKDNS_SUBDOMAIN}.duckdns.org

      # Optional Docker Socket Configuration
      # Uncomment and modify if connecting to a remote Docker socket
      # - DOCKER_HOST=tcp://198.51.100.32:2376
      # - DOCKER_CERT_PATH=/docker-certs
      # - DOCKER_TLS_VERIFY=1

      # Optional Traefik Filtering
      # Use these to limit which containers/services are processed
      # - TRAEFIK_FILTER_LABEL=traefik.constraint
      # - TRAEFIK_FILTER=proxy-public

      # Additional optional configurations:
      # - DEFAULT_TTL: TTL for DNS records (1 = automatic, 60-86400 valid range)
      # - REFRESH_ENTRIES: Update existing records (TRUE/FALSE)
      # - DOCKER_SWARM_MODE: Enable Docker Swarm discovery (TRUE/FALSE)
    networks:
      - infranet
    restart: always

  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    network_mode: bridge
    ports:
      - ${DDNS_UPDATER_PORT:-7998}:7998
    volumes:
      - ${CONFIG_PATH:-./configs}/ddns-updater/updater/data:/updater/data
    environment:
      - CONFIG_FILEPATH=${DDNS_UPDATER_CONFIG_FILEPATH:-/updater/data/config.json}
      - PERIOD=${DDNS_UPDATER_PERIOD:-5m}
      - UPDATE_COOLDOWN_PERIOD=${DDNS_UPDATER_UPDATE_COOLDOWN_PERIOD:-5m}
      - PUBLICIP_FETCHERS=${DDNS_UPDATER_PUBLICIP_FETCHERS:-all}
      - PUBLICIP_HTTP_PROVIDERS=${DDNS_UPDATER_PUBLICIP_HTTP_PROVIDERS:-all}
      - PUBLICIPV4_HTTP_PROVIDERS=${DDNS_UPDATER_PUBLICIPV4_HTTP_PROVIDERS:-all}
      - PUBLICIPV6_HTTP_PROVIDERS=${DDNS_UPDATER_PUBLICIPV6_HTTP_PROVIDERS:-all}
      - PUBLICIP_DNS_PROVIDERS=${DDNS_UPDATER_PUBLICIP_DNS_PROVIDERS:-all}
      - PUBLICIP_DNS_TIMEOUT=${DDNS_UPDATER_PUBLICIP_DNS_TIMEOUT:-3s}
      - HTTP_TIMEOUT=${DDNS_UPDATER_HTTP_TIMEOUT:-10s}

      # Web UI
      - LISTENING_ADDRESS=0.0.0.0:7998
      - ROOT_URL=${DDNS_UPDATER_ROOT_URL:-/}

      # Backup
      - BACKUP_PERIOD=${DDNS_UPDATER_BACKUP_PERIOD:-1h} # 0 to disable
      - BACKUP_DIRECTORY=${DDNS_UPDATER_BACKUP_DIRECTORY:-/updater/data}

      # Other
      - LOG_LEVEL=${DDNS_UPDATER_LOG_LEVEL:-debug}
      - LOG_CALLER=${DDNS_UPDATER_LOG_CALLER:-hidden}
      - SHOUTRRR_ADDRESSES=${DDNS_UPDATER_SHOUTRRR_ADDRESSES:-}
    restart: unless-stopped

  decluttarr:
    # 🔹🔹 Decluttarr 🔹🔹  https://github.com/manimatter/decluttarr
    # Watches radarr, sonarr, lidarr, readarr and whisparr download queues and removes downloads if they become stalled or no longer needed.
    image: ghcr.io/manimatter/decluttarr
    container_name: decluttarr
    hostname: decluttarr
    networks:
      - infranet
    <<: *resource-limits
    environment:
      <<: *common-env
      TEST_RUN: ${DECLUTTARR_TEST_RUN:-false}
      SSL_VERIFICATION: ${DECLUTTARR_SSL_VERIFICATION:-false}
      FAILED_IMPORT_MESSAGE_PATTERNS: '["Not a Custom Format upgrade for existing", "Not an upgrade for existing"]' # TODO: add more patterns
      IGNORED_DOWNLOAD_CLIENTS: '["emulerr"]'
      LOG_LEVEL: ${DECLUTTARR_LOG_LEVEL:-VERBOSE}
      MIN_DOWNLOAD_SPEED: ${DECLUTTARR_MIN_DOWNLOAD_SPEED:-100} # 100 KB/s
      NO_STALLED_REMOVAL_QBIT_TAG: ${DECLUTTARR_NO_STALLED_REMOVAL_QBIT_TAG:-Don't Kill}
      PERMITTED_ATTEMPTS: ${DECLUTTARR_PERMITTED_ATTEMPTS:-3}
      LIDARR_KEY: ${LIDARR_API_KEY}
      LIDARR_URL: http://lidarr:${LIDARR_PORT:-8686}
      RADARR_KEY: ${RADARR_API_KEY}
      RADARR_URL: http://radarr:${RADARR_PORT:-7878}
      READARR_KEY: ${READARR_API_KEY}
      READARR_URL: http://readarr:${READARR_PORT:-8787}
      SONARR_KEY: ${SONARR_API_KEY}
      SONARR_URL: http://sonarr:${SONARR_PORT:-8989}
      WHISPARR_URL: http://whisparr:${WHISPARR_PORT:-6969}
      WHISPARR_KEY: ${WHISPARR_API_KEY}
      QBITTORRENT_URL: http://host.docker.internal:${QBITTORRENT_PORT:-8084}
      QBITTORRENT_USERNAME: ${QBITTORRENT_USERNAME:-admin}
      QBITTORRENT_PASSWORD: ${QBITTORRENT_PASSWORD:-adminadmin}
      REMOVE_FAILED: ${DECLUTTARR_REMOVE_FAILED:-false}
      REMOVE_FAILED_IMPORTS: ${DECLUTTARR_REMOVE_FAILED_IMPORTS:-true}
      REMOVE_METADATA_MISSING: ${DECLUTTARR_REMOVE_METADATA_MISSING:-false}
      REMOVE_MISSING_FILES: ${DECLUTTARR_REMOVE_MISSING_FILES:-false}
      REMOVE_ORPHANS: ${DECLUTTARR_REMOVE_ORPHANS:-true}
      REMOVE_SLOW: ${DECLUTTARR_REMOVE_SLOW:-true}
      REMOVE_STALLED: ${DECLUTTARR_REMOVE_STALLED:-true}
      REMOVE_TIMER: ${DECLUTTARR_REMOVE_TIMER:-10} # 10 seconds
      REMOVE_UNMONITORED: ${DECLUTTARR_REMOVE_UNMONITORED:-false}
      RUN_PERIODIC_RESCANS: '{
        "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 1},
        "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 1}
        }'
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    restart: unless-stopped

  deluge:
    # 🔹🔹 Deluge 🔹🔹
    depends_on:
      - gluetun-openvpn
    image: linuxserver/deluge
    container_name: deluge
    network_mode: service:gluetun-openvpn
    volumes:
      - ${DATA_PATH:-./data}/downloads:/downloads:rw
      - ${CONFIG_PATH:-./configs}/deluge:/config:rw
    <<: [*common-logging, *resource-limits]
    environment:
      <<: *common-env
      DELUGE_LOGLEVEL: ${DELUGE_LOGLEVEL:-info}
    labels:
      homepage.group: Download Clients
      homepage.name: Deluge
      homepage.icon: deluge.png
      homepage.href: https://deluge.${DOMAIN}/
      homepage.description: A lightweight, cross-platform BitTorrent client designed for downloading files efficiently and securely from the internet.
    restart: unless-stopped

  deunhealth:
    # 🔹🔹 DeUnhealth 🔹🔹
    # Restart unhealthy containers marked with `deunhealth.restart.on.unhealthy=true` label
    # Receive Docker events as stream instead of polling periodically
    # Doesn't need network! (more secure)
    # Compatible with amd64, 386, arm64, arm32v7, arm32v6, ppc64le, s390x and riscv64 CPU architectures
    # Since Docker is written in Go, the program is also written in Go and uses the official Docker Go API⁠
    # https://hub.docker.com/r/qmcgaw/deunhealth/tags  https://hub.docker.com/r/qmcgaw/deunhealth
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: none
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:z
    <<: [*common-logging, *resource-limits]
    environment:
      <<: *common-env # for TZ env var.
      DOCKER_HOST: ${DOCKER_HOST:-unix:///var/run/docker.sock} # Docker host value such as unix:///var/run/docker.sock or tcp://socket-proxy:2375 (default: unix:///var/run/docker.sock)
      LOG_LEVEL: ${DEUNHEALTH_LOG_LEVEL:-debug} # debug, info, warning, error
      HEALTH_SERVER_ADDRESS: ${DEUNHEALTH_HEALTH_SERVER_ADDRESS:-127.0.0.1:9999} # Internal health http server listening address. Nothing to do with restarting unhealthy containers.
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    restart: unless-stopped

  dozzle:
    # 🔹🔹 Dozzle 🔹🔹
    image: amir20/dozzle
    container_name: dozzle
    hostname: dozzle
    networks:
      - infranet
    ports:
      - ${DOZZLE_PORT:-9997}:8080
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:z
    <<: [*common-logging, *resource-limits]
    labels:
      traefik.enable: "true"
      traefik.http.services.dozzle.loadbalancer.server.port: 8080
      homepage.group: System Monitoring
      homepage.name: Dozzle
      homepage.icon: dozzle.png
      homepage.href: https://dozzle.${DOMAIN}/
      homepage.description: Real-time log viewer for Docker containers, providing an easy way to monitor application logs and troubleshoot issues.
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        traefik.enable: "true"
        traefik.http.services.dozzle.loadbalancer.server.port: 8080
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    restart: unless-stopped

  flaresolverr:
    # 🔹🔹 Flaresolverr 🔹🔹  # https://github.com/flaresolverr/flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr
    container_name: flaresolverr
    network_mode: service:gluetun-openvpn
    security_opt:
      - no-new-privileges:true
    <<: [*common-logging, *resource-limits]
    environment:
      <<: *common-env
      CAPTCHA_SOLVER: ${FLARESOLVERR_CAPTCHA_SOLVER:-none}
      LOG_HTML: ${FLARESOLVERR_LOG_HTML:-false}
      LOG_LEVEL: ${FLARESOLVERR_LOG_LEVEL:-info}
    labels:
      traefik.enable: "true"
      traefik.http.services.flaresolverr.loadbalancer.server.port: 8191
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    restart: unless-stopped

  gluetun-openvpn:
    # 🔹🔹 Gluetun 🔹🔹  # https://github.com/qdm12/gluetun
    # Gluetun is a VPN client that supports various VPN protocols, providing secure and private internet access for your applications.
    # use this one with arm:
    # image: ghcr.io/qdm12/gluetun-openvpn:latest@sha256:f035267182d3928d6d8351eb1b21f74dce0f97c1a521ffe4c18ce6376614806d
    image: ghcr.io/qdm12/gluetun
    container_name: gluetun-openvpn
    hostname: gluetun-openvpn
    networks:
      infranet:
        ipv4_address: ${GLUETUN_CONTAINER_IPV4_ADDR:-172.25.4.1}
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: ${DISABLE_IPV6:-1}
    ports:
      - "8009${GLUETUN_HTTP_CONTROL_SERVER_ADDRESS:-:8000}"
      - "8888${GLUETUN_HTTPPROXY_LISTENING_ADDRESS:-:8888}"
      - "8388${GLUETUN_SHADOWSOCKS_LISTENING_ADDRESS:-:8388}/tcp"
      - "8388${GLUETUN_SHADOWSOCKS_LISTENING_ADDRESS:-:8388}/udp"
      - "9999${GLUETUN_HEALTH_SERVER_ADDRESS:-:9999}/tcp"
      - "${AIOSTREAMS_PORT:-3005}:3000"
      - "${AUTOBRR__METRICS_PORT:-9092}:${AUTOBRR__METRICS_PORT:-9092}"
      - "${AUTOBRR__PORT:-7474}:${AUTOBRR__PORT:-7474}"
      - "${AUTOBRR__POSTGRES_PORT:-5430}:${AUTOBRR__POSTGRES_PORT:-5430}"
      - "${DELUGE_EXT_PORT:-58846}:58846"
      - "${DELUGE_PORT:-8112}:8112"
      - "${FLARESOLVERR_PORT:-8191}:8191"
      - "${JACKETT_PORT:-9117}:9117"
      - "${PROWLARR_PORT:-9696}:9696"
      - "${SABNZBD_PORT:-8085}:8080"
      - "${STREMIO_PORT:-8086}:8080"
      - "${TRANSMISSION_EXT_PORT:-51413}:51413"
      - "${TRANSMISSION_EXT_PORT:-51413}:51413/udp"
      - "${TRANSMISSION_PORT:-9094}:9091"
    devices:
      - "${GLUETUN_TUN_DEVICE:-/dev/net/tun}:/dev/net/tun" # https://github.com/qdm12/gluetun-wiki/blob/main/errors/tun.md
    volumes:
      - ${CONFIG_PATH:-./configs}/gluetun:/gluetun
      - ${CONFIG_PATH:-./configs}/gluetun/servers:${GLUETUN_STORAGE_FILEPATH:-/gluetun/servers}
    environment:
      <<: *common-env
      # HTTP Control Panel section references:
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/control-server.md
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md
      HTTP_CONTROL_SERVER_ADDRESS: ${GLUETUN_HTTP_CONTROL_SERVER_ADDRESS:-:8000} # Listening address for the HTTP control server
      HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH: ${GLUETUN_HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH:-} # Path to a TOML file containing authentication configuration. There is no default.
      HTTP_CONTROL_SERVER_LOG: ${GLUETUN_HTTP_CONTROL_SERVER_LOG:-on} # Enable logging of HTTP requests
      # DNS reference: https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/dns.md
      BLOCK_ADS: ${GLUETUN_BLOCK_ADS:-on} # Uses ads hostnames and IP addresses block lists for Unbound: https://github.com/qdm12/files
      BLOCK_MALICIOUS: ${GLUETUN_BLOCK_MALICIOUS:-on} # Uses malicious hostnames and IP addresses block lists for Unbound: https://github.com/qdm12/files
      BLOCK_SURVEILLANCE: ${GLUETUN_BLOCK_SURVEILLANCE:-on} # Uses surveillance hostnames and IP addresses block lists for Unbound: https://github.com/qdm12/files
      DNS_ADDRESS: ${GLUETUN_DNS_ADDRESS:-127.0.0.1} # IP address to use as DNS resolver. It defaults to localhost to use the DNS over TLS Unbound server.
      DNS_KEEP_NAMESERVER: ${GLUETUN_DNS_KEEP_NAMESERVER:-off} # Keep /etc/resolv.conf untouched. ⚠️ this will likely leak DNS traffic outside the VPN through your default container DNS. This imples DOT=off and ignores DNS_ADDRESS
      DNS_UPDATE_PERIOD: ${GLUETUN_DNS_UPDATE_PERIOD:-24h} # Period to update block lists and cryptographic files and restart Unbound. Set to 0 to deactivate updates. This does a burst of DNS over TLS requests, which may be blocked if you set BLOCK_MALICIOUS=on for example. examples: `0`, `30s`, `5m`, `24h`
      DOT_CACHING: ${GLUETUN_DOT_CACHING:-on} # Enable caching of DNS over TLS responses
      DOT_IPV6: ${GLUETUN_DOT_IPV6:-off} # DNS IPv6 resolution
      DOT_PRIVATE_ADDRESS: ${GLUETUN_DOT_PRIVATE_ADDRESS:-} # Comma separated list of CIDRs or single IP addresses Unbound won't resolve to. Note that the setting prevents DNS rebinding
      DOT_PROVIDERS: ${GLUETUN_DOT_PROVIDERS:-cloudflare} # DNS over TLS providers to use.
      DOT: ${GLUETUN_DOT:-on} # Activate DNS over TLS with Unbound. If DOT=off, Unbound won't run and therefore no file will be downloaded by the program at all. If DOT=on, after tunneling, it downloads at start (and periodically if DNS_UPDATE_PERIOD is not 0):
      UNBLOCK: ${GLUETUN_UNBLOCK:-off} # Comma separated list of domain names to leave unblocked with Unbound, e.g. `domain1.com,x.domain2.co.uk`
      # firewall references:
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/firewall.md
      # https://github.com/qdm12/gluetun-wiki/blob/main/errors/firewall.md
      # https://github.com/qdm12/gluetun-wiki/blob/main/errors/routing.md
      FIREWALL_OUTBOUND_SUBNETS: ${GLUETUN_FIREWALL_OUTBOUND_SUBNETS:-172.25.0.0/16} # Comma separated subnets that Gluetun and the containers sharing its network stack are allowed to access. This involves firewall and routing modifications.
      FIREWALL_VPN_INPUT_PORTS: ${GLUETUN_FIREWALL_VPN_INPUT_PORTS:-20027,23936,36175,42162,52065} # Comma separated list of ports that you've forwarded on airvpn's control panel.
      HEALTH_SERVER_ADDRESS: ${GLUETUN_HEALTH_SERVER_ADDRESS:-127.0.0.1:9999} # Internal health check server listening address
      HEALTH_SUCCESS_WAIT_DURATION: ${GLUETUN_HEALTH_SUCCESS_WAIT_DURATION:-5s} # Duration to wait after a success check to perform another check
      HEALTH_TARGET_ADDRESS: ${GLUETUN_HEALTH_TARGET_ADDRESS:-cloudflare.com:443} # Address to ping on every internal health check
      HEALTH_VPN_DURATION_ADDITION: ${GLUETUN_HEALTH_VPN_DURATION_ADDITION:-5s} # Additional duration to add to the wait time for each consecutive failure of the VPN
      HEALTH_VPN_DURATION_INITIAL: ${GLUETUN_HEALTH_VPN_DURATION_INITIAL:-6s} # Initial duration to wait for the VPN to be ready before restarting it
      # HTTP Proxy section references:
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/http-proxy.md
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/http-proxy.md
      HTTPPROXY_LISTENING_ADDRESS: ${GLUETUN_HTTPPROXY_LISTENING_ADDRESS:-:8888} # Internal listening address for the HTTP proxy
      HTTPPROXY_LOG: ${GLUETUN_HTTPPROXY_LOG:-off} # Logs every tunnel requests
      HTTPPROXY_PASSWORD: ${GLUETUN_HTTPPROXY_PASSWORD:-proxypassword} # Password to use to connect to the HTTP proxy
      HTTPPROXY_STEALTH: ${GLUETUN_HTTPPROXY_STEALTH:-on} # Stealth mode means HTTP proxy headers are not added to your requests
      HTTPPROXY_USER: ${GLUETUN_HTTPPROXY_USER:-proxyuser} # Username to use to connect to the HTTP proxy
      HTTPPROXY: ${GLUETUN_HTTPPROXY:-off} # Enable the internal HTTP proxy
      # OpenVPN section references:
      # https://github.com/qdm12/gluetun-wiki/blob/main/errors/openvpn.md
      OPENVPN_AUTH: ${GLUETUN_OPENVPN_AUTH:-sha256} # Specify a custom auth algorithm to use
      #      OPENVPN_CERT: ${GLUETUN_OPENVPN_CERT:-} # OpenVPN certificate content (base64 part only). More info found here: https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/openvpn-client-encrypted-key.md
      OPENVPN_CIPHERS: ${GLUETUN_OPENVPN_CIPHERS:-aes-256-gcm} # Specify a custom cipher to use. It will also set ncp-disable if using AES GCM for PIA
      #      OPENVPN_CUSTOM_CONFIG: ${GLUETUN_OPENVPN_CUSTOM_CONFIG:-} # Specify a custom OpenVPN configuration file to use for the custom VPN provider.
      #      OPENVPN_ENCRYPTED_KEY: ${GLUETUN_OPENVPN_ENCRYPTED_KEY:-} # OpenVPN encrypted key (base64 part only). More info found here: https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/openvpn-client-encrypted-key.md
      #      OPENVPN_ENDPOINT_IP: ${GLUETUN_OPENVPN_ENDPOINT_IP:-} # Specify a generally optional target VPN server IP address to use
      #      OPENVPN_ENDPOINT_PORT: ${GLUETUN_OPENVPN_ENDPOINT_PORT:-} # Specify a generally optional target VPN server port number to use
      #      OPENVPN_FLAGS: ${GLUETUN_OPENVPN_FLAGS:-} # Space delimited openvpn flags to pass to openvpn
      OPENVPN_IPV6: ${GLUETUN_OPENVPN_IPV6:-off} # Enable/disable IPv6
      #      OPENVPN_KEY_PASSPHRASE: ${GLUETUN_OPENVPN_KEY_PASSPHRASE:-} # Specify a key passphrase to decrypt an encrypted key
      #      OPENVPN_KEY: ${GLUETUN_OPENVPN_KEY:-} # OpenVPN key (base64 part only). More info found here: https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/openvpn-client-key.md
      OPENVPN_MSSFIX: ${GLUETUN_OPENVPN_MSSFIX:-0} # Set the MSS fix parameter. Set to 0 to use the defaults.
      OPENVPN_PROCESS_USER: ${GLUETUN_OPENVPN_PROCESS_USER:-root} # Specify a user to run the OpenVPN subprocess. root is default.
      OPENVPN_PROTOCOL: ${GLUETUN_OPENVPN_PROTOCOL:-tcp} # Network protocol to use, only valid for OpenVPN
      OPENVPN_ROOT: ${GLUETUN_OPENVPN_ROOT:-no} # Run OpenVPN as root
      OPENVPN_VERBOSITY: ${GLUETUN_OPENVPN_VERBOSITY:-1} # Openvpn verbosity level
      OPENVPN_VERSION: ${GLUETUN_OPENVPN_VERSION:-2.6} # Set the OpenVPN version to run
      #      PUBLICIP_API_KEY: ${GLUETUN_PUBLICIP_API_KEY:-} # Optional API token for the public IP echo service to increase rate limiting
      #      PUBLICIP_API: ${GLUETUN_PUBLICIP_API:-ipinfo} # Public IP echo service API to use or an echoip URL in the form `echoip#https://xyz`.
      #      PUBLICIP_ENABLED: ${GLUETUN_PUBLICIP_ENABLED:-on} # Check for public IP address information on VPN connection
      #      PUBLICIP_FILE: ${GLUETUN_PUBLICIP_FILE:-/gluetun/publicip.txt} # Filepath to store the public IP address assigned. This will be removed in the v4 program, instead you might want to use the control server
      SERVER_COUNTRIES: ${GLUETUN_SERVER_COUNTRIES:-Austria,Belgium,Brazil,Bulgaria,Canada,Czech Republic,Estonia,Germany,Ireland,Japan,Latvia,Netherlands,New Zealand,Norway,Romania,Serbia,Singapore,Spain,Sweden,Switzerland,United Kingdom,United States,China,Isle of Man} # List of countries to filter servers by.  # todo: add more, i gave up halfway through there were so many.
      SHADOWSOCKS_ADDRESS: ${GLUETUN_SHADOWSOCKS_ADDRESS:-:8388} # Internal listening address for Shadowsocks
      SHADOWSOCKS_CIPHER: ${GLUETUN_SHADOWSOCKS_CIPHER:-chacha20-ietf-poly1305} # AEAD Cipher to use for Shadowsocks. Choose between `chacha20-ietf-poly1305`, `aes-128-gcm`, or `aes-256-gcm`
      SHADOWSOCKS_LISTENING_ADDRESS: ${GLUETUN_SHADOWSOCKS_LISTENING_ADDRESS:-:8388} # Internal listening address for Shadowsocks
      SHADOWSOCKS_LOG: ${GLUETUN_SHADOWSOCKS_LOG:-off} # Logs every tunnel requests
      SHADOWSOCKS_PASSWORD: ${GLUETUN_SHADOWSOCKS_PASSWORD:-password} # Password to use to connect to Shadowsocks
      SHADOWSOCKS: ${GLUETUN_SHADOWSOCKS:-off} # Enable the internal Shadowsocks proxy
      STORAGE_FILEPATH: ${GLUETUN_STORAGE_FILEPATH:-/gluetun/servers/servers.json} # Path to the file that will store the VPN servers data.
      UPDATER_MIN_RATIO: ${GLUETUN_UPDATER_MIN_RATIO:-0} # Ratio of servers to be found for the update to succeed, compared to the servers already built in the program
      UPDATER_PERIOD: ${GLUETUN_UPDATER_PERIOD:-24h} # Period to update the VPN servers data in memory and to /gluetun/servers.json. Set to 0 to disable. This does a burst of DNS over TLS requests, which may be blocked if you set BLOCK_MALICIOUS=on for example.
      UPDATER_VPN_SERVICE_PROVIDERS: ${GLUETUN_UPDATER_VPN_SERVICE_PROVIDERS:-airvpn} # List of providers to update servers data for, when the updater triggers periodically. If left empty, it defaults to the current VPN provider used at start.
      VERSION_INFORMATION: ${GLUETUN_VERSION_INFORMATION:-on} # Logs a message indicating if a newer version is available once the VPN is connected
      # Port Forwarding section references:
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/port-forwarding.md
      # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/vpn-port-forwarding.md
      #VPN_PORT_FORWARDING_LISTENING_PORTS: ${GLUETUN_VPN_PORT_FORWARDING_LISTENING_PORTS:-8388} # Port redirection for the VPN server side port forwarded.
      #VPN_PORT_FORWARDING_STATUS_FILE: ${GLUETUN_VPN_PORT_FORWARDING_STATUS_FILE:-/tmp/gluetun/forwarded_port} # File path to use for writing the forwarded port obtained.
      #VPN_PORT_FORWARDING: ${GLUETUN_VPN_PORT_FORWARDING:-off} # Enable custom port forwarding code for supported providers
      VPN_SERVICE_PROVIDER: ${GLUETUN_VPN_SERVICE_PROVIDER:-airvpn} # VPN provider to use.
      VPN_TYPE: ${GLUETUN_VPN_TYPE:-openvpn} # VPN type to use, only two choices available: `openvpn` and `wireguard`
    labels:
      <<: *gluetun-labels
      homepage.group: Network
      homepage.name: Gluetun
      homepage.icon: gluetun.png
      homepage.href: https://gluetun.${DOMAIN}/
      homepage.description: VPN client that supports various VPN protocols, providing secure and private internet access for your applications.
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
      labels:
        <<: *gluetun-labels
    #    post_start:
    #      - command: /bin/bash -c "rm -rf /gluetun/servers.json" # fixes occasional startup crashloop
    restart: unless-stopped

  homepage:
    # 🔹🔹 Homepage 🔹🔹  # https://github.com/gethomepage/homepage
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    hostname: homepage
    <<: [*common-logging, *resource-limits]
    networks:
      - infranet
    ports:
      - ${HOMEPAGE_PORT:-3000}:3000
    environment:
      <<: *common-env
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS:-0.0.0.0/0,${DOMAIN},*.${DOMAIN},${DUCKDNS_SUBDOMAIN}.duckdns.org}
      HOMEPAGE_VAR_TITLE: ${HOMEPAGE_VAR_TITLE:-Homepage}
      HOMEPAGE_VAR_SEARCH_PROVIDER: ${HOMEPAGE_VAR_SEARCH_PROVIDER:-google}
      HOMEPAGE_VAR_HEADER_STYLE: ${HOMEPAGE_VAR_HEADER_STYLE:-}
      HOMEPAGE_VAR_WEATHER_CITY: ${HOMEPAGE_VAR_WEATHER_CITY:-Chicago}
      HOMEPAGE_VAR_WEATHER_LAT: ${HOMEPAGE_VAR_WEATHER_LAT:-41.8781}
      HOMEPAGE_VAR_WEATHER_LONG: ${HOMEPAGE_VAR_WEATHER_LONG:--87.6298}
      #      HOMEPAGE_VAR_WEATHER_TIME: ${HOMEPAGE_VAR_WEATHER_TIME:-}
      HOMEPAGE_VAR_WEATHER_UNIT: ${HOMEPAGE_VAR_WEATHER_UNIT:-fahrenheit}
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:z
      - ${CONFIG_PATH:-./configs}/homepage:/app/config
      - ${DATA_PATH:-./data}:/data
    labels:
      traefik.enable: "true"
      traefik.http.services.homepage.loadbalancer.server.port: 3000
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        traefik.enable: "true"
        traefik.http.services.homepage.loadbalancer.server.port: 3000
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    restart: unless-stopped

  jackett:
    # 🔹🔹 Jackett 🔹🔹
    image: linuxserver/jackett
    container_name: jackett
    <<: [*common-uidgid, *common-logging, *resource-limits]
    network_mode: service:gluetun-openvpn
    volumes:
      - ${CONFIG_PATH:-./configs}/jackett/config:/config
    environment:
      <<: *common-env
    labels:
      homepage.group: Source Aggregator
      homepage.name: Jackett Indexer
      homepage.icon: jackett.png
      homepage.href: https://jackett.${DOMAIN}/
      homepage.description: Connects your download applications with various source providers and indexers, making it easier to find and download content through your download clients.
      homepage.weight: 1
      homepage.widget.type: jackett
      homepage.widget.url: https://jackett.${DOMAIN}
      homepage.widget.key: ${JACKETT_API_KEY}
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    healthcheck:
      test: curl --fail http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab?t=indexers&apikey=${JACKETT_API_KEY} || exit 1
      interval: ${JACKETT_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${JACKETT_HEALTHCHECK_TIMEOUT:-10s}
      start_period: ${JACKETT_HEALTHCHECK_START_PERIOD:-60s}
    restart: unless-stopped

  janitorr:
    # 🔹🔹 Janitorr 🔹🔹  # https://github.com/Schaka/janitorr
    # Cleans your Radarr, Sonarr, Jellyseerr and Jellyfin before you run out of space
    image: ghcr.io/schaka/janitorr
    container_name: janitorr
    hostname: janitorr
    ports:
      - ${JANITORR_THC_PORT:-8079}:${JANITORR_THC_PORT:-8079}
      - ${JANITORR_PORT:-8978}:8978
    volumes:
      - ${CONFIG_PATH:-./configs}/janitorr/config/application.yml:/workspace/application.yml
      - ${CONFIG_PATH:-./configs}/janitorr/logs:/logs
    <<: [*resource-limits, *common-uidgid]
    environment:
      <<: *common-env
      EXCLUDE_RESOURCES: ${JANITORR_EXCLUDE_RESOURCES:-}
      HOUR_OF_DAY_END: ${JANITORR_HOUR_OF_DAY_END:-23}
      HOUR_OF_DAY_START: ${JANITORR_HOUR_OF_DAY_START:-20}
      PRUNE_VOLUMES: ${JANITORR_PRUNE_VOLUMES:-true}
      RUN_ON_STARTUP: ${JANITORR_RUN_ON_STARTUP:-true}
      SKIP_RANDOM_BACKOFF: ${JANITORR_SKIP_RANDOM_BACKOFF:-true}
      THC_PATH: /health
      THC_PORT: ${JANITORR_THC_PORT:-8079}
      TIME_BETWEEN_RUNS: ${JANITORR_TIME_BETWEEN_RUNS:-86400}
      UNUSED_TIME: ${JANITORR_UNUSED_TIME:-24h}
      DEBUG: ${JANITORR_DEBUG:-true}
    labels:
      traefik.enable: "true"
      traefik.http.services.janitorr.loadbalancer.server.port: 8978
      homepage.group: Server Management
      homepage.name: Janitorr Cleaner
      homepage.icon: janitorr.png
      homepage.href: https://janitorr.${DOMAIN}/
      homepage.description: Helps keep your server tidy by automatically removing old and unused Docker components, freeing up valuable storage space.
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
      labels:
        traefik.enable: "true"
        traefik.http.services.janitorr.loadbalancer.server.port: 8978
    restart: unless-stopped

  jellyfin:
    # 🔹🔹 Jellyfin 🔹🔹
    image: linuxserver/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    networks:
      - infranet
    ports:
      - ${JELLYFIN_PORT:-8096}:8096
      - ${JELLYFIN_PORT2:-8920}:8920
      - ${JELLYFIN_DLNA_PORT:-1901}:1900/udp
      - ${JELLYFIN_PORT3:-7359}:7359/udp
    volumes:
      - ${ROOT_DIR:-.}/data/media/anime:/media/anime
      - ${ROOT_DIR:-.}/data/media/books:/media/books
      - ${ROOT_DIR:-.}/data/media/movies:/media/movies
      - ${ROOT_DIR:-.}/data/media/music:/media/music
      - ${ROOT_DIR:-.}/data/media/music/videos:/media/music/videos
      - ${ROOT_DIR:-.}/data/media/tv:/media/tv
      - ${ROOT_DIR:-.}/data/media/xxx:/media/xxx
      - ${CONFIG_PATH:-./configs}/jellyfin/data:/data
      - ${CONFIG_PATH:-./configs}/jellyfin/cache:/cache
      - ${CONFIG_PATH:-./configs}/jellyfin/config:/config
      - ${CONFIG_PATH:-./configs}/jellyfin/transcode:/transcode
    environment:
      <<: *common-env
      JELLYFIN_PublishedServerUrl: https://jellyfin.${DOMAIN}
    labels:
      traefik.enable: "true"
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      homepage.group: Media Streaming
      homepage.name: Jellyfin Media Server
      homepage.icon: jellyfin.png
      homepage.href: https://jellyfin.${DOMAIN}/
      homepage.description: Organize and stream your movies, TV shows, and music to any device, creating your own personal media center.
    deploy:
      <<: *common-deploy
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
      labels:
        traefik.enable: "true"
        traefik.http.services.jellyfin.loadbalancer.server.port: 8096
    restart: unless-stopped

  jellyseerr:
    # 🔹🔹 Jellyseerr 🔹🔹
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    hostname: jellyseerr
    networks:
      - infranet
    ports:
      - ${JELLYSEERR_PORT:-5055}:5055
    volumes:
      - ${CONFIG_PATH:-./configs}/jellyseerr/config:/app/config
    environment:
      <<: *common-env
      LOG_LEVEL: ${LOG_LEVEL:-debug}
    labels:
      traefik.enable: "true"
      traefik.http.services.jellyseerr.loadbalancer.server.port: 5055
      homepage.group: Media Requests
      homepage.name: Jellyseerr Requests
      homepage.icon: jellyseerr.png
      homepage.href: https://jellyseerr.${DOMAIN}/
      homepage.description: Allows you and others to request new movies and TV shows to be added to your Jellyfin media server.
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
      labels:
        traefik.enable: "true"
        traefik.docker.network: traefik_public
        traefik.http.services.jellyseerr.loadbalancer.server.port: 5055
    restart: unless-stopped

  i2p:
    # 🔹🔹 I2P 🔹🔹
    # image: geti2p/i2p
    # use this one with arm:
    image: ghcr.io/purplei2p/i2pd
    container_name: i2p
    hostname: i2p
    <<: *resource-limits
    networks:
      - infranet
    ports:
      #      - "${I2P_HTTP_PROXY_PORT:-4444}:4444"   # HTTP Proxy (optional)
      #      - "${I2P_HTTPS_PROXY_PORT:-4445}:4445"   # HTTPS Proxy (optional)
      #      - "${I2P_IRC_PROXY_PORT:-6668}:6668"   # IRC Proxy (optional)
      #      - "${I2P_LAN_INTERFACE_TCP_PORT:-7652}:7652"   # LAN interface TCP
      #      - "${I2P_LAN_INTERFACE_UDP_PORT:-7653}:7653/udp"   # LAN interface UDP
      #      - "${I2P_I2CP_PROTOCOL_PORT:-7654}:7654"   # I2CP Protocol
      #      - "${I2P_SAM_BRIDGE_TCP_PORT:-7656}:7656"   # I2P SAM Bridge TCP
      #      - "${I2P_ROUTER_CONSOLE_PORT:-7657}:7657"   # Router Console
      - "${I2P_SITE_PORT:-7658}:7658" # I2P Site
      #      - "${I2P_SMTP_PROXY_PORT:-7659}:7659"   # SMTP Proxy
      #      - "${I2P_POP3_PROXY_PORT:-7660}:7660"   # POP3 Proxy
      #      - "${I2P_EXT_PORT:-7661}:${I2P_EXT_PORT:-7661}"   # I2P external port
      #      - "${I2P_I2NP_PORT:-24531}:12345"  # I2NP Protocol
      #      - "${I2P_I2NP_PORT:-24531}:12345/udp"  # I2NP Protocol UDP
    volumes:
      - "${CONFIG_PATH:-./configs}/i2p:/i2p/.i2p"
      - "${ROOT_DIR:-.}/data/downloads:/i2psnark"
    environment:
      <<: *common-env
      EXT_PORT: "${I2P_EXT_PORT:-7661}"
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: global
      placement:
        <<: *constraints-manager-only
    restart: unless-stopped

  lidarr:
    # 🔹🔹 Lidarr 🔹🔹
    image: linuxserver/lidarr
    container_name: lidarr
    hostname: lidarr
    extra_hosts:
      - host.docker.internal:172.17.0.1
    networks:
      - infranet
    ports:
      - ${LIDARR_PORT:-8686}:8686
    volumes:
      - ${DATA_PATH:-./data}/downloads/bazarr:/downloads
      - ${DATA_PATH:-./data}/downloads/complete:/downloads/complete
      - ${DATA_PATH:-./data}/downloads/incomplete:/downloads/incomplete
      - ${DATA_PATH:-./data}/media/music:/media/music
      - ${CONFIG_PATH:-./configs}/lidarr/config:/config
    <<: [*common-uidgid, *common-logging, *resource-limits]
    environment:
      <<: *common-env
    labels:
      traefik.enable: "true"
      traefik.http.services.lidarr.loadbalancer.server.port: 8686
      homepage.group: Music Management
      homepage.name: Lidarr Music
      homepage.icon: lidarr.png
      homepage.href: https://lidarr.${DOMAIN}
      homepage.description: Helps you automatically download and organize your music collection, ensuring correct metadata and album art.
      homepage.weight: 2
      homepage.widget.type: lidarr
      homepage.widget.url: https://lidarr.${DOMAIN}
      homepage.widget.key: ${LIDARR_API_KEY}
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
      labels:
        traefik.enable: "true"
        traefik.http.services.lidarr.loadbalancer.server.port: 8686
    healthcheck:
      test: curl -fs http://localhost:8686 > /dev/null || exit 1
      interval: ${LIDARR_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${LIDARR_HEALTHCHECK_TIMEOUT:-15s}
      retries: ${LIDARR_HEALTHCHECK_RETRIES:-4}
      start_period: ${LIDARR_HEALTHCHECK_START_PERIOD:-60s}
    restart: unless-stopped

  maintainerr:
    # 🔹🔹 Maintainerr 🔹🔹  https://docs.maintainerr.info/latest/Works/
    # Looks and smells like Overseerr, does the opposite. Maintenance tool for the Plex ecosystem
    depends_on:
      plex:
        condition: service_healthy
    image: ghcr.io/jorenn92/maintainerr
    container_name: maintainerr
    hostname: maintainerr
    extra_hosts:
      - host.docker.internal:172.17.0.1
    ports:
      - ${MAINTAINERR_API_PORT:-3002}:${MAINTAINERR_API_PORT:-3002}
      - ${MAINTAINERR_UI_PORT:-6246}:${MAINTAINERR_UI_PORT:-6246}
    volumes:
      - ${CONFIG_DIR:-./configs}/maintainerr/data:/opt/data
    <<: [*common-uidgid, *common-logging, *resource-limits]
    environment:
      <<: *common-env
      API_PORT: ${MAINTAINERR_API_PORT:-3002}
      DEBUG: ${MAINTAINERR_DEBUG:-true}
      NODE_ENV: ${NODE_ENV:-production}
      UI_HOSTNAME: ${MAINTAINERR_UI_HOSTNAME:-"0.0.0.0"} # "0.0.0.0" for IPv4, "::" for IPv6
      UI_PORT: ${MAINTAINERR_UI_PORT:-6246} # Default 6246.
      VERSION_TAG: ${MAINTAINERR_VERSION_TAG:-develop}
      UV_USE_IO_URING: 0 # Temporary workaround for https://github.com/libuv/libuv/pull/4141
    labels:
      traefik.enable: "true"
      traefik.http.services.maintainerr.loadbalancer.server.port: ${MAINTAINERR_PORT:-6246}
      homepage.group: Media Server Management
      homepage.name: Maintainerr
      homepage.icon: maintainerr.png
      homepage.href: https://maintainerr.${DOMAIN}
      homepage.description: A comprehensive tool for monitoring and managing your server, providing insights and tools to keep everything running smoothly.
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        traefik.enable: "true"
        traefik.http.services.maintainerr.loadbalancer.server.port: ${MAINTAINERR_PORT:-6246}
    restart: unless-stopped

  moviematch: # http://localhost:2001 or https://bolabaden.org:2001 or https://moviematch.bolabaden.org or https://bolabaden.org/moviematch
    # 🔹🔹 Moviematch 🔹🔹
    # Allows two or more people to select movies to watch on Plex.
    depends_on:
      - plex
    image: lukechannings/moviematch
    container_name: moviematch
    hostname: moviematch
    networks:
      - infranet
    ports:
      - ${MOVIEMATCH_PORT:-2001}:8000
    <<: [*common-uidgid, *resource-limits]
    environment:
      <<: *common-env
      LIBRARY_FILTER: "${MOVIEMATCH_LIBRARY_FILTER:-}"
      PLEX_TOKEN: "${PLEX_TOKEN}" # see instructions here: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
      PLEX_URL: "http://plex:${PLEX_PORT:-32400}"
    labels:
      traefik.enable: "true"
      traefik.http.services.moviematch.loadbalancer.server.port: 8000
      homepage.group: Media Streaming
      homepage.name: Moviematch
      homepage.icon: moviematch.png
      homepage.href: https://moviematch.${DOMAIN}
      homepage.description: Allows two or more people to select movies to watch on Plex.
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        traefik.enable: "true"
        traefik.http.services.moviematch.loadbalancer.server.port: 8000
      mode: replicated
      replicas: 1
      placement:
        <<: *preferences-worker-priority
    restart: unless-stopped

  overseerr:
    # 🔹🔹 Overseerr 🔹🔹
    depends_on:
      - plex
    image: linuxserver/overseerr
    container_name: overseerr
    hostname: overseerr
    networks:
      - infranet
    ports:
      - "${OVERSEERR_PORT:-5050}:5055"
    volumes:
      - ${CONFIG_PATH:-./configs}/overseerr/config:/config
    <<: [*common-uidgid, *resource-limits]
    environment:
      <<: *common-env
    labels:
      traefik.enable: "true"
      traefik.http.services.overseerr.loadbalancer.server.port: 5055
      homepage.group: Media Requests
      homepage.name: Overseerr Requests
      homepage.icon: overseerr.png
      homepage.href: https://overseerr.${DOMAIN}
      homepage.description: Allows users to request movies and TV shows, integrating with your media server for easy content management.
      homepage.weight: 3
      homepage.widget.type: overseerr
      homepage.widget.url: https://overseerr.${DOMAIN}
      homepage.widget.key: ${OVERSEERR_API_KEY}
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        traefik.enable: "true"
        traefik.http.services.overseerr.loadbalancer.server.port: 5055
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    restart: unless-stopped

  plex:
    # 🔹🔹 Plex Media Server 🔹🔹
    image: plexinc/pms-docker
    container_name: plex
    hostname: plex
    networks:
      - infranet
      - default
    ports:
      - ${PLEX_PORT:-32400}:32400/tcp
      - ${PLEX_DLNA_PORT:-1900}:1900/udp
      - ${PLEX_PORT2:-8324}:8324/tcp
      - ${PLEX_PORT3:-32410}:32410/udp
      - ${PLEX_PORT4:-32412}:32412/udp
      - ${PLEX_PORT5:-32413}:32413/udp
      - ${PLEX_PORT6:-32414}:32414/udp
      - ${PLEX_PORT7:-32469}:32469/tcp
    # Uncomment below line if you have an embedded intel GPU
    #devices:
    #  - /dev/dri:/dev/dri
    volumes:
      - "${ROOT_DIR:-.}/data/media/anime:/media/anime"
      - "${ROOT_DIR:-.}/data/media/movies:/media/movies"
      - "${ROOT_DIR:-.}/data/media/music:/media/music"
      - "${ROOT_DIR:-.}/data/media/music/videos:/media/music/videos"
      - "${ROOT_DIR:-.}/data/media/tv:/media/tv"
      - "${CONFIG_PATH:-./configs}/plex:/config"
      - "${CONFIG_PATH:-./configs}/plex/config/osx-config:/config/Library/Application Support/Plex Media Server"
    <<: *resource-limits
    environment:
      <<: *common-env
      PLEX_CLAIM: ${PLEX_CLAIM}
    labels:
      traefik.enable: "true"
      traefik.http.services.plex.loadbalancer.server.port: 32400
      homepage.group: Media Streaming
      homepage.name: Plex Media Server
      homepage.icon: plex.png
      homepage.href: https://plex.${DOMAIN}
      homepage.description: Stream your movies, TV shows, music, and photos to any device, providing a centralized media hub for all your content.
      homepage.weight: 4
      homepage.widget.type: plex
      homepage.widget.url: https://plex.${DOMAIN}
      homepage.widget.key: ${PLEX_TOKEN} # see instructions here: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
      labels:
        traefik.enable: "true"
        traefik.http.services.plex.loadbalancer.server.port: 32400
    restart: unless-stopped

  prowlarr:
    # 🔹🔹 Prowlarr 🔹🔹
    image: linuxserver/prowlarr
    container_name: prowlarr
    network_mode: service:gluetun-openvpn
    volumes:
      - ${CONFIG_PATH:-./configs}/prowlarr/config:/config
    <<: *common-logging
    environment:
      <<: *common-env
    labels:
      homepage.group: Source Aggregator
      homepage.name: Prowlarr Indexer
      homepage.icon: prowlarr.png
      homepage.href: https://prowlarr.${DOMAIN}
      homepage.description: Manages multiple torrent indexers, making it easier to find and download content through your download clients.
      homepage.weight: 1
      homepage.widget.type: prowlarr
      homepage.widget.url: https://prowlarr.${DOMAIN}
      homepage.widget.key: ${PROWLARR_API_KEY}
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    restart: unless-stopped

  qbittorrent:
    # 🔹🔹 qBittorrent 🔹🔹
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    hostname: qbittorrent
    <<: [*common-uidgid, *common-logging]
    networks:
      - infranet
    ports:
      - ${QB_WEBUI_PORT:-8084}:${QB_WEBUI_PORT:-8084}
      - ${QB_TORRENTING_PORT:-6881}:${QB_TORRENTING_PORT:-6881}
      - ${QB_TORRENTING_PORT:-6881}:${QB_TORRENTING_PORT:-6881}/udp
    volumes:
      - ${DATA_PATH:-./data}/downloads:/downloads
      - ${DATA_PATH:-./data}/downloads/incomplete:/downloads/incomplete
      - ${CONFIG_PATH:-./configs}/qbittorrent/config:/config
      - ${CONFIG_PATH:-./configs}/qbittorrent/scripts:/scripts
    environment:
      <<: *common-env
      TORRENTING_PORT: ${QB_TORRENTING_PORT:-6881}
      WEBUI_PORT: ${QB_WEBUI_PORT:-8084}
    labels:
      traefik.enable: "true"
      traefik.http.services.qbittorrent.loadbalancer.server.port: ${QB_WEBUI_PORT:-8084}
      #traefik.http.routers.qbittorrent.middlewares: qbittorrent-strip-slash,qbittorrent-stripprefix
      # https://github.com/qbittorrent/qBittorrent/issues/5693#issuecomment-552146296
      #traefik.http.middlewares.qbittorrent-stripprefix.stripPrefix.prefixes: /qbittorrent
      # https://community.traefik.io/t/middleware-to-add-the-if-needed/1895/19
      #traefik.http.middlewares.qbittorrent-strip-slash.redirectregex.regex: ^.*\/qbittorrent$$
      #traefik.http.middlewares.qbittorrent-strip-slash.redirectregex.replacement: $$1/
      #traefik.http.middlewares.qbittorrent-strip-slash.redirectregex.permanent: "false"
      homepage.group: Download Clients
      homepage.name: qBittorrent Downloader
      homepage.icon: qbittorrent.png
      homepage.href: https://qbittorrent.${DOMAIN}
      homepage.description: A user-friendly torrent client for downloading and managing files via BitTorrent, offering a clean interface and powerful features.
      homepage.weight: 2
      homepage.widget.type: qbittorrent
      homepage.widget.url: https://qbittorrent.${DOMAIN}
      homepage.widget.username: ${QBITTORRENT_USERNAME:-admin}
      homepage.widget.password: ${QBITTORRENT_PASSWORD:-adminadmin}
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        traefik.enable: "true"
        traefik.http.services.qbittorrent.loadbalancer.server.port: ${QB_WEBUI_PORT:-8084}
        #traefik.http.routers.qbittorrent.middlewares: qbittorrent-strip-slash,qbittorrent-stripprefix
        # https://github.com/qbittorrent/qBittorrent/issues/5693#issuecomment-552146296
        #traefik.http.middlewares.qbittorrent-stripprefix.stripPrefix.prefixes: /qbittorrent
        # https://community.traefik.io/t/middleware-to-add-the-if-needed/1895/19
        #traefik.http.middlewares.qbittorrent-strip-slash.redirectregex.regex: ^.*\/qbittorrent$$
        #traefik.http.middlewares.qbittorrent-strip-slash.redirectregex.replacement: $$1/
        #traefik.http.middlewares.qbittorrent-strip-slash.redirectregex.permanent: "false"
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    restart: unless-stopped

  radarr:
    # 🔹🔹 Radarr 🔹🔹
    image: linuxserver/radarr
    container_name: radarr
    hostname: ${RADARR_HOSTNAME:-radarr}
    networks:
      - infranet
    ports:
      - ${RADARR_PORT:-7878}:7878
    volumes:
      - ${DATA_PATH:-./data}/media/movies:/movies
      - ${DATA_PATH:-./data}/downloads/movies:/downloads/movies
      - ${DATA_PATH:-./data}/downloads/complete:/downloads/complete
      - ${DATA_PATH:-./data}/downloads/incomplete:/downloads/incomplete
      - ${CONFIG_PATH:-./configs}/radarr/config:/config
    <<: [*common-logging, *resource-limits]
    environment:
      <<: *common-env
    labels:
      traefik.enable: "true"
      traefik.http.services.radarr.loadbalancer.server.port: 7878
      homepage.group: Movie Management
      homepage.name: Radarr Movies
      homepage.icon: radarr.png
      homepage.href: https://radarr.${DOMAIN}
      homepage.description: Automates your movie downloads, finding and adding new releases to your collection as they become available.
      homepage.weight: 1
      homepage.widget.type: radarr
      homepage.widget.url: https://radarr.${DOMAIN}
      homepage.widget.key: ${RADARR_API_KEY}
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        traefik.enable: "true"
        traefik.http.services.radarr.loadbalancer.server.port: 7878
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    healthcheck:
      test: curl -fs http://localhost:7878 > /dev/null || exit 1
      interval: ${RADARR_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${RADARR_HEALTHCHECK_TIMEOUT:-15s}
      retries: ${RADARR_HEALTHCHECK_RETRIES:-4}
      start_period: ${RADARR_HEALTHCHECK_START_PERIOD:-60s}
    restart: unless-stopped

  readarr:
    # 🔹🔹 Readarr 🔹🔹
    image: linuxserver/readarr:develop
    container_name: readarr
    hostname: readarr
    networks:
      - infranet
    ports:
      - ${READARR_PORT:-8787}:8787
    volumes:
      - ${CONFIG_PATH:-./configs}/readarr/config:/config
      - ${DATA_PATH:-./data}/media/books:/books
      - ${DATA_PATH:-./data}/media/comics:/comics
      - ${DATA_PATH:-./data}/media/manga:/manga
      - ${DATA_PATH:-./data}/downloads:/downloads
      - ${DATA_PATH:-./data}/downloads/complete:/downloads/complete
      - ${DATA_PATH:-./data}/downloads/incomplete:/downloads/incomplete
    <<: [*common-logging, *resource-limits]
    environment:
      <<: *common-env
    labels:
      traefik.enable: "true"
      traefik.http.services.readarr.loadbalancer.server.port: 8787
      homepage.group: E-books & Comics
      homepage.name: Readarr
      homepage.icon: readarr.png
      homepage.href: https://readarr.${DOMAIN}
      homepage.description: Manages and automates the downloading of ebooks and audiobooks, ensuring your digital library is always up-to-date.
      homepage.weight: 5
      homepage.widget.type: readarr
      homepage.widget.url: https://readarr.${DOMAIN}
      homepage.widget.key: ${READARR_API_KEY}
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        traefik.enable: "true"
        traefik.http.services.readarr.loadbalancer.server.port: 8787
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    healthcheck:
      test: curl -fs http://localhost:8787 > /dev/null || exit 1
      interval: ${READARR_HEALTHCHECK_INTERVAL:-5s}
      timeout: ${READARR_HEALTHCHECK_TIMEOUT:-4s}
      retries: ${READARR_HEALTHCHECK_RETRIES:-4}
      start_period: ${READARR_HEALTHCHECK_START_PERIOD:-60s}
    restart: unless-stopped

  recyclarr:
    # 🔹🔹 Recyclarr 🔹🔹  # https://github.com/recyclarr/recyclarr
    # command-line application that will automatically synchronize recommended settings from the TRaSH guides to your Sonarr/Radarr instances.
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    hostname: recyclarr
    networks:
      - infranet
    ports:
      - ${RECYCLARR_PORT:-32888}:32888
    init: true
    volumes:
      - ${CONFIG_PATH:-./configs}/recyclarr:/config
    <<: *resource-limits
    environment:
      <<: *common-env
      TINI_SUBREAPER: "true"
      RADARR_API_KEY: ${RADARR_API_KEY}
      RADARR_BASE_URL: https://radarr:${RADARR_PORT:-7878}
      SONARR_API_KEY: ${SONARR_API_KEY}
      SONARR_BASE_URL: https://sonarr:${SONARR_PORT:-8989}
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    restart: unless-stopped

  searxng:
    # 🔹🔹 SearxNG 🔹🔹  # https://hub.docker.com/r/searxng/searxng
    # SearxNG is a privacy-respecting, hackable, open-source metasearch engine.
    image: docker.io/searxng/searxng
    container_name: searxng
    hostname: ${SEARXNG_HOSTNAME:-searxng}
    <<: [*common-logging, *resource-limits]
    networks:
      - infranet
    ports:
      - ${SEARXNG_PORT:-8077}:8080
    volumes:
      # touch ${CONFIG_PATH:-./configs}/searxng/limiter.toml
      - ${CONFIG_PATH:-./configs}/searxng:/etc/searxng
    environment:
      <<: *common-env
      SEARXNG_BASE_URL: http://searxng:${SEARXNG_PORT:-8080}
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    restart: unless-stopped

  sonarr:
    # 🔹🔹 Sonarr 🔹🔹
    # Sonarr is a PVR for Usenet and BitTorrent users. It's a sleek Web UI that integrates seamlessly with your various PVR apps.
    image: linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    networks:
      - infranet
    ports:
      - ${SONARR_PORT:-8989}:8989
    volumes:
      - ${DATA_PATH:-./data}/media/anime:/anime
      - ${DATA_PATH:-./data}/media/tv:/tv
      - ${DATA_PATH:-./data}/downloads/anime:/downloads/anime
      - ${DATA_PATH:-./data}/downloads/tv:/downloads/tv
      - ${CONFIG_PATH:-./configs}/sonarr/config:/config
    <<: [*common-logging, *resource-limits]
    environment:
      <<: *common-env
    labels:
      traefik.enable: "true"
      traefik.http.services.sonarr.loadbalancer.server.port: 8989
      homepage.group: TV Management
      homepage.name: Sonarr TV
      homepage.icon: sonarr.png
      homepage.href: https://sonarr.${DOMAIN}
      homepage.description: Manages your TV show downloads, automatically finding and adding new episodes as they air, keeping your library organized.
      homepage.weight: 0
      homepage.widget.type: sonarr
      homepage.widget.url: https://sonarr.${DOMAIN}
      homepage.widget.key: ${SONARR_API_KEY}
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        traefik.enable: "true"
        traefik.http.services.sonarr.loadbalancer.server.port: 8989
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    healthcheck:
      test: curl -fs http://localhost:8989 > /dev/null || exit 1
      interval: ${SONARR_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${SONARR_HEALTHCHECK_TIMEOUT:-15s}
      start_period: ${SONARR_HEALTHCHECK_START_PERIOD:-60s}
    restart: always

  speedtest:
    # 🔹🔹 Speedtest 🔹🔹
    image: linuxserver/speedtest-tracker
    container_name: speedtest
    hostname: speedtest
    networks:
      - infranet
    ports:
      - ${SPEEDTEST_TRACKER_PORT:-8765}:80
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${CONFIG_PATH:-./configs}/speedtest-tracker/config:/config
      - ${CERTS_PATH:-./certs}/speedtest-tracker/keys:/config/keys
    <<: *resource-limits
    environment:
      <<: *common-env
      ADMIN_EMAIL: ${SPEEDTEST_TRACKER_ADMIN_EMAIL} # Email of the initial admin user. Note: Only effective during initial setup.
      ADMIN_NAME: ${SPEEDTEST_TRACKER_ADMIN_NAME} # Name of the initial admin user. Note: Only effective during initial setup.
      ADMIN_PASSWORD: ${SPEEDTEST_TRACKER_ADMIN_PASSWORD:-b00tstr4p} # Password of the initial admin user. Note: Only effective during initial setup.
      API_RATE_LIMIT: ${SPEEDTEST_TRACKER_API_RATE_LIMIT:-60} # Number of requests per minute to the API. Default: 60
      APP_KEY: ${SPEEDTEST_TRACKER_APP_KEY} # Key used to encrypt and decrypt data. You can generate a key at https://speedtest-tracker.dev.
      APP_NAME: ${SPEEDTEST_TRACKER_APP_NAME:-Speedtest Tracker} # Used to define the application's name in the dashboard and in notifications.
      APP_TIMEZONE: ${SPEEDTEST_TRACKER_APP_TIMEZONE:-${TZ:-America/Chicago}} # Application timezone should be set if your database does not use UTC as its  timezone.
      APP_URL: ${SPEEDTEST_TRACKER_APP_URL:-} # URL used for links in emails and notifications.
      ASSET_URL: ${SPEEDTEST_TRACKER_ASSET_URL:-} # URL used for assets, needed when using a reverse proxy.
      CHART_BEGIN_AT_ZERO: ${SPEEDTEST_TRACKER_CHART_BEGIN_AT_ZERO:-true} # Begin the dashboard axis charts at zero. Default: true
      CHART_DATETIME_FORMAT: ${SPEEDTEST_TRACKER_CHART_DATETIME_FORMAT:-j/m G:i} # Set the formatting of timestamps in charts.
      CONTENT_WIDTH: ${SPEEDTEST_TRACKER_CONTENT_WIDTH:-7xl} # Width of the content section of each page. Can be set to any value found in the Filament docs. Default: 7xl
      DATETIME_FORMAT: ${SPEEDTEST_TRACKER_DATETIME_FORMAT:-j M Y, G:i:s} # Set the formatting of timestamps in tables and notifications.
      DB_CONNECTION: ${SPEEDTEST_TRACKER_DB_CONNECTION:-sqlite}
      DISPLAY_TIMEZONE: ${SPEEDTEST_TRACKER_DISPLAY_TIMEZONE:-${TZ:-America/Chicago}} # Display timestamps in your local time.
      PRUNE_RESULTS_OLDER_THAN: ${SPEEDTEST_TRACKER_PRUNE_RESULTS_OLDER_THAN:-0} # Set the value to greater than zero to prune stored results. This value should be represented in days.
      PUBLIC_DASHBOARD: ${SPEEDTEST_TRACKER_PUBLIC_DASHBOARD:-true} # Enables the public dashboard for guest (unauthenticated) users. Default: false
      SPEEDTEST_BLOCKED_SERVERS: ${SPEEDTEST_TRACKER_BLOCKED_SERVERS:-} # Comma separated list of server IDs that should not be used when running speedtests.
      SPEEDTEST_INTERFACE: ${SPEEDTEST_TRACKER_INTERFACE:-} # Set the network interface to use for the test. This need to be the network interface available inside the container
      SPEEDTEST_SCHEDULE: ${SPEEDTEST_TRACKER_SCHEDULE:-0 * * * *} # Cron expression used to run speedtests on a scheduled basis.
      SPEEDTEST_SERVERS: ${SPEEDTEST_TRACKER_SERVERS:-} # Comma separated list of server IDs to randomly use for speedtest.
      SPEEDTEST_SKIP_IPS: ${SPEEDTEST_TRACKER_SKIP_IPS:-} # A comma separated list of public IP addresses where tests will be skipped when present.
      THRESHOLD_DOWNLOAD: ${SPEEDTEST_TRACKER_THRESHOLD_DOWNLOAD:-900} # Set the Download Threshold. Note: Only effective during initial setup.
      THRESHOLD_ENABLED: ${SPEEDTEST_TRACKER_THRESHOLD_ENABLED:-true} # Enable the thresholds. Note: Only effective during initial setup.
      THRESHOLD_PING: ${SPEEDTEST_TRACKER_THRESHOLD_PING:-25} # Set the Ping Threshold. Note: Only effective during initial setup.
      THRESHOLD_UPLOAD: ${SPEEDTEST_TRACKER_THRESHOLD_UPLOAD:-900} # Set the Upload Threshold. Note: Only effective during initial setup.
    labels:
      traefik.enable: "true"
      traefik.http.services.speedtest.loadbalancer.server.port: 80
      homepage.group: Network Monitoring
      homepage.name: Speedtest
      homepage.icon: speedtest.png
      homepage.href: https://speedtest.${DOMAIN}
      homepage.description: Regularly tests your internet speed and tracks performance over time, helping you monitor your connection quality.
      homepage.widget.type: speedtest
      homepage.widget.url: https://speedtest.${DOMAIN}
      homepage.widget.fields: '["download", "upload", "ping", "speedtest"]'
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        traefik.enable: "true"
        traefik.docker.network: traefik_public
        traefik.http.services.speedtest.loadbalancer.server.port: 80
      mode: replicated
      replicas: 1
      placement:
        <<: *constraints-manager-only
    healthcheck:
      test: curl -fs http://localhost:80 > /dev/null || exit 1
      start_period: ${SPEEDTEST_TRACKER_HEALTHCHECK_START_PERIOD:-20s}
      timeout: ${SPEEDTEST_TRACKER_HEALTHCHECK_TIMEOUT:-15s}
      interval: ${SPEEDTEST_TRACKER_HEALTHCHECK_INTERVAL:-30s}
    restart: unless-stopped

  # Multiple DNS challenge provider are not supported with Traefik,
  # but you can use CNAME to handle that. For example, if you have example.org (account foo) and
  # example.com (account bar) you can create a CNAME on example.org called _acme-challenge.example.org
  # pointing to challenge.example.com. This way, you can obtain certificates for example.org with the bar account.
  traefik:
    # 🔹🔹 Traefik 🔹🔹
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    networks:
      - infranet
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - ${TRAEFIK_WEB_PORT:-80}:${TRAEFIK_WEB_PORT:-80}
      # Listen on port 443, default for HTTPS
      - ${TRAEFIK_WEBSECURE_PORT:-443}:${TRAEFIK_WEBSECURE_PORT:-443}
      # Listen on port 8099, default for the Traefik API and Dashboard
      - ${TRAEFIK_DASHBOARD_PORT:-8099}:${TRAEFIK_DASHBOARD_PORT:-8099}
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: ${DISABLE_IPV6:-1}
    volumes:
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - ${CONFIG_PATH:-./configs}/traefik/config:/config
      - ${CONFIG_PATH:-./configs}/traefik/config:/etc/traefik
      - ${CERTS_PATH:-./certs}:/certs
    #      - /etc/localtime:/etc/localtime:ro
    environment:
      <<: *common-env
      CLOUDFLARE_EMAIL: ${CLOUDFLARE_EMAIL}
      CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
      CLOUDFLARE_ZONE_API_TOKEN: ${CLOUDFLARE_ZONE_API_TOKEN}
      LETS_ENCRYPT_EMAIL: ${LETS_ENCRYPT_EMAIL} # Email address used for Letsencrypt registration.
      # CNAME are supported (and sometimes even encouraged), but there are a few cases where they can be problematic.
      # If needed, CNAME support can be disabled with the following environment variable:
      LEGO_DISABLE_CNAME_SUPPORT: ${LEGO_DISABLE_CNAME_SUPPORT:-false} # Disable CNAME support for DNS challenges. (Default: false)
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN}
      ZEROSSL_API_KEY: ${ZEROSSL_API_KEY:-} # ZeroSSL API key.
    command:
      - --accessLog=true # Enable the access log, with HTTP requests
      - --api # Enable api/dashboard. When set to true, its sub option api.dashboard is also set to true.
      - --api.dashboard=true # Enable dashboard (default: false)
      - --api.debug=false # Enable additional endpoints for debugging and profiling (default: false)
      - --api.disableDashboardAd=true # Disable the advertisement from the dashboard (default: false)
      - --api.insecure=true # Enable the API and the dashboard on the entryPoint named traefik (default: false)
      - --entrypoints.web.address=:${TRAEFIK_WEB_PORT:-80}
      - --entrypoints.web.asDefault=true # Adds this EntryPoint to the list of default EntryPoints to be used on routers that don't have any Entrypoint defined. (Default: false)
      - --entrypoints.web.http.redirections.entrypoint.scheme=https # The redirection target scheme (optional, default: https)
      - --entrypoints.web.http.redirections.entrypoint.to=websecure # The redirection target entry point.
      - --entrypoints.web.observability.accessLogs=true
      - --entrypoints.web.observability.metrics=true
      - --entrypoints.web.observability.tracing=true
      - --entrypoints.websecure.address=:${TRAEFIK_WEBSECURE_PORT:-443}
      - --entrypoints.websecure.asDefault=true # Adds this EntryPoint to the list of default EntryPoints to be used on routers that don't have any Entrypoint defined. (Default: false)
      - --entrypoints.websecure.http.tls.certResolver=myresolver
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}
      - --entrypoints.websecure.http.tls.domains[1].main=${DUCKDNS_SUBDOMAIN}.duckdns.org
      - --entrypoints.websecure.http.tls.domains[1].sans=*.${DUCKDNS_SUBDOMAIN}.duckdns.org
      - --entrypoints.websecure.http.tls=true
      - --certificatesresolvers.myresolver.acme.caServer=https://acme.zerossl.com/v2/DV90 # Let's Encrypt has a limit: 5 certs generated a week. Use staging when breaking things (specifically https://acme-staging-v02.api.letsencrypt.org/directory). see https://doc.traefik.io/traefik/https/acme/#caserver
      - --certificatesresolvers.myresolver.acme.certificatesDuration=2160 # The certificates' duration in hours, exclusively used to determine renewal dates. (Default: 2160)
      - --certificatesresolvers.myresolver.acme.dnsChallenge.provider=cloudflare
      - --certificatesresolvers.myresolver.acme.dnsChallenge=true # Use the DNS challenges instead of HTTP/TLS challenges. (Default: false)
      - --certificatesresolvers.myresolver.acme.eab.hmacEncoded=${TRAEFIK_ACME_EAB_HMAC_ENCODED} # Uncomment this line to use ZeroSSL (no rate limits) over Let's Encrypt.  # Base64 encoded HMAC key from External CA.
      - --certificatesresolvers.myresolver.acme.eab.kid=${TRAEFIK_ACME_EAB_KID} # Uncomment this line to use ZeroSSL (no rate limits) over Let's Encrypt.  # Key identifier from External CA.
      - --certificatesresolvers.myresolver.acme.email=${ACME_RESOLVER_EMAIL} # Email address used for registration.
      - --certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web
      - --certificatesresolvers.myresolver.acme.httpChallenge=true # Activate HTTP-01 Challenge. (Default: false)
      - --certificatesresolvers.myresolver.acme.storage=/certs/acme.json # Storage to use. (Default: acme.json)
      - --certificatesresolvers.myresolver.acme.tlsChallenge=true # Use the TLS-ALPN-01 challenge to generate and renew ACME certificates by provisioning a TLS certificate.  As described on the Let's Encrypt community forum, when using the TLS-ALPN-01 challenge, Traefik must be reachable by Let's Encrypt through port 443.
      - --global.checkNewVersion=true # Periodically check if a new version has been released. (Default: true)
      - --global.sendAnonymousUsage=false # Periodically send anonymous usage statistics. If the option is not specified, it will be disabled by default. (Default: false)
      - --log # Enable the Traefik log, for configurations and errors
      - --log.level=INFO # Log level. (Default: INFO)
      - --ping.terminatingStatusCode=503 # Terminating status code (Default: 503)
      - --ping=true # Enable the ping endpoint. (Default: true)
      - --providers.docker.defaultRule=Host(`${DOMAIN}`) || Host(`{{ .ContainerName }}.${DOMAIN}`) || Host(`${DUCKDNS_SUBDOMAIN}.duckdns.org`) || Host(`{{ .ContainerName }}.${DUCKDNS_SUBDOMAIN}.duckdns.org`) || Host(`${TS_HOSTNAME}.${TS_BASE_DOMAIN}`) || Host(`{{ .ContainerName }}.${TS_HOSTNAME}.${TS_BASE_DOMAIN}`) # Default rule. (Default: Host(`{{ normalize .Name }}`)
      - --providers.docker.endpoint=unix://${DOCKER_SOCK:/var/run/docker.sock} # Docker server endpoint. Can be a TCP or a Unix socket endpoint. (Default: unix:///var/run/docker.sock)
      - --providers.docker.exposedByDefault=false # Don't expose services by default, only the ones that have the label "traefik.expose=true"
      - --providers.docker=true # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.file.directory=/configs
      - --experimental.localPlugins.traefik_plugin_AdminAPI_WebUI.modulename=github.com/Miromani4/traefik-plugin-AdminAPI_WebUI
    labels:
      traefik.enable: "true"
      #  traefik.http.middlewares.admin-auth.basicauth.users: ${TRAEFIK_USERNAME:-admin}:${TRAEFIK_HASHED_PASSWORD:-$$apr1$$89eqM5Ro$$CxaFELthUKV21DpI3UTQO.}
      traefik.http.services.api@internal.loadbalancer.server.port: 8099
      homepage.group: Infrastructure
      homepage.name: Traefik
      homepage.icon: traefik
      homepage.href: https://traefik.${DOMAIN}
      homepage.description: Reverse proxy
      homepage.widget.type: traefik
      homepage.widget.url: http://traefik.${DOMAIN}
      homepage.widget.fields: '["routers", "services", "middleware"]'
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *preferences-worker-priority
      # While in Swarm Mode, Traefik uses labels found on services, not on individual containers.
      # Therefore, if you use a compose file with Swarm Mode, labels should be defined in the deploy part of your service
      # as shown:
      labels:
        traefik.enable: "true"
        #  traefik.http.middlewares.admin-auth.basicauth.users: ${TRAEFIK_USERNAME:-admin}:${TRAEFIK_HASHED_PASSWORD:-$$apr1$$89eqM5Ro$$CxaFELthUKV21DpI3UTQO.}
        traefik.http.services.api@internal.loadbalancer.server.port: 8099
        homepage.group: Infrastructure
        homepage.name: Traefik
        homepage.icon: traefik
        homepage.href: https://traefik.${DOMAIN}
        homepage.description: Reverse proxy
        homepage.widget.type: traefik
        homepage.widget.url: http://traefik.${DOMAIN}
        homepage.widget.fields: '["routers", "services", "middleware"]'
    restart: always

  transmission:
    # 🔹🔹 Transmission 🔹🔹
    depends_on:
      - gluetun-openvpn
    image: linuxserver/transmission
    container_name: transmission
    network_mode: service:gluetun-openvpn
    volumes:
      - ${CONFIG_PATH:-./configs}/transmission/data:/config
      - ${DATA_PATH:-./data}/watch:/watch
      - ${DATA_PATH:-./data}/downloads/complete:/downloads/complete
      - ${DATA_PATH:-./data}/downloads/incomplete:/downloads/incomplete
    <<: [*common-logging, *resource-limits]
    environment:
      <<: *common-env
      #      HOST_WHITELIST: ${TRANSMISSION_HOST_WHITELIST:-}
      USER: ${TRANSMISSION_USER:-admin}
      PASS: ${TRANSMISSION_PASS:-admin}
      PEERPORT: ${TRANSMISSION_PEERPORT:-51413}
      TRANSMISSION_WEB_HOME: ${TRANSMISSION_WEB_HOME:-}
    labels:
      traefik.enable: "true"
      homepage.group: BitTorrent Clients
      homepage.name: Transmission BitTorrent Client
      homepage.icon: transmission.png
      homepage.href: https://transmission.${DOMAIN}
      homepage.description: A lightweight and efficient BitTorrent client for downloading and managing torrent files, known for its simplicity and speed.
      homepage.weight: 2
      homepage.widget.type: transmission
      homepage.widget.url: https://transmission.${DOMAIN}
      homepage.widget.username: ${TRANSMISSION_USER:-admin}
      homepage.widget.password: ${TRANSMISSION_PASS:-admin}
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      mode: replicated
      replicas: 1
      placement:
        <<: *preferences-worker-priority
    restart: unless-stopped

  whisparr:
    # 🔹🔹 Whisparr 🔹🔹  https://github.com/thespad/whisparr
    # Whisparr is a fork of Sonarr for managing and downloading adult content.
    image: ghcr.io/thespad/whisparr
    container_name: whisparr
    hostname: whisparr
    networks:
      - infranet
    ports:
      - ${WHISPARR_PORT:-6969}:6969
    volumes:
      - ${CONFIG_PATH:-./configs}/whisparr/config:/config
      - ${DATA_PATH:-./data}/downloads/xxx:/downloads/xxx
      - ${DATA_PATH:-./data}/downloads/complete:/downloads/complete
      - ${DATA_PATH:-./data}/downloads/incomplete:/downloads/incomplete
      - ${DATA_PATH:-./data}/media/xxx:/xxx
    <<: [*resource-limits]
    environment:
      <<: *common-env
    labels:
      traefik.enable: "true"
      traefik.http.services.whisparr.loadbalancer.server.port: 6969
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        traefik.enable: "true"
        traefik.http.services.whisparr.loadbalancer.server.port: 6969
      mode: replicated
      replicas: 1
      placement:
        <<: *preferences-worker-priority
    healthcheck:
      test: curl -fs http://localhost:6969 > /dev/null || exit 1
      interval: ${WHISPARR_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${WHISPARR_HEALTHCHECK_TIMEOUT:-15s}
      start_period: ${WHISPARR_HEALTHCHECK_START_PERIOD:-60s}
    restart: unless-stopped

networks:
  infranet:
    #external: true  # docker network create --driver=bridge --attachable infranet
    name: infranet
    driver: bridge
    ipam:
      config:
        - subnet: ${INFRANET_SUBNET:-172.25.0.0/16}
          gateway: ${INFRANET_GATEWAY:-172.25.0.1}
          ip_range: ${INFRANET_IP_RANGE:-172.25.0.0/16}
#  meshnet:
#    external: true # docker network create --driver=macvlan --attachable --subnet=${TAILSCALE_SUBNET:-100.64.0.0/10} --gateway=${TAILSCALE_GATEWAY:-100.64.0.1} --ip-range=${TAILSCALE_IP_RANGE:-100.64.2.0/24} -o parent=tailscale0 meshnet
#    name: tailnet
#    driver: macvlan
#    driver_opts:
#      parent: ${TAILSCALE_INTERFACE_NAME:-tailscale0}
#    ipam:
#      config:
#        - subnet: ${TAILSCALE_SUBNET:-100.64.0.0/10}
#          gateway: ${TAILSCALE_GATEWAY:-100.64.0.1}
#          ip_range: ${TAILSCALE_IP_RANGE:-100.64.2.0/24}
