x-common-env: &common-env
  PGID: ${PGID:-988} # 'docker' Group ID
  PUID: ${PUID:-1001} # A non-root user ID
  TZ: ${TZ:-America/Chicago} # Your Timezone

x-resource-limits: &resource-limits
  cpu_shares: 1024 # CPU share weight (relative, 2-262144). Higher = more CPU *if competing*.
  #  mem_limit: 512m        # Max RAM usage (e.g., 64m, 1g). Exceeding = container kill.
  #  mem_reservation: 325m  # Soft RAM limit (e.g., 32m, 512m).  Best effort, not guaranteed.
  #  mem_swappiness: 30      # Swap usage (0-100). 0 = off. Higher = more swap, may slow down container.
  #memswap_limit: 1024m    # Max RAM + Swap.  Usually same as mem_limit.
  labels:
    autoheal: "true"

x-swarm-resource-limits: &swarm-resource-limits
  resources:
    limits:
      cpus: "0.10"
      memory: 1024M
    reservations:
      cpus: "0.05"
      memory: 512M

x-common-deploy: &common-deploy
  placement:
    preferences:
      - spread: node.labels.worker_priority
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
  labels:
    autoheal: "true"
    swarm.autoscaler: "true"
#  resources:
#    limits:
#      cpus: '0.10'
#      memory: 128M
#    reservations:
#      cpus: '0.10'
#      memory: 64M

x-autoindex-labels: &autoindex-labels
  traefik.enable: "true"
  traefik.http.services.autoindex.loadbalancer.server.port: 80

x-gaps-labels: &gaps-labels
  traefik.enable: "true"
  traefik.http.services.gaps.loadbalancer.server.port: 8484

x-kometa-labels: &kometa-labels
  traefik.enable: "true"
  traefik.http.services.kometa.loadbalancer.server.port: 80

x-komga-labels: &komga-labels
  traefik.enable: "true"
  traefik.http.services.komga.loadbalancer.server.port: 25600

x-qdirstat-labels: &qdirstat-labels
  traefik.enable: "true"
  traefik.http.services.qdirstat.loadbalancer.server.port: 5800

x-rsshub-labels: &rsshub-labels
  traefik.enable: "true"
  traefik.http.services.rsshub.loadbalancer.server.port: 1200

services:
  autoindex:
    # 🔹🔹 Autoindex 🔹🔹
    # Simple Directory Index
    image: dceoy/nginx-autoindex
    container_name: autoindex
    hostname: autoindex
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - traefik_public
    security_opt:
      - no-new-privileges:true
    ports:
      - ${AUTOINDEX_PORT:-8089}:80
    volumes:
      - ${ROOT_DIR:-.}/data/media:/var/lib/nginx/html:ro # Location you want to index
    environment:
      <<: *common-env
    labels:
      <<: *autoindex-labels
      homepage.group: File Management
      homepage.name: AutoIndex
      homepage.icon: autoindex.png
      homepage.href: https://autoindex.${DOMAIN}/
      homepage.description: A self-hosted file indexer and search engine, providing a simple way to browse and search your files.
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        <<: *autoindex-labels
    restart: unless-stopped

  gaps:
    # 🔹🔹 Gaps 🔹🔹
    # Finds missing movies in plex libraries
    image: housewrecker/gaps
    container_name: gaps
    hostname: gaps
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - traefik_public
    ports:
      - ${GAPS_PORT:-8484}:8484
    volumes:
      - ${ROOT_DIR:-.}/configs/gaps:/usr/data
    environment:
      <<: *common-env
    labels:
      <<: *gaps-labels
      homepage.group: Utilities
      homepage.name: Gaps
      homepage.icon: gaps.png
      homepage.href: https://gaps.${DOMAIN}/
      homepage.description: A self-hosted file manager that allows you to manage your files and folders on your server.
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        <<: *gaps-labels
    restart: unless-stopped

  kometa: # http://localhost:5004 or https://kometa.bolabaden.org or https://bolabaden.org/kometa
    # 🔹🔹 Kometa 🔹🔹
    # Complete power and control over your media libraries
    image: linuxserver/kometa
    container_name: kometa
    hostname: kometa
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - traefik_public
    ports:
      - ${KOMETA_PORT:-5004}:80
    volumes:
      - ${ROOT_DIR:-.}/configs/kometa/config:${KOMETA_CONFIG:-/config}
    environment:
      <<: *common-env
      KOMETA_COLLECTIONS_ONLY: ${KOMETA_COLLECTIONS_ONLY:-"false"} # Run only collection YAML files, skipping all other operations.
      KOMETA_CONFIG: ${KOMETA_CONFIG:-/config}/config.yml # Specify the path to the configuration YAML file for Kometa.
      KOMETA_DELETE_COLLECTIONS: ${KOMETA_DELETE_COLLECTIONS:-"false"} # Delete all collections in the library before running collections or operations.
      KOMETA_DELETE_LABELS: ${KOMETA_DELETE_LABELS:-"false"} # Remove all labels from every item in the library before running collections or operations.
      KOMETA_DIVIDER: ${KOMETA_DIVIDER:-"="} # Set the character used to divide output in the terminal.
      KOMETA_IGNORE_GHOST: ${KOMETA_IGNORE_GHOST:-"false"} # Suppress ghost logging, which shows progress during execution.
      KOMETA_IGNORE_SCHEDULES: ${KOMETA_IGNORE_SCHEDULES:-"false"} # Bypass all scheduled runs for this execution.
      KOMETA_METADATA_ONLY: ${KOMETA_METADATA_ONLY:-"false"} # Execute only metadata files, skipping all other operations.
      KOMETA_NO_COUNTDOWN: ${KOMETA_NO_COUNTDOWN:-"false"} # Disable the countdown display before the next scheduled run.
      KOMETA_NO_MISSING: ${KOMETA_NO_MISSING:-"false"} # Do not utilize the functions that handle missing movies or shows.
      KOMETA_NO_REPORT: ${KOMETA_NO_REPORT:-"false"} # Prevent saving a report after the run is completed.
      KOMETA_NO_VERIFY_SSL: ${KOMETA_NO_VERIFY_SSL:-"false"} # Disable SSL verification for network requests.
      KOMETA_OPERATIONS_ONLY: ${KOMETA_OPERATIONS_ONLY:-"false"} # Execute only library operations, skipping collections, metadata, playlists, and overlays.
      KOMETA_OVERLAYS_ONLY: ${KOMETA_OVERLAYS_ONLY:-"false"} # Run only library overlay files, skipping all other operations.
      KOMETA_PLAYLISTS_ONLY: ${KOMETA_PLAYLISTS_ONLY:-"false"} # Execute only playlist YAML files, skipping collections, overlays, and metadata.
      KOMETA_READ_ONLY_CONFIG: ${KOMETA_READ_ONLY_CONFIG:-"false"} # Run without making any changes to the configuration file.
      KOMETA_RESUME: ${KOMETA_RESUME:-""} # Resume execution from the specified collection, bypassing the scheduled time.
      KOMETA_RUN_COLLECTIONS: ${KOMETA_RUN_COLLECTIONS:-""} # Immediately perform a run for the specified collections, bypassing the scheduled time.
      KOMETA_RUN_FILES: ${KOMETA_RUN_FILES:-""} # Execute a run for the specified files, bypassing the scheduled time.
      KOMETA_RUN_LIBRARIES: ${KOMETA_RUN_LIBRARIES:-""} # Process only the specified libraries during execution.
      KOMETA_RUN: ${KOMETA_RUN:-"true"} # Trigger an immediate run of Kometa.
      KOMETA_TIMEOUT: ${KOMETA_TIMEOUT:-180} # Set the timeout duration in seconds for all non-Plex services.
      KOMETA_TIMES: ${KOMETA_TIMES:-"04:00"} # Define the time of day when Kometa should execute its tasks.
      KOMETA_WIDTH: ${KOMETA_WIDTH:-100} # Adjust the width of the terminal output.
    labels:
      <<: *kometa-labels
      homepage.group: Media Metadata
      homepage.name: Kometa Metadata
      homepage.icon: kometa.png
      homepage.href: https://kometa.${DOMAIN}/
      homepage.description: Complete power and control over your media libraries.
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        <<: *kometa-labels
    restart: unless-stopped

  komga:
    # 🔹🔹 Komga 🔹🔹
    # Komga is a web application for managing your digital comic books.
    image: gotson/komga
    container_name: komga
    hostname: komga
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - traefik_public
    ports:
      - ${KOMGA_PORT:-25600}:25600
    volumes:
      - ${ROOT_DIR:-.}/configs/komga:/config
      - ${ROOT_DIR:-.}/data/media/books:/media/books
      - ${ROOT_DIR:-.}/data/media/comics:/media/comics
      - ${ROOT_DIR:-.}/data/media/manga:/media/manga
    environment:
      <<: *common-env
    labels:
      <<: *komga-labels
      homepage.group: E-books & Comics
      homepage.name: Komga Library
      homepage.icon: komga.png
      homepage.href: https://komga.${DOMAIN}/
      homepage.description: Manages and streams your digital comics, manga, and books, providing a clean and organized reading experience.
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        <<: *komga-labels
    restart: unless-stopped

  qdirstat:
    # 🔹🔹 qDirStat 🔹🔹
    # Directory Statistics
    image: jlesage/qdirstat
    container_name: qdirstat
    hostname: qdirstat
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - traefik_public
    security_opt:
      - no-new-privileges:true
    ports:
      - ${QDIRSTAT_PORT:-5800}:5800
    volumes:
      - /volume1:/storage:ro
      - ${ROOT_DIR:-.}/configs/qdirstat/config:/config:rw
      - ${ROOT_DIR:-.}/configs/qdirstat/logs:/config/log
    environment:
      <<: *common-env
      CLEAN_TMP_DIR: ${QDIRSTAT_CLEAN_TMP_DIR:-1}
      DISPLAY_HEIGHT: ${QDIRSTAT_DISPLAY_HEIGHT:-960}
      DISPLAY_WIDTH: ${QDIRSTAT_DISPLAY_WIDTH:-1600}
      KEEP_APP_RUNNING: ${QDIRSTAT_KEEP_APP_RUNNING:-1}
      UMASK: ${UMASK_SET:-002}
      VNC_PASSWORD: ${QDIRSTAT_VNC_PASSWORD}
    labels:
      <<: *qdirstat-labels
      homepage.group: File Management
      homepage.name: QDirStat
      homepage.icon: qdirstat.png
      homepage.href: https://qdirstat.${DOMAIN}
      homepage.description: A tool for visualizing and analyzing directory structures, helping you manage your files more efficiently.
      homepage.weight: 4
      homepage.widget.type: qdirstat
      homepage.widget.url: https://qdirstat.${DOMAIN}
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        <<: *qdirstat-labels
    restart: unless-stopped

  rsshub:
    # 🔹🔹 RSSHub 🔹🔹
    # World's largest RSS network, consisting of over 5,000 global instances.
    # Delivers millions of contents aggregated from all kinds of sources
    depends_on:
      redis:
        condition: service_healthy
    image: diygod/rsshub:chromium-bundled
    container_name: rsshub
    hostname: rsshub
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - traefik_public
    ports:
      - ${RSSHUB_PORT:-1200}:1200
    environment:
      <<: *common-env
      CACHE_TYPE: ${RSSHUB_CACHE_TYPE:-redis}
      NODE_ENV: ${RSSHUB_NODE_ENV:-production}
      REDIS_URL: ${RSSHUB_REDIS_URL:-redis://redis:${REDIS_PORT:-6379}}
    labels:
      <<: *rsshub-labels
      homepage.group: RSS Feeds
      homepage.name: RSSHub
      homepage.icon: rsshub.png
      homepage.href: https://rsshub.${DOMAIN}
      homepage.description: World's largest RSS network, consisting of over 5,000 global instances.  Delivers millions of contents aggregated from all kinds of sources
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        <<: *rsshub-labels
    restart: unless-stopped
