# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

x-common-env: &common-env
  PGID: ${PGID:-988} # 'docker' Group ID
  PUID: ${PUID:-1001} # A non-root user ID
  TZ: ${TZ:-America/Chicago} # Your Timezone

x-resource-limits: &resource-limits
  cpu_shares: 1024 # CPU share weight (relative, 2-262144). Higher = more CPU *if competing*.
  #  mem_limit: 512m        # Max RAM usage (e.g., 64m, 1g). Exceeding = container kill.
  #  mem_reservation: 325m  # Soft RAM limit (e.g., 32m, 512m).  Best effort, not guaranteed.
  #  mem_swappiness: 30      # Swap usage (0-100). 0 = off. Higher = more swap, may slow down container.
  #memswap_limit: 1024m    # Max RAM + Swap.  Usually same as mem_limit.
  labels:
    autoheal: "true"

x-swarm-resource-limits: &swarm-resource-limits
  resources:
    limits:
      cpus: "0.10"
      memory: 1024M
#    reservations:
#     cpus: '0.05'
#    memory:  256M

x-common-deploy: &common-deploy
  placement:
    preferences:
      - spread: node.labels.worker_priority
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
  labels:
    autoheal: "true"
    swarm.autoscaler: "true"
#  resources:
#    limits:
#      cpus: '0.10'
#      memory: 128M
#    reservations:
#      cpus: '0.10'
#      memory: 64M

services:
  aiostreams:
    # 🔹🔹 AIOStreams 🔹🔹  # https://github.com/viren070/aiostreams
    image: ghcr.io/viren070/aiostreams
    container_name: aiostreams
    network_mode: service:gluetun
    # uncomment if you are not using torrent plugins.
    #    ports:
    #      - ${AIOSTREAMS_PORT:-3005}:3000
    environment:
      <<: *common-env
    profiles:
      - opt
    labels:
      homepage.group: Media Management
      homepage.name: Aiostreams
      homepage.icon: aiostreams.png
      homepage.href: https://aiostreams.${DOMAIN}
      homepage.description: All-in-one streaming application to consolidate and manage your media across various platforms and services.
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
    restart: unless-stopped

  stremio:
    # 🔹🔹 Stremio 🔹🔹
    # Stream Movies/TV over debrid instantly.
    depends_on:
      - gluetun
    image: tsaridas/stremio-docker
    container_name: stremio
    network_mode: service:gluetun
    # uncomment only if you are not using torrent plugins.
    #    ports:
    #      - ${STREMIO_PORT:-8086}:8080
    #      - 11470:11470
    #      - 12470:12470
    #    labels:
    #      traefik.http.services.stremio.loadbalancer.server.port: 8080
    volumes:
      - ${ROOT_DIR:-.}/configs/stremio-server:/root/.stremio-server
    environment:
      <<: *common-env
    profiles:
      - opt
    labels:
      homepage.group: Media Streaming
      homepage.name: Stremio
      homepage.icon: stremio.png
      homepage.href: https://stremio.${DOMAIN}
      homepage.description: A one-stop hub for video content aggregation, allowing you to stream movies, series, and more from various sources.
    <<: *resource-limits
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
    restart: unless-stopped
