apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"meta.helm.sh/release-name":"brunner56","meta.helm.sh/release-namespace":"bolabaden"},"labels":{"app.kubernetes.io/instance":"brunner56","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"filebrowser","app.kubernetes.io/service":"brunner56-filebrowser","app.kubernetes.io/version":"2.18.0","helm.sh/chart":"filebrowser-1.4.2","helm.toolkit.fluxcd.io/name":"brunner56","helm.toolkit.fluxcd.io/namespace":"bolabaden"},"name":"brunner56-filebrowser","namespace":"bolabaden"},"spec":{"clusterIP":"10.43.9.44","clusterIPs":["10.43.9.44"],"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http","port":8080,"targetPort":"http"}],"selector":{"app.kubernetes.io/instance":"brunner56","app.kubernetes.io/name":"filebrowser"}}}
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: bolabaden
  labels:
    app.kubernetes.io/instance: brunner56
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: filebrowser
    app.kubernetes.io/service: brunner56-filebrowser
    app.kubernetes.io/version: 2.18.0
    helm.sh/chart: filebrowser-1.4.2
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: bolabaden
  name: brunner56-filebrowser
  namespace: bolabaden
spec:
  clusterIP: 10.43.9.44
  clusterIPs:
  - 10.43.9.44
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: brunner56
    app.kubernetes.io/name: filebrowser
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
