apiVersion: metrics.k8s.io/v1beta1
containers:
- name: lb-tcp-443
  usage:
    cpu: "0"
    memory: 328Ki
- name: lb-tcp-80
  usage:
    cpu: "0"
    memory: 328Ki
- name: lb-tcp-8080
  usage:
    cpu: "0"
    memory: 336Ki
kind: PodMetrics
metadata:
  labels:
    app: svclb-traefik-679a600c
    controller-revision-hash: 86b78b86f9
    pod-template-generation: "2"
    svccontroller.k3s.cattle.io/svcname: traefik
    svccontroller.k3s.cattle.io/svcnamespace: kube-system
  name: svclb-traefik-679a600c-v6nmr
  namespace: kube-system
timestamp: "2025-06-14T23:02:00Z"
window: 15.315s
