apiVersion: metrics.k8s.io/v1beta1
containers:
- name: pod-gateway
  usage:
    cpu: 1004531n
    memory: 3600Ki
kind: PodMetrics
metadata:
  labels:
    app: pod-gateway
    component: vpn-gateway
    controller-revision-hash: 97dff69b8
    pod-template-generation: "1"
  name: pod-gateway-vt4xr
  namespace: vpn-gateway
timestamp: "2025-06-14T23:07:49Z"
window: 16.772s
