apiVersion: metrics.k8s.io/v1beta1
containers:
- name: pod-gateway
  usage:
    cpu: 669145n
    memory: 1276Ki
kind: PodMetrics
metadata:
  labels:
    app: pod-gateway
    component: vpn-gateway
    controller-revision-hash: 97dff69b8
    pod-template-generation: "1"
  name: pod-gateway-x8jrn
  namespace: vpn-gateway
timestamp: "2025-06-14T23:07:59Z"
window: 27.568s
