apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"deluge"},"name":"deluge","namespace":"default"},"spec":{"ports":[{"name":"http","port":8112,"protocol":"TCP","targetPort":8112},{"name":"daemon","port":58846,"protocol":"TCP","targetPort":58846},{"name":"gluetun","port":8999,"protocol":"TCP","targetPort":8999}],"selector":{"app.elfhosted.com/name":"deluge"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: deluge
  name: deluge
  namespace: default
spec:
  clusterIP: 10.43.5.77
  clusterIPs:
  - 10.43.5.77
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8112
    protocol: TCP
    targetPort: 8112
  - name: daemon
    port: 58846
    protocol: TCP
    targetPort: 58846
  - name: gluetun
    port: 8999
    protocol: TCP
    targetPort: 8999
  selector:
    app.elfhosted.com/name: deluge
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
