apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"ersatztv"},"name":"ersatztv","namespace":"default"},"spec":{"ports":[{"name":"http","port":8409,"protocol":"TCP","targetPort":8409}],"selector":{"app.elfhosted.com/name":"ersatztv"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: ersatztv
  name: ersatztv
  namespace: default
spec:
  clusterIP: 10.43.220.244
  clusterIPs:
  - 10.43.220.244
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8409
    protocol: TCP
    targetPort: 8409
  selector:
    app.elfhosted.com/name: ersatztv
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
