apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"jackettio"},"name":"jackettio","namespace":"default"},"spec":{"ports":[{"name":"http","port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app.elfhosted.com/name":"jackettio"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: jackettio
  name: jackettio
  namespace: default
spec:
  clusterIP: 10.43.210.136
  clusterIPs:
  - 10.43.210.136
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.elfhosted.com/name: jackettio
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
