apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"mongoexpress"},"name":"mongoexpress","namespace":"default"},"spec":{"ports":[{"name":"http","port":8081,"protocol":"TCP","targetPort":8081}],"selector":{"app.elfhosted.com/name":"mongoexpress"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: mongoexpress
  name: mongoexpress
  namespace: default
spec:
  clusterIP: 10.43.86.36
  clusterIPs:
  - 10.43.86.36
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app.elfhosted.com/name: mongoexpress
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
