apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"readarraudio"},"name":"readarraudio","namespace":"default"},"spec":{"ports":[{"name":"http","port":8787,"protocol":"TCP","targetPort":8787}],"selector":{"app.elfhosted.com/name":"readarraudio"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: readarraudio
  name: readarraudio
  namespace: default
spec:
  clusterIP: 10.43.224.56
  clusterIPs:
  - 10.43.224.56
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8787
    protocol: TCP
    targetPort: 8787
  selector:
    app.elfhosted.com/name: readarraudio
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
