apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"seafile-memcached"},"name":"seafile-memcached","namespace":"default"},"spec":{"ports":[{"name":"memcached","port":11211,"protocol":"TCP","targetPort":11211}],"selector":{"app.elfhosted.com/name":"seafile-memcached"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: seafile-memcached
  name: seafile-memcached
  namespace: default
spec:
  clusterIP: 10.43.153.196
  clusterIPs:
  - 10.43.153.196
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: memcached
    port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    app.elfhosted.com/name: seafile-memcached
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
