apiVersion: v1
data:
  LIDARR__ANALYTICS_ENABLED: "False"
  LIDARR__API_KEY: your-api-key-here
  LIDARR__APPLICATION_URL: https://lidarr.elfhosted.com
  LIDARR__BRANCH: master
  LIDARR__INSTANCE_NAME: Lidarr
  LIDARR__LOG_LEVEL: info
  LIDARR__PORT: "8686"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"LIDARR__ANALYTICS_ENABLED":"False","LIDARR__API_KEY":"your-api-key-here","LIDARR__APPLICATION_URL":"https://lidarr.elfhosted.com","LIDARR__BRANCH":"master","LIDARR__INSTANCE_NAME":"Lidarr","LIDARR__LOG_LEVEL":"info","LIDARR__PORT":"8686"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"lidarr-env","namespace":"default"}}
  name: lidarr-env
  namespace: default
