apiVersion: v1
data:
  rclone.conf: "[realdebrid-zurg]\ntype = webdav\nurl = http://zurg:9999/http\nvendor
    = other\nuser = \npass = \n\n[alldebrid]\ntype = webdav\nurl = http://alldebrid:9999\nvendor
    = other\nuser = \npass = \n\n[premiumize]\ntype = webdav\nurl = http://premiumize:8080\nvendor
    = other\nuser = \npass = "
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"rclone.conf":"[realdebrid-zurg]\ntype = webdav\nurl = http://zurg:9999/http\nvendor = other\nuser = \npass = \n\n[alldebrid]\ntype = webdav\nurl = http://alldebrid:9999\nvendor = other\nuser = \npass = \n\n[premiumize]\ntype = webdav\nurl = http://premiumize:8080\nvendor = other\nuser = \npass = "},"kind":"ConfigMap","metadata":{"annotations":{},"name":"rclonefm-config","namespace":"default"}}
  name: rclonefm-config
  namespace: default
