apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"bazarr4k"},"name":"bazarr4k","namespace":"default"},"spec":{"ports":[{"name":"http","port":6767,"protocol":"TCP","targetPort":6767}],"selector":{"app.elfhosted.com/name":"bazarr4k"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: bazarr4k
  name: bazarr4k
  namespace: default
spec:
  clusterIP: 10.43.29.222
  clusterIPs:
  - 10.43.29.222
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 6767
    protocol: TCP
    targetPort: 6767
  selector:
    app.elfhosted.com/name: bazarr4k
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
