apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"calibre"},"name":"calibre","namespace":"default"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":8080},{"name":"webserver","port":8081,"protocol":"TCP","targetPort":8081}],"selector":{"app.elfhosted.com/name":"calibre"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: calibre
  name: calibre
  namespace: default
spec:
  clusterIP: 10.43.165.84
  clusterIPs:
  - 10.43.165.84
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: webserver
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app.elfhosted.com/name: calibre
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
