apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"decypharr"},"name":"decypharr","namespace":"default"},"spec":{"ports":[{"name":"http","port":8282,"protocol":"TCP","targetPort":8282}],"selector":{"app.elfhosted.com/name":"decypharr"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: decypharr
  name: decypharr
  namespace: default
spec:
  clusterIP: 10.43.126.197
  clusterIPs:
  - 10.43.126.197
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8282
    protocol: TCP
    targetPort: 8282
  selector:
    app.elfhosted.com/name: decypharr
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
