apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"elfterm"},"name":"elfterm","namespace":"default"},"spec":{"ports":[{"name":"http","port":7681,"protocol":"TCP","targetPort":7681}],"selector":{"app.elfhosted.com/name":"elfterm"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: elfterm
  name: elfterm
  namespace: default
spec:
  clusterIP: 10.43.196.179
  clusterIPs:
  - 10.43.196.179
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 7681
    protocol: TCP
    targetPort: 7681
  selector:
    app.elfhosted.com/name: elfterm
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
