apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"emby"},"name":"emby","namespace":"default"},"spec":{"ports":[{"name":"http","port":8096,"protocol":"TCP","targetPort":8096},{"name":"https","port":8920,"protocol":"TCP","targetPort":8920}],"selector":{"app.elfhosted.com/name":"emby"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: emby
  name: emby
  namespace: default
spec:
  clusterIP: 10.43.57.221
  clusterIPs:
  - 10.43.57.221
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8096
    protocol: TCP
    targetPort: 8096
  - name: https
    port: 8920
    protocol: TCP
    targetPort: 8920
  selector:
    app.elfhosted.com/name: emby
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
