apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"jellyfin"},"name":"jellyfin","namespace":"default"},"spec":{"ports":[{"name":"http","port":8096,"protocol":"TCP","targetPort":8096}],"selector":{"app.elfhosted.com/name":"jellyfin"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: jellyfin
  name: jellyfin
  namespace: default
spec:
  clusterIP: 10.43.67.144
  clusterIPs:
  - 10.43.67.144
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8096
    protocol: TCP
    targetPort: 8096
  selector:
    app.elfhosted.com/name: jellyfin
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
