apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"lidarr"},"name":"lidarr","namespace":"default"},"spec":{"ports":[{"name":"http","port":8686,"protocol":"TCP","targetPort":8686}],"selector":{"app.elfhosted.com/name":"lidarr"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: lidarr
  name: lidarr
  namespace: default
spec:
  clusterIP: 10.43.236.163
  clusterIPs:
  - 10.43.236.163
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8686
    protocol: TCP
    targetPort: 8686
  selector:
    app.elfhosted.com/name: lidarr
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
