apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"nzbget"},"name":"nzbget","namespace":"default"},"spec":{"ports":[{"name":"http","port":6789,"protocol":"TCP","targetPort":6789}],"selector":{"app.elfhosted.com/name":"nzbget"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: nzbget
  name: nzbget
  namespace: default
spec:
  clusterIP: 10.43.7.49
  clusterIPs:
  - 10.43.7.49
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 6789
    protocol: TCP
    targetPort: 6789
  selector:
    app.elfhosted.com/name: nzbget
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
