apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"ombi"},"name":"ombi","namespace":"default"},"spec":{"ports":[{"name":"http","port":3579,"protocol":"TCP","targetPort":3579}],"selector":{"app.elfhosted.com/name":"ombi"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: ombi
  name: ombi
  namespace: default
spec:
  clusterIP: 10.43.48.85
  clusterIPs:
  - 10.43.48.85
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3579
    protocol: TCP
    targetPort: 3579
  selector:
    app.elfhosted.com/name: ombi
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
