apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"overseerr"},"name":"overseerr","namespace":"default"},"spec":{"ports":[{"name":"http","port":5055,"protocol":"TCP","targetPort":5055}],"selector":{"app.elfhosted.com/name":"overseerr"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: overseerr
  name: overseerr
  namespace: default
spec:
  clusterIP: 10.43.208.59
  clusterIPs:
  - 10.43.208.59
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 5055
    protocol: TCP
    targetPort: 5055
  selector:
    app.elfhosted.com/name: overseerr
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
