apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"pgadmin"},"name":"pgadmin","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80}],"selector":{"app.elfhosted.com/name":"pgadmin"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: pgadmin
  name: pgadmin
  namespace: default
spec:
  clusterIP: 10.43.1.116
  clusterIPs:
  - 10.43.1.116
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.elfhosted.com/name: pgadmin
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
