apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"rclonefm"},"name":"rclonefm","namespace":"default"},"spec":{"ports":[{"name":"http","port":5572,"protocol":"TCP","targetPort":5572}],"selector":{"app.elfhosted.com/name":"rclonefm"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: rclonefm
  name: rclonefm
  namespace: default
spec:
  clusterIP: 10.43.76.149
  clusterIPs:
  - 10.43.76.149
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 5572
    protocol: TCP
    targetPort: 5572
  selector:
    app.elfhosted.com/name: rclonefm
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
