apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"requestrr"},"name":"requestrr","namespace":"default"},"spec":{"ports":[{"name":"http","port":4545,"protocol":"TCP","targetPort":4545}],"selector":{"app.elfhosted.com/name":"requestrr"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: requestrr
  name: requestrr
  namespace: default
spec:
  clusterIP: 10.43.105.200
  clusterIPs:
  - 10.43.105.200
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 4545
    protocol: TCP
    targetPort: 4545
  selector:
    app.elfhosted.com/name: requestrr
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
