apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"resilio-sync"},"name":"resilio-sync","namespace":"default"},"spec":{"ports":[{"name":"http","port":8888,"protocol":"TCP","targetPort":8888}],"selector":{"app.elfhosted.com/name":"resilio-sync"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: resilio-sync
  name: resilio-sync
  namespace: default
spec:
  clusterIP: 10.43.229.168
  clusterIPs:
  - 10.43.229.168
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app.elfhosted.com/name: resilio-sync
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
