apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"riven"},"name":"riven","namespace":"default"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":8080},{"name":"backend","port":8001,"protocol":"TCP","targetPort":8001}],"selector":{"app.elfhosted.com/name":"riven"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: riven
  name: riven
  namespace: default
spec:
  clusterIP: 10.43.253.164
  clusterIPs:
  - 10.43.253.164
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: backend
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app.elfhosted.com/name: riven
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
