apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"sonarr"},"name":"sonarr","namespace":"default"},"spec":{"ports":[{"name":"http","port":8989,"protocol":"TCP","targetPort":8989}],"selector":{"app.elfhosted.com/name":"sonarr"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: sonarr
  name: sonarr
  namespace: default
spec:
  clusterIP: 10.43.92.189
  clusterIPs:
  - 10.43.92.189
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app.elfhosted.com/name: sonarr
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
