apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"myprecious","app.kubernetes.io/name":"notifiarr"},"name":"notifiarr","namespace":"default"},"spec":{"ports":[{"name":"http","port":5454,"protocol":"TCP","targetPort":5454}],"selector":{"app.elfhosted.com/name":"notifiarr"},"type":"ClusterIP"}}
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: notifiarr
  name: notifiarr
  namespace: default
spec:
  clusterIP: 10.43.20.156
  clusterIPs:
  - 10.43.20.156
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 5454
    protocol: TCP
    targetPort: 5454
  selector:
    app.elfhosted.com/name: notifiarr
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
