{{- if .Values.vpnConfigs.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vpn-configs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "vpn-gateway.name" . }}
    helm.sh/chart: {{ include "vpn-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $key, $value := .Values.vpnConfigs.data }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end }}
{{- end -}} 