apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: gatus
  name: gatus
  namespace: default
subsets:
- addresses:
  - ip: 10.42.0.42
    nodeName: beatapostapita
    targetRef:
      kind: Pod
      name: gatus-66789cb9c-2dcvs
      namespace: default
  ports:
  - name: http
    port: 8080
    protocol: TCP
