apiVersion: v1
kind: Pod
metadata:
  generateName: code-dev-d466fffc8-
  labels:
    app: code-dev
    pod-template-hash: d466fffc8
  name: code-dev-d466fffc8-766nn
  namespace: bolabaden
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: code-dev-d466fffc8
spec:
  containers:
  - env:
    - name: CODESERVER_PASSWORD
      value: ubuntu
    - name: CODESERVER_SUDO_PASSWORD
      value: h4L0m4St3R327
    - name: DEFAULT_WORKSPACE
      value: /workspace
    - name: PGID
      value: "988"
    - name: PUID
      value: "1001"
    - name: TZ
      value: America/Chicago
    - name: UMASK
      value: "002"
    image: linuxserver/code-server:latest
    imagePullPolicy: IfNotPresent
    name: code-dev
    ports:
    - containerPort: 8443
      name: code-dev-8443
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: config
    - mountPath: /workspace
      name: workspace
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tggl7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: beatapostapita
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /home/ubuntu/my-media-stack/configs/code-server/dev/config
      type: ""
    name: config
  - hostPath:
      path: /home/ubuntu/my-media-stack
      type: ""
    name: workspace
  - name: kube-api-access-tggl7
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:38:54Z"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:38:52Z"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:38:54Z"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:38:54Z"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:38:48Z"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://a1bfb79bd274f6368f78dfa61e5563163826a47b23d62e5c17cab9a1dd20749c
    image: docker.io/linuxserver/code-server:latest
    imageID: docker.io/linuxserver/code-server@sha256:d7f2668cc91adc8a2826be20a1e2d7782d1484c037725f827bb888d040cd9f68
    lastState: {}
    name: code-dev
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-06-14T22:38:53Z"
    volumeMounts:
    - mountPath: /config
      name: config
    - mountPath: /workspace
      name: workspace
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tggl7
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.0.0.81
  hostIPs:
  - ip: 10.0.0.81
  phase: Running
  podIP: 10.42.0.84
  podIPs:
  - ip: 10.42.0.84
  qosClass: Burstable
  startTime: "2025-06-14T22:38:52Z"
