apiVersion: v1
kind: Pod
metadata:
  generateName: comet-5bb864868d-
  labels:
    app: comet
    pod-template-hash: 5bb864868d
  name: comet-5bb864868d-jlm79
  namespace: bolabaden
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: comet-5bb864868d
spec:
  containers:
  - env:
    - name: TZ
      value: America/Chicago
    - name: ADDON_ID
      value: comet.bolabaden.org
    - name: ADDON_NAME
      value: Comet
    - name: FASTAPI_HOST
      value: 0.0.0.0
    - name: FASTAPI_PORT
      value: "2020"
    - name: FASTAPI_WORKERS
      value: "4"
    - name: USE_GUNICORN
      value: "True"
    - name: DASHBOARD_ADMIN_PASSWORD
      value: h4L0m4St3R327
    - name: DATABASE_TYPE
      value: sqlite
    - name: DATABASE_PATH
      value: /data/comet.db
    - name: DATABASE_URL
      value: postgres:postgres@comet-postgres:5432/comet
    - name: METADATA_CACHE_TTL
      value: "2592000"
    - name: TORRENT_CACHE_TTL
      value: "1296000"
    - name: DEBRID_CACHE_TTL
      value: "86400"
    - name: INDEXER_MANAGER_TYPE
      value: prowlarr
    - name: INDEXER_MANAGER_URL
      value: http://prowlarr:9696
    - name: INDEXER_MANAGER_API_KEY
      value: 29440a82740d475cacb35327c62c87a1
    - name: INDEXER_MANAGER_TIMEOUT
      value: "60"
    - name: INDEXER_MANAGER_INDEXERS
      value: '["1337x", "animetosho", "anirena", "limetorrents", "nyaasi", "solidtorrents",
        "thepiratebay", "torlock", "yts"]'
    - name: GET_TORRENT_TIMEOUT
      value: "2"
    - name: DOWNLOAD_TORRENT_FILES
      value: "False"
    - name: SCRAPE_COMET
      value: "false"
    - name: COMET_URL
      value: https://comet.elfhosted.com
    - name: SCRAPE_ZILEAN
      value: "true"
    - name: ZILEAN_URL
      value: https://zilean.elfhosted.com
    - name: SCRAPE_TORRENTIO
      value: "false"
    - name: TORRENTIO_URL
      value: https://torrentio.strem.fun
    - name: SCRAPE_MEDIAFUSION
      value: "false"
    - name: MEDIAFUSION_URL
      value: https://mediafusion.elfhosted.com
    - name: STREMTHRU_URL
      value: https://stremthru.bolabaden.org
    - name: PROXY_DEBRID_STREAM
      value: "True"
    - name: PROXY_DEBRID_STREAM_PASSWORD
      value: h4L0m4St3R327
    - name: PROXY_DEBRID_STREAM_MAX_CONNECTIONS
      value: "-1"
    - name: PROXY_DEBRID_STREAM_DEBRID_DEFAULT_SERVICE
      value: premiumize
    - name: PROXY_DEBRID_STREAM_DEBRID_DEFAULT_APIKEY
      value: 6i6zgswm35baj3ur
    - name: REMOVE_ADULT_CONTENT
      value: "True"
    image: g0ldyy/comet:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health
        port: 2020
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 10
    name: comet
    ports:
    - containerPort: 2020
      name: comet-2020
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 2020
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: comet-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dhmcg
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /home/ubuntu/my-media-stack/configs/stremio/addons/comet/data
      type: DirectoryOrCreate
    name: comet-data
  - name: kube-api-access-dhmcg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T22:41:36Z"
    message: '0/3 nodes are available: 1 Insufficient memory, 2 Insufficient cpu.
      preemption: 0/3 nodes are available: 3 No preemption victims found for incoming
      pod.'
    reason: Unschedulable
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
