apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart-backup-pvc.fullname" . }}-backup
  labels:
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: my-media-stack
  {{- include "chart-backup-pvc.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: my-media-stack
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.backup.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.backup.storageClass | quote }}
