apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: gatus-config
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "1"
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: bolabaden
  labels:
    app.kubernetes.io/instance: brunner56
    app.kubernetes.io/name: gatus
    pod-template-hash: 59b6dff76d
  name: brunner56-gatus-59b6dff76d
  namespace: bolabaden
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: brunner56
      app.kubernetes.io/name: gatus
      pod-template-hash: 59b6dff76d
  template:
    metadata:
      creationTimestamp: "2025-05-29T17:12:59Z"
      labels:
        app.kubernetes.io/instance: brunner56
        app.kubernetes.io/name: gatus
        pod-template-hash: 59b6dff76d
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.elfhosted.com/role
                operator: In
                values:
                - nodefinder
            topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: false
      containers:
      - env:
        - name: GATUS_CONFIG_PATH
          value: /config/config.yaml
        - name: SMTP_FROM
          value: health@elfhosted.com
        - name: SMTP_PORT
          value: "587"
        envFrom:
        - secretRef:
            name: gatus-smtp-config
        image: ghcr.io/elfhosted/gatus:5.17.0@sha256:e2752cf7e1781478b12e0ca48159a40549905195afe39fe0a5e39ac2c7256dac
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        name: brunner56-gatus
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 128Mi
          requests:
            cpu: "0"
            memory: 20Mi
        securityContext:
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        startupProbe:
          failureThreshold: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/
          name: config
          subPath: gatus
        - mountPath: /config
          name: gatus-config
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      priorityClassName: tenant-normal
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 568
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
      - configMap:
          defaultMode: 420
          name: gatus-config
        name: gatus-config
