apiVersion: v1
data:
  config.yml: |
    auth:
      - user: brunner56
        group: brunner56
        uid: 568
        gid: 568
        password: brunner56


    global:
      - "force user = brunner56"
      - "force group = brunner56"

    share:
      - name: symlinks
        comment: symlinks
        path: /samba/symlinks-block
        browsable: yes
        readonly: no
        guestok: no
        veto: no
        recycle: no
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: bolabaden
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: bolabaden
  name: samba-config
  namespace: bolabaden
