apiVersion: v1
data:
  AUTH_HOST: brunner56-auth-me.elfhosted.com
  CLIENT_ID: XbLfjhaDz2Bnxce99YYhRkuxkzGrjjUr
  CLIENT_SECRET: wAHba6W7gGsmWTHGAx8ztQsUYEv6usuf
  COOKIE_DOMAIN: elfhosted.com
  COOKIE_NAME: brunner56-auth-me.elfhosted.com
  ENCRYPTION_KEY: TR9vQgnPNKgdNRLWMeGgAWq7Yy52fbPu
  LIFETIME: "2764800"
  LOGOUT_REDIRECT: https://store.elfhosted.com/my-account/customer-logout/
  PROVIDER_URI: https://store.elfhosted.com/
  SCOPE: openid email
  WHITELIST: boden.crouch@gmail.com
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: brunner56
    meta.helm.sh/release-namespace: bolabaden
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: brunner56
    helm.toolkit.fluxcd.io/namespace: bolabaden
  name: traefik-forward-auth-config
  namespace: bolabaden
