apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-14T22:04:18Z"
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/version: v1.14.0
    helm.sh/chart: cert-manager-v1.14.0
  name: cert-manager
  namespace: cert-manager
subsets:
- notReadyAddresses:
  - ip: 10.42.0.65
    nodeName: beatapostapita
    targetRef:
      kind: Pod
      name: cert-manager-9fd4dc6bf-rv5c4
      namespace: cert-manager
  ports:
  - name: tcp-prometheus-servicemonitor
    port: 9402
    protocol: TCP
