apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "1"
  labels:
    app.elfhosted.com/name: prowlarr
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: prowlarr
    pod-template-hash: 799895546f
  name: prowlarr-799895546f
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.elfhosted.com/name: prowlarr
      pod-template-hash: 799895546f
  template:
    metadata:
      labels:
        app.elfhosted.com/name: prowlarr
        app.kubernetes.io/instance: myprecious
        app.kubernetes.io/name: prowlarr
        pod-template-hash: 799895546f
    spec:
      containers:
      - image: linuxserver/prowlarr:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9696
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: prowlarr
        ports:
        - containerPort: 9696
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9696
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
          subPath: prowlarr
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
