# Suggestarr Configuration
CRON_TIMES: '0 0 * * *'
DB_HOST: 'suggestarr_db'
DB_NAME: 'suggestarr'
DB_PASSWORD: 'suggestarr'
DB_PORT: '5432'
DB_TYPE: 'postgres'
DB_USER: 'suggestarr'
FILTER_GENRES_EXCLUDE: []
FILTER_INCLUDE_NO_RATING: true
FILTER_LANGUAGE: 'en'
FILTER_NUM_SEASONS: null
FILTER_REGION_PROVIDER: null
FILTER_RELEASE_YEAR: null
FILTER_STREAMING_SERVICES: []
FILTER_TMDB_MIN_VOTES: null
FILTER_TMDB_THRESHOLD: null
HONOR_JELLYSEER_DISCOVERY: false
JELLYFIN_API_URL: 'http://jellyfin:8096'
JELLYFIN_LIBRARIES: []
JELLYFIN_TOKEN: '156d831d11574f95a0c87be8b7a4b964'
MAX_CONTENT_CHECKS: '10'
MAX_SIMILAR_MOVIE: '5'
MAX_SIMILAR_TV: '2'
PLEX_API_URL: 'http://plex:32400'
PLEX_LIBRARIES: []
PLEX_TOKEN: '18rS6gM-Wec22uq5Gw-U'
SEARCH_SIZE: '20'
SEER_API_URL: 'https://seer.bolabaden.org'
SEER_SESSION_TOKEN: null
SEER_TOKEN: '156d831d11574f95a0c87be8b7a4b964'
SEER_USER_NAME: ''
SEER_USER_PSW: ''
SELECTED_SERVICE: ''
SELECTED_USERS: []
SUBPATH: null
TMDB_API_KEY: 'cec876f852b9c15d2c1b436b1117dff7'
