addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.42.3.23
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: baden.vpshostingservice.co
  targetRef:
    kind: Pod
    name: jellyseerr-8574d6486d-4nl2l
    namespace: default
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-14T15:07:02Z"
  generateName: jellyseerr-
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: jellyseerr
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: jellyseerr
  name: jellyseerr-vr4sc
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: jellyseerr
ports:
- name: http
  port: 5055
  protocol: TCP
