addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.42.0.239
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: beatapostapita
  targetRef:
    kind: Pod
    name: jellyfin-5854fc967-mq6c6
    namespace: default
kind: EndpointSlice
metadata:
  generateName: jellyfin-
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: jellyfin
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: jellyfin
  name: jellyfin-lvxvd
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: jellyfin
ports:
- name: http
  port: 8096
  protocol: TCP
