addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.42.0.41
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: beatapostapita
  targetRef:
    kind: Pod
    name: overseerr-5866b7bfcc-64ckh
    namespace: default
kind: EndpointSlice
metadata:
  generateName: overseerr-
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: overseerr
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: overseerr
  name: overseerr-vj2vq
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: overseerr
ports:
- name: http
  port: 5055
  protocol: TCP
