addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.42.3.22
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: baden.vpshostingservice.co
  targetRef:
    kind: Pod
    name: riven-frontend-6b5dcd5f5f-gvzzn
    namespace: default
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-14T15:06:00Z"
  generateName: riven-frontend-
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: riven-frontend
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: riven-frontend
  name: riven-frontend-cwl2k
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: riven-frontend
ports:
- name: http
  port: 3000
  protocol: TCP
