addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.42.0.252
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: beatapostapita
  targetRef:
    kind: Pod
    name: sonarr-b7cd845f9-l8fg6
    namespace: default
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-14T22:04:27Z"
  generateName: sonarr-
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: sonarr
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: sonarr
  name: sonarr-bx62h
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: sonarr
ports:
- name: http
  port: 8989
  protocol: TCP
