apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt-prod","kubernetes.io/ingress.class":"traefik","traefik.ingress.kubernetes.io/router.entrypoints":"websecure","traefik.ingress.kubernetes.io/router.tls":"true"},"labels":{"app.kubernetes.io/component":"ingress","app.kubernetes.io/instance":"myprecious"},"name":"readarr-ingress","namespace":"default"},"spec":{"rules":[{"host":"readarr.elfhosted.com","http":{"paths":[{"backend":{"service":{"name":"readarr","port":{"number":8787}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["readarr.elfhosted.com"],"secretName":"readarr-tls"}]}}
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    app.kubernetes.io/component: ingress
    app.kubernetes.io/instance: myprecious
  name: readarr-ingress
  namespace: default
spec:
  rules:
  - host: readarr.elfhosted.com
    http:
      paths:
      - backend:
          service:
            name: readarr
            port:
              number: 8787
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - readarr.elfhosted.com
    secretName: readarr-tls
  loadBalancer:
    ingress:
    - ip: 10.0.0.81
    - ip: 107.172.71.172
    - ip: 209.54.102.83
