apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"maintenance","app.kubernetes.io/instance":"myprecious"},"name":"maintenance-operator","namespace":"default"}}
  labels:
    app.kubernetes.io/component: maintenance
    app.kubernetes.io/instance: myprecious
  name: maintenance-operator
  namespace: default
