apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.elfhosted.com/name":"plex","app.kubernetes.io/instance":"myprecious"},"name":"plex","namespace":"default"}}
  labels:
    app.elfhosted.com/name: plex
    app.kubernetes.io/instance: myprecious
  name: plex
  namespace: default
