apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.elfhosted.com/name":"prowlarr","app.kubernetes.io/instance":"myprecious"},"name":"prowlarr","namespace":"default"}}
  labels:
    app.elfhosted.com/name: prowlarr
    app.kubernetes.io/instance: myprecious
  name: prowlarr
  namespace: default
