apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2025-06-12T01:11:04Z"
  generateName: jellyseerr-8574d6486d-
  labels:
    app.elfhosted.com/name: jellyseerr
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: jellyseerr
    pod-template-hash: 8574d6486d
  name: jellyseerr-8574d6486d-4nl2l
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: jellyseerr-8574d6486d
spec:
  containers:
  - image: fallenbagel/jellyseerr:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 5055
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 10
    name: jellyseerr
    ports:
    - containerPort: 5055
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 5055
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /app/config
      name: config
      subPath: jellyseerr
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: baden.vpshostingservice.co
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: config
    persistentVolumeClaim:
      claimName: config
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T15:06:38Z"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T15:04:37Z"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T15:07:02Z"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T15:07:02Z"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T15:04:37Z"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://eedead5a9139416b0bdd9be9903c5cbde0393f48a76ff1d3a1e4ed18fe9d5842
    image: docker.io/fallenbagel/jellyseerr:latest
    imageID: docker.io/fallenbagel/jellyseerr@sha256:8f320036d937d84c385ea5800f87d69ba16ec4d3770fccf6cad803b5e8d66a52
    lastState: {}
    name: jellyseerr
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-06-14T15:06:37Z"
    volumeMounts:
    - mountPath: /app/config
      name: config
  hostIP: 209.54.102.83
  hostIPs:
  - ip: 209.54.102.83
  phase: Running
  podIP: 10.42.3.23
  podIPs:
  - ip: 10.42.3.23
  qosClass: Burstable
  startTime: "2025-06-14T15:04:37Z"
