apiVersion: v1
kind: Pod
metadata:
  generateName: node-exporter-
  labels:
    app.elfhosted.com/name: node-exporter
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: node-exporter
    controller-revision-hash: 5c595f64f4
    pod-template-generation: "1"
  name: node-exporter-m64xv
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: node-exporter
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - beatapostapita
  containers:
  - image: prom/node-exporter:latest
    imagePullPolicy: Always
    name: node-exporter
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/proc
      name: proc
      readOnly: true
    - mountPath: /host/sys
      name: sys
      readOnly: true
    - mountPath: /rootfs
      name: root
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: beatapostapita
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /proc
      type: ""
    name: proc
  - hostPath:
      path: /sys
      type: ""
    name: sys
  - hostPath:
      path: /
      type: ""
    name: root
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:24:22Z"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:24:20Z"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:24:22Z"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:24:22Z"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-06-14T17:24:20Z"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://756864999b2a48108280779111215a5968bf08465b42d72f91e9e88a6e1d73d3
    image: docker.io/prom/node-exporter:latest
    imageID: docker.io/prom/node-exporter@sha256:d00a542e409ee618a4edc67da14dd48c5da66726bbd5537ab2af9c1dfc442c8a
    lastState: {}
    name: node-exporter
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-06-14T17:24:21Z"
    volumeMounts:
    - mountPath: /host/proc
      name: proc
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /host/sys
      name: sys
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /rootfs
      name: root
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.0.0.81
  hostIPs:
  - ip: 10.0.0.81
  phase: Running
  podIP: 10.0.0.81
  podIPs:
  - ip: 10.0.0.81
  qosClass: Burstable
  startTime: "2025-06-14T17:24:20Z"
