apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-11T23:33:00Z"
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: jackettio
  name: jackettio
  namespace: default
