apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-12T00:03:36Z"
  labels:
    app.kubernetes.io/instance: myprecious
    app.kubernetes.io/name: rutorrent
  name: rutorrent
  namespace: default
